//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
#include <QSGNode>
#include <qsgnode.h>
#include "gen_qsgnode.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern C */
#endif

extern "C" void qtrhi_native_destroyed(void*);
extern "C" void qtrhi_callback_released(intptr_t);
QSGNode* qtrhi_QSGNode_new() {
	return new (std::nothrow) QSGNode();
}

void qtrhi_QSGNode_delete(QSGNode* self) {
	delete self;
}
