//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
#include <QByteArray>
#include <QImage>
#include <QList>
#include <QPair>
#include <QPoint>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#define WORKAROUND_INNER_CLASS_DEFINITION_QRhiGraphicsPipeline__StencilOpState
#define WORKAROUND_INNER_CLASS_DEFINITION_QRhiGraphicsPipeline__TargetBlend
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <rhi/qshader.h>
#include <QSize>
#include <QVector>
#include <rhi/qrhi.h>
#include "gen_qrhi.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern C */
#endif

extern "C" void qtrhi_native_destroyed(void*);
extern "C" void qtrhi_callback_released(intptr_t);
QRhiViewport* qtrhi_QRhiViewport_new() {
	return new (std::nothrow) QRhiViewport();
}

QRhiViewport* qtrhi_QRhiViewport_new2(float x, float y, float w, float h) {
	return new (std::nothrow) QRhiViewport(static_cast<float>(x), static_cast<float>(y), static_cast<float>(w), static_cast<float>(h));
}

QRhiViewport* qtrhi_QRhiViewport_new3(QRhiViewport* param1) {
	return new (std::nothrow) QRhiViewport(*param1);
}

QRhiViewport* qtrhi_QRhiViewport_new4(float x, float y, float w, float h, float minDepth) {
	return new (std::nothrow) QRhiViewport(static_cast<float>(x), static_cast<float>(y), static_cast<float>(w), static_cast<float>(h), static_cast<float>(minDepth));
}

QRhiViewport* qtrhi_QRhiViewport_new5(float x, float y, float w, float h, float minDepth, float maxDepth) {
	return new (std::nothrow) QRhiViewport(static_cast<float>(x), static_cast<float>(y), static_cast<float>(w), static_cast<float>(h), static_cast<float>(minDepth), static_cast<float>(maxDepth));
}

void qtrhi_QRhiViewport_delete(QRhiViewport* self) {
	delete self;
}

QRhiScissor* qtrhi_QRhiScissor_new() {
	return new (std::nothrow) QRhiScissor();
}

QRhiScissor* qtrhi_QRhiScissor_new2(int x, int y, int w, int h) {
	return new (std::nothrow) QRhiScissor(static_cast<int>(x), static_cast<int>(y), static_cast<int>(w), static_cast<int>(h));
}

QRhiScissor* qtrhi_QRhiScissor_new3(QRhiScissor* param1) {
	return new (std::nothrow) QRhiScissor(*param1);
}

void qtrhi_QRhiScissor_delete(QRhiScissor* self) {
	delete self;
}

QRhiVertexInputBinding* qtrhi_QRhiVertexInputBinding_new() {
	return new (std::nothrow) QRhiVertexInputBinding();
}

QRhiVertexInputBinding* qtrhi_QRhiVertexInputBinding_new2(uint32_t stride) {
	return new (std::nothrow) QRhiVertexInputBinding(static_cast<quint32>(stride));
}

QRhiVertexInputBinding* qtrhi_QRhiVertexInputBinding_new3(QRhiVertexInputBinding* param1) {
	return new (std::nothrow) QRhiVertexInputBinding(*param1);
}

QRhiVertexInputBinding* qtrhi_QRhiVertexInputBinding_new4(uint32_t stride, int cls) {
	return new (std::nothrow) QRhiVertexInputBinding(static_cast<quint32>(stride), static_cast<QRhiVertexInputBinding::Classification>(cls));
}

QRhiVertexInputBinding* qtrhi_QRhiVertexInputBinding_new5(uint32_t stride, int cls, uint32_t stepRate) {
	return new (std::nothrow) QRhiVertexInputBinding(static_cast<quint32>(stride), static_cast<QRhiVertexInputBinding::Classification>(cls), static_cast<quint32>(stepRate));
}

void qtrhi_QRhiVertexInputBinding_delete(QRhiVertexInputBinding* self) {
	delete self;
}

QRhiVertexInputAttribute* qtrhi_QRhiVertexInputAttribute_new() {
	return new (std::nothrow) QRhiVertexInputAttribute();
}

QRhiVertexInputAttribute* qtrhi_QRhiVertexInputAttribute_new2(int binding, int location, int format, uint32_t offset) {
	return new (std::nothrow) QRhiVertexInputAttribute(static_cast<int>(binding), static_cast<int>(location), static_cast<QRhiVertexInputAttribute::Format>(format), static_cast<quint32>(offset));
}

QRhiVertexInputAttribute* qtrhi_QRhiVertexInputAttribute_new3(QRhiVertexInputAttribute* param1) {
	return new (std::nothrow) QRhiVertexInputAttribute(*param1);
}

QRhiVertexInputAttribute* qtrhi_QRhiVertexInputAttribute_new4(int binding, int location, int format, uint32_t offset, int matrixSlice) {
	return new (std::nothrow) QRhiVertexInputAttribute(static_cast<int>(binding), static_cast<int>(location), static_cast<QRhiVertexInputAttribute::Format>(format), static_cast<quint32>(offset), static_cast<int>(matrixSlice));
}

void qtrhi_QRhiVertexInputAttribute_delete(QRhiVertexInputAttribute* self) {
	delete self;
}

QRhiVertexInputLayout* qtrhi_QRhiVertexInputLayout_new() {
	return new (std::nothrow) QRhiVertexInputLayout();
}

QRhiVertexInputLayout* qtrhi_QRhiVertexInputLayout_new2(QRhiVertexInputLayout* param1) {
	return new (std::nothrow) QRhiVertexInputLayout(*param1);
}

void qtrhi_QRhiVertexInputLayout_setBindings(QRhiVertexInputLayout* self, struct miqt_array /* of QRhiVertexInputBinding* */  list) {
	QList<QRhiVertexInputBinding> list_QList;
	list_QList.reserve(list.len);
	QRhiVertexInputBinding** list_arr = static_cast<QRhiVertexInputBinding**>(list.data);
	for(size_t i = 0; i < list.len; ++i) {
		list_QList.push_back(*(list_arr[i]));
	}
	self->setBindings(list_QList.cbegin(), list_QList.cend());
}

void qtrhi_QRhiVertexInputLayout_setAttributes(QRhiVertexInputLayout* self, struct miqt_array /* of QRhiVertexInputAttribute* */  list) {
	QList<QRhiVertexInputAttribute> list_QList;
	list_QList.reserve(list.len);
	QRhiVertexInputAttribute** list_arr = static_cast<QRhiVertexInputAttribute**>(list.data);
	for(size_t i = 0; i < list.len; ++i) {
		list_QList.push_back(*(list_arr[i]));
	}
	self->setAttributes(list_QList.cbegin(), list_QList.cend());
}

void qtrhi_QRhiVertexInputLayout_delete(QRhiVertexInputLayout* self) {
	delete self;
}

QRhiShaderStage* qtrhi_QRhiShaderStage_new() {
	return new (std::nothrow) QRhiShaderStage();
}

QRhiShaderStage* qtrhi_QRhiShaderStage_new2(int type, QShader* shader) {
	return new (std::nothrow) QRhiShaderStage(static_cast<QRhiShaderStage::Type>(type), *shader);
}

QRhiShaderStage* qtrhi_QRhiShaderStage_new3(QRhiShaderStage* param1) {
	return new (std::nothrow) QRhiShaderStage(*param1);
}

QRhiShaderStage* qtrhi_QRhiShaderStage_new4(int type, QShader* shader, int v) {
	return new (std::nothrow) QRhiShaderStage(static_cast<QRhiShaderStage::Type>(type), *shader, static_cast<QShader::Variant>(v));
}

void qtrhi_QRhiShaderStage_delete(QRhiShaderStage* self) {
	delete self;
}

QRhiShaderResourceBinding* qtrhi_QRhiShaderResourceBinding_new() {
	return new (std::nothrow) QRhiShaderResourceBinding();
}

QRhiShaderResourceBinding* qtrhi_QRhiShaderResourceBinding_new2(QRhiShaderResourceBinding* param1) {
	return new (std::nothrow) QRhiShaderResourceBinding(*param1);
}

QRhiShaderResourceBinding* qtrhi_QRhiShaderResourceBinding_uniformBufferWithDynamicOffset(int binding, int stage, QRhiBuffer* buf, uint32_t size) {
	return new QRhiShaderResourceBinding(QRhiShaderResourceBinding::uniformBufferWithDynamicOffset(static_cast<int>(binding), static_cast<QRhiShaderResourceBinding::StageFlags>(stage), buf, static_cast<quint32>(size)));
}

QRhiShaderResourceBinding* qtrhi_QRhiShaderResourceBinding_sampledTexture(int binding, int stage, QRhiTexture* tex, QRhiSampler* sampler) {
	return new QRhiShaderResourceBinding(QRhiShaderResourceBinding::sampledTexture(static_cast<int>(binding), static_cast<QRhiShaderResourceBinding::StageFlags>(stage), tex, sampler));
}

void qtrhi_QRhiShaderResourceBinding_delete(QRhiShaderResourceBinding* self) {
	delete self;
}

QRhiTextureSubresourceUploadDescription* qtrhi_QRhiTextureSubresourceUploadDescription_new() {
	return new (std::nothrow) QRhiTextureSubresourceUploadDescription();
}

QRhiTextureSubresourceUploadDescription* qtrhi_QRhiTextureSubresourceUploadDescription_new2(QImage* image) {
	return new (std::nothrow) QRhiTextureSubresourceUploadDescription(*image);
}

QRhiTextureSubresourceUploadDescription* qtrhi_QRhiTextureSubresourceUploadDescription_new3(const void* data, uint32_t size) {
	return new (std::nothrow) QRhiTextureSubresourceUploadDescription(data, static_cast<quint32>(size));
}

QRhiTextureSubresourceUploadDescription* qtrhi_QRhiTextureSubresourceUploadDescription_new4(struct miqt_string data) {
	QByteArray data_QByteArray(data.data, data.len);
	return new (std::nothrow) QRhiTextureSubresourceUploadDescription(data_QByteArray);
}

QRhiTextureSubresourceUploadDescription* qtrhi_QRhiTextureSubresourceUploadDescription_new5(QRhiTextureSubresourceUploadDescription* param1) {
	return new (std::nothrow) QRhiTextureSubresourceUploadDescription(*param1);
}

void qtrhi_QRhiTextureSubresourceUploadDescription_setDestinationTopLeft(QRhiTextureSubresourceUploadDescription* self, QPoint* p) {
	self->setDestinationTopLeft(*p);
}

void qtrhi_QRhiTextureSubresourceUploadDescription_setSourceSize(QRhiTextureSubresourceUploadDescription* self, QSize* size) {
	self->setSourceSize(*size);
}

void qtrhi_QRhiTextureSubresourceUploadDescription_delete(QRhiTextureSubresourceUploadDescription* self) {
	delete self;
}

QRhiTextureUploadEntry* qtrhi_QRhiTextureUploadEntry_new() {
	return new (std::nothrow) QRhiTextureUploadEntry();
}

QRhiTextureUploadEntry* qtrhi_QRhiTextureUploadEntry_new2(int layer, int level, QRhiTextureSubresourceUploadDescription* desc) {
	return new (std::nothrow) QRhiTextureUploadEntry(static_cast<int>(layer), static_cast<int>(level), *desc);
}

QRhiTextureUploadEntry* qtrhi_QRhiTextureUploadEntry_new3(QRhiTextureUploadEntry* param1) {
	return new (std::nothrow) QRhiTextureUploadEntry(*param1);
}

void qtrhi_QRhiTextureUploadEntry_delete(QRhiTextureUploadEntry* self) {
	delete self;
}

QRhiTextureUploadDescription* qtrhi_QRhiTextureUploadDescription_new() {
	return new (std::nothrow) QRhiTextureUploadDescription();
}

QRhiTextureUploadDescription* qtrhi_QRhiTextureUploadDescription_new2(QRhiTextureUploadEntry* entry) {
	return new (std::nothrow) QRhiTextureUploadDescription(*entry);
}

QRhiTextureUploadDescription* qtrhi_QRhiTextureUploadDescription_new3(QRhiTextureUploadDescription* param1) {
	return new (std::nothrow) QRhiTextureUploadDescription(*param1);
}

void qtrhi_QRhiTextureUploadDescription_setEntries(QRhiTextureUploadDescription* self, struct miqt_array /* of QRhiTextureUploadEntry* */  list) {
	QList<QRhiTextureUploadEntry> list_QList;
	list_QList.reserve(list.len);
	QRhiTextureUploadEntry** list_arr = static_cast<QRhiTextureUploadEntry**>(list.data);
	for(size_t i = 0; i < list.len; ++i) {
		list_QList.push_back(*(list_arr[i]));
	}
	self->setEntries(list_QList.cbegin(), list_QList.cend());
}

void qtrhi_QRhiTextureUploadDescription_delete(QRhiTextureUploadDescription* self) {
	delete self;
}

void qtrhi_QRhiResource_destroy(QRhiResource* self) {
	self->destroy();
}

void qtrhi_QRhiResource_deleteLater(QRhiResource* self) {
	self->deleteLater();
}

void qtrhi_QRhiResource_setName(QRhiResource* self, struct miqt_string name) {
	QByteArray name_QByteArray(name.data, name.len);
	self->setName(name_QByteArray);
}

void qtrhi_QRhiResource_delete(QRhiResource* self) {
	delete self;
}

void qtrhi_QRhiBuffer_virtbase(QRhiBuffer* src, QRhiResource** outptr_QRhiResource) {
	*outptr_QRhiResource = static_cast<QRhiResource*>(src);
}

uint32_t qtrhi_QRhiBuffer_size(const QRhiBuffer* self) {
	return self->size();
}

bool qtrhi_QRhiBuffer_create(QRhiBuffer* self) {
	return self->create();
}

void qtrhi_QRhiBuffer_delete(QRhiBuffer* self) {
	delete self;
}

void qtrhi_QRhiTexture_virtbase(QRhiTexture* src, QRhiResource** outptr_QRhiResource) {
	*outptr_QRhiResource = static_cast<QRhiResource*>(src);
}

QSize* qtrhi_QRhiTexture_pixelSize(const QRhiTexture* self) {
	return new QSize(self->pixelSize());
}

bool qtrhi_QRhiTexture_create(QRhiTexture* self) {
	return self->create();
}

void qtrhi_QRhiTexture_delete(QRhiTexture* self) {
	delete self;
}

void qtrhi_QRhiSampler_virtbase(QRhiSampler* src, QRhiResource** outptr_QRhiResource) {
	*outptr_QRhiResource = static_cast<QRhiResource*>(src);
}

bool qtrhi_QRhiSampler_create(QRhiSampler* self) {
	return self->create();
}

void qtrhi_QRhiSampler_delete(QRhiSampler* self) {
	delete self;
}

void qtrhi_QRhiRenderPassDescriptor_virtbase(QRhiRenderPassDescriptor* src, QRhiResource** outptr_QRhiResource) {
	*outptr_QRhiResource = static_cast<QRhiResource*>(src);
}

bool qtrhi_QRhiRenderPassDescriptor_isCompatible(const QRhiRenderPassDescriptor* self, QRhiRenderPassDescriptor* other) {
	return self->isCompatible(other);
}

struct miqt_array /* of uint32_t */  qtrhi_QRhiRenderPassDescriptor_serializedFormat(const QRhiRenderPassDescriptor* self) {
	QVector<quint32> _ret = self->serializedFormat();
	// Convert QList<> from C++ memory to manually-managed C memory
	uint32_t* _arr = static_cast<uint32_t*>(malloc(sizeof(uint32_t) * _ret.length()));
	for (size_t i = 0, e = _ret.length(); i < e; ++i) {
		_arr[i] = _ret[i];
	}
	struct miqt_array _out;
	_out.len = _ret.length();
	_out.data = static_cast<void*>(_arr);
	return _out;
}

void qtrhi_QRhiRenderPassDescriptor_delete(QRhiRenderPassDescriptor* self) {
	delete self;
}

void qtrhi_QRhiRenderTarget_virtbase(QRhiRenderTarget* src, QRhiResource** outptr_QRhiResource) {
	*outptr_QRhiResource = static_cast<QRhiResource*>(src);
}

QSize* qtrhi_QRhiRenderTarget_pixelSize(const QRhiRenderTarget* self) {
	return new QSize(self->pixelSize());
}

int qtrhi_QRhiRenderTarget_sampleCount(const QRhiRenderTarget* self) {
	return self->sampleCount();
}

QRhiRenderPassDescriptor* qtrhi_QRhiRenderTarget_renderPassDescriptor(const QRhiRenderTarget* self) {
	return self->renderPassDescriptor();
}

void qtrhi_QRhiRenderTarget_delete(QRhiRenderTarget* self) {
	delete self;
}

void qtrhi_QRhiShaderResourceBindings_virtbase(QRhiShaderResourceBindings* src, QRhiResource** outptr_QRhiResource) {
	*outptr_QRhiResource = static_cast<QRhiResource*>(src);
}

void qtrhi_QRhiShaderResourceBindings_setBindings(QRhiShaderResourceBindings* self, struct miqt_array /* of QRhiShaderResourceBinding* */  list) {
	QList<QRhiShaderResourceBinding> list_QList;
	list_QList.reserve(list.len);
	QRhiShaderResourceBinding** list_arr = static_cast<QRhiShaderResourceBinding**>(list.data);
	for(size_t i = 0; i < list.len; ++i) {
		list_QList.push_back(*(list_arr[i]));
	}
	self->setBindings(list_QList.cbegin(), list_QList.cend());
}

bool qtrhi_QRhiShaderResourceBindings_create(QRhiShaderResourceBindings* self) {
	return self->create();
}

void qtrhi_QRhiShaderResourceBindings_delete(QRhiShaderResourceBindings* self) {
	delete self;
}

void qtrhi_QRhiGraphicsPipeline_virtbase(QRhiGraphicsPipeline* src, QRhiResource** outptr_QRhiResource) {
	*outptr_QRhiResource = static_cast<QRhiResource*>(src);
}

void qtrhi_QRhiGraphicsPipeline_setFlags(QRhiGraphicsPipeline* self, int f) {
	self->setFlags(static_cast<QRhiGraphicsPipeline::Flags>(f));
}

void qtrhi_QRhiGraphicsPipeline_setTargetBlends(QRhiGraphicsPipeline* self, struct miqt_array /* of QRhiGraphicsPipeline__TargetBlend* */  list) {
	QList<QRhiGraphicsPipeline::TargetBlend> list_QList;
	list_QList.reserve(list.len);
	QRhiGraphicsPipeline__TargetBlend** list_arr = static_cast<QRhiGraphicsPipeline__TargetBlend**>(list.data);
	for(size_t i = 0; i < list.len; ++i) {
		list_QList.push_back(*(list_arr[i]));
	}
	self->setTargetBlends(list_QList.cbegin(), list_QList.cend());
}

void qtrhi_QRhiGraphicsPipeline_setDepthTest(QRhiGraphicsPipeline* self, bool enable) {
	self->setDepthTest(enable);
}

void qtrhi_QRhiGraphicsPipeline_setDepthWrite(QRhiGraphicsPipeline* self, bool enable) {
	self->setDepthWrite(enable);
}

void qtrhi_QRhiGraphicsPipeline_setStencilTest(QRhiGraphicsPipeline* self, bool enable) {
	self->setStencilTest(enable);
}

void qtrhi_QRhiGraphicsPipeline_setStencilFront(QRhiGraphicsPipeline* self, QRhiGraphicsPipeline__StencilOpState* state) {
	self->setStencilFront(*state);
}

void qtrhi_QRhiGraphicsPipeline_setStencilBack(QRhiGraphicsPipeline* self, QRhiGraphicsPipeline__StencilOpState* state) {
	self->setStencilBack(*state);
}

void qtrhi_QRhiGraphicsPipeline_setStencilReadMask(QRhiGraphicsPipeline* self, uint32_t mask) {
	self->setStencilReadMask(static_cast<quint32>(mask));
}

void qtrhi_QRhiGraphicsPipeline_setStencilWriteMask(QRhiGraphicsPipeline* self, uint32_t mask) {
	self->setStencilWriteMask(static_cast<quint32>(mask));
}

void qtrhi_QRhiGraphicsPipeline_setSampleCount(QRhiGraphicsPipeline* self, int s) {
	self->setSampleCount(static_cast<int>(s));
}

void qtrhi_QRhiGraphicsPipeline_setShaderStages(QRhiGraphicsPipeline* self, struct miqt_array /* of QRhiShaderStage* */  list) {
	QList<QRhiShaderStage> list_QList;
	list_QList.reserve(list.len);
	QRhiShaderStage** list_arr = static_cast<QRhiShaderStage**>(list.data);
	for(size_t i = 0; i < list.len; ++i) {
		list_QList.push_back(*(list_arr[i]));
	}
	self->setShaderStages(list_QList.cbegin(), list_QList.cend());
}

void qtrhi_QRhiGraphicsPipeline_setVertexInputLayout(QRhiGraphicsPipeline* self, QRhiVertexInputLayout* layout) {
	self->setVertexInputLayout(*layout);
}

void qtrhi_QRhiGraphicsPipeline_setShaderResourceBindings(QRhiGraphicsPipeline* self, QRhiShaderResourceBindings* srb) {
	self->setShaderResourceBindings(srb);
}

void qtrhi_QRhiGraphicsPipeline_setRenderPassDescriptor(QRhiGraphicsPipeline* self, QRhiRenderPassDescriptor* desc) {
	self->setRenderPassDescriptor(desc);
}

bool qtrhi_QRhiGraphicsPipeline_create(QRhiGraphicsPipeline* self) {
	return self->create();
}

void qtrhi_QRhiGraphicsPipeline_delete(QRhiGraphicsPipeline* self) {
	delete self;
}

void qtrhi_QRhiCommandBuffer_virtbase(QRhiCommandBuffer* src, QRhiResource** outptr_QRhiResource) {
	*outptr_QRhiResource = static_cast<QRhiResource*>(src);
}

void qtrhi_QRhiCommandBuffer_resourceUpdate(QRhiCommandBuffer* self, QRhiResourceUpdateBatch* resourceUpdates) {
	self->resourceUpdate(resourceUpdates);
}

void qtrhi_QRhiCommandBuffer_setGraphicsPipeline(QRhiCommandBuffer* self, QRhiGraphicsPipeline* ps) {
	self->setGraphicsPipeline(ps);
}

void qtrhi_QRhiCommandBuffer_setShaderResources(QRhiCommandBuffer* self) {
	self->setShaderResources();
}

void qtrhi_QRhiCommandBuffer_setVertexInput(QRhiCommandBuffer* self, int startBinding, int bindingCount, struct miqt_map /* tuple of QRhiBuffer* and uint32_t */  bindings) {
	QRhiCommandBuffer::VertexInput bindings_QPair;
	QRhiBuffer** bindings_first_arr = static_cast<QRhiBuffer**>(bindings.keys);
	uint32_t* bindings_second_arr = static_cast<uint32_t*>(bindings.values);
	bindings_QPair.first = bindings_first_arr[0];
	bindings_QPair.second = static_cast<quint32>(bindings_second_arr[0]);
	self->setVertexInput(static_cast<int>(startBinding), static_cast<int>(bindingCount), &bindings_QPair);
}

void qtrhi_QRhiCommandBuffer_setViewport(QRhiCommandBuffer* self, QRhiViewport* viewport) {
	self->setViewport(*viewport);
}

void qtrhi_QRhiCommandBuffer_setScissor(QRhiCommandBuffer* self, QRhiScissor* scissor) {
	self->setScissor(*scissor);
}

void qtrhi_QRhiCommandBuffer_setStencilRef(QRhiCommandBuffer* self, uint32_t refValue) {
	self->setStencilRef(static_cast<quint32>(refValue));
}

void qtrhi_QRhiCommandBuffer_draw(QRhiCommandBuffer* self, uint32_t vertexCount) {
	self->draw(static_cast<quint32>(vertexCount));
}

void qtrhi_QRhiCommandBuffer_drawIndexed(QRhiCommandBuffer* self, uint32_t indexCount) {
	self->drawIndexed(static_cast<quint32>(indexCount));
}

double qtrhi_QRhiCommandBuffer_lastCompletedGpuTime(QRhiCommandBuffer* self) {
	return self->lastCompletedGpuTime();
}

void qtrhi_QRhiCommandBuffer_setShaderResourcesWithSrb(QRhiCommandBuffer* self, QRhiShaderResourceBindings* srb) {
	self->setShaderResources(srb);
}

void qtrhi_QRhiCommandBuffer_setShaderResources2(QRhiCommandBuffer* self, QRhiShaderResourceBindings* srb, int dynamicOffsetCount) {
	self->setShaderResources(srb, static_cast<int>(dynamicOffsetCount));
}

void qtrhi_QRhiCommandBuffer_setShaderResources3(QRhiCommandBuffer* self, QRhiShaderResourceBindings* srb, int dynamicOffsetCount, struct miqt_map /* tuple of int and uint32_t */  dynamicOffsets) {
	QRhiCommandBuffer::DynamicOffset dynamicOffsets_QPair;
	int* dynamicOffsets_first_arr = static_cast<int*>(dynamicOffsets.keys);
	uint32_t* dynamicOffsets_second_arr = static_cast<uint32_t*>(dynamicOffsets.values);
	dynamicOffsets_QPair.first = static_cast<int>(dynamicOffsets_first_arr[0]);
	dynamicOffsets_QPair.second = static_cast<quint32>(dynamicOffsets_second_arr[0]);
	self->setShaderResources(srb, static_cast<int>(dynamicOffsetCount), &dynamicOffsets_QPair);
}

void qtrhi_QRhiCommandBuffer_setVertexInput2(QRhiCommandBuffer* self, int startBinding, int bindingCount, struct miqt_map /* tuple of QRhiBuffer* and uint32_t */  bindings, QRhiBuffer* indexBuf) {
	QRhiCommandBuffer::VertexInput bindings_QPair;
	QRhiBuffer** bindings_first_arr = static_cast<QRhiBuffer**>(bindings.keys);
	uint32_t* bindings_second_arr = static_cast<uint32_t*>(bindings.values);
	bindings_QPair.first = bindings_first_arr[0];
	bindings_QPair.second = static_cast<quint32>(bindings_second_arr[0]);
	self->setVertexInput(static_cast<int>(startBinding), static_cast<int>(bindingCount), &bindings_QPair, indexBuf);
}

void qtrhi_QRhiCommandBuffer_setVertexInput3(QRhiCommandBuffer* self, int startBinding, int bindingCount, struct miqt_map /* tuple of QRhiBuffer* and uint32_t */  bindings, QRhiBuffer* indexBuf, uint32_t indexOffset) {
	QRhiCommandBuffer::VertexInput bindings_QPair;
	QRhiBuffer** bindings_first_arr = static_cast<QRhiBuffer**>(bindings.keys);
	uint32_t* bindings_second_arr = static_cast<uint32_t*>(bindings.values);
	bindings_QPair.first = bindings_first_arr[0];
	bindings_QPair.second = static_cast<quint32>(bindings_second_arr[0]);
	self->setVertexInput(static_cast<int>(startBinding), static_cast<int>(bindingCount), &bindings_QPair, indexBuf, static_cast<quint32>(indexOffset));
}

void qtrhi_QRhiCommandBuffer_setVertexInput4(QRhiCommandBuffer* self, int startBinding, int bindingCount, struct miqt_map /* tuple of QRhiBuffer* and uint32_t */  bindings, QRhiBuffer* indexBuf, uint32_t indexOffset, int indexFormat) {
	QRhiCommandBuffer::VertexInput bindings_QPair;
	QRhiBuffer** bindings_first_arr = static_cast<QRhiBuffer**>(bindings.keys);
	uint32_t* bindings_second_arr = static_cast<uint32_t*>(bindings.values);
	bindings_QPair.first = bindings_first_arr[0];
	bindings_QPair.second = static_cast<quint32>(bindings_second_arr[0]);
	self->setVertexInput(static_cast<int>(startBinding), static_cast<int>(bindingCount), &bindings_QPair, indexBuf, static_cast<quint32>(indexOffset), static_cast<QRhiCommandBuffer::IndexFormat>(indexFormat));
}

void qtrhi_QRhiCommandBuffer_draw2(QRhiCommandBuffer* self, uint32_t vertexCount, uint32_t instanceCount) {
	self->draw(static_cast<quint32>(vertexCount), static_cast<quint32>(instanceCount));
}

void qtrhi_QRhiCommandBuffer_draw3(QRhiCommandBuffer* self, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex) {
	self->draw(static_cast<quint32>(vertexCount), static_cast<quint32>(instanceCount), static_cast<quint32>(firstVertex));
}

void qtrhi_QRhiCommandBuffer_draw4(QRhiCommandBuffer* self, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance) {
	self->draw(static_cast<quint32>(vertexCount), static_cast<quint32>(instanceCount), static_cast<quint32>(firstVertex), static_cast<quint32>(firstInstance));
}

void qtrhi_QRhiCommandBuffer_drawIndexed2(QRhiCommandBuffer* self, uint32_t indexCount, uint32_t instanceCount) {
	self->drawIndexed(static_cast<quint32>(indexCount), static_cast<quint32>(instanceCount));
}

void qtrhi_QRhiCommandBuffer_drawIndexed3(QRhiCommandBuffer* self, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex) {
	self->drawIndexed(static_cast<quint32>(indexCount), static_cast<quint32>(instanceCount), static_cast<quint32>(firstIndex));
}

void qtrhi_QRhiCommandBuffer_drawIndexed4(QRhiCommandBuffer* self, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t vertexOffset) {
	self->drawIndexed(static_cast<quint32>(indexCount), static_cast<quint32>(instanceCount), static_cast<quint32>(firstIndex), static_cast<qint32>(vertexOffset));
}

void qtrhi_QRhiCommandBuffer_drawIndexed5(QRhiCommandBuffer* self, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t vertexOffset, uint32_t firstInstance) {
	self->drawIndexed(static_cast<quint32>(indexCount), static_cast<quint32>(instanceCount), static_cast<quint32>(firstIndex), static_cast<qint32>(vertexOffset), static_cast<quint32>(firstInstance));
}

void qtrhi_QRhiCommandBuffer_delete(QRhiCommandBuffer* self) {
	delete self;
}

void qtrhi_QRhiResourceUpdateBatch_release(QRhiResourceUpdateBatch* self) {
	self->release();
}

void qtrhi_QRhiResourceUpdateBatch_updateDynamicBuffer(QRhiResourceUpdateBatch* self, QRhiBuffer* buf, uint32_t offset, uint32_t size, const void* data) {
	self->updateDynamicBuffer(buf, static_cast<quint32>(offset), static_cast<quint32>(size), data);
}

void qtrhi_QRhiResourceUpdateBatch_updateDynamicBuffer2(QRhiResourceUpdateBatch* self, QRhiBuffer* buf, uint32_t offset, struct miqt_string data) {
	QByteArray data_QByteArray(data.data, data.len);
	self->updateDynamicBuffer(buf, static_cast<quint32>(offset), data_QByteArray);
}

void qtrhi_QRhiResourceUpdateBatch_uploadStaticBuffer(QRhiResourceUpdateBatch* self, QRhiBuffer* buf, uint32_t offset, uint32_t size, const void* data) {
	self->uploadStaticBuffer(buf, static_cast<quint32>(offset), static_cast<quint32>(size), data);
}

void qtrhi_QRhiResourceUpdateBatch_uploadStaticBuffer2(QRhiResourceUpdateBatch* self, QRhiBuffer* buf, uint32_t offset, struct miqt_string data) {
	QByteArray data_QByteArray(data.data, data.len);
	self->uploadStaticBuffer(buf, static_cast<quint32>(offset), data_QByteArray);
}

void qtrhi_QRhiResourceUpdateBatch_uploadStaticBuffer3(QRhiResourceUpdateBatch* self, QRhiBuffer* buf, const void* data) {
	self->uploadStaticBuffer(buf, data);
}

void qtrhi_QRhiResourceUpdateBatch_uploadStaticBuffer4(QRhiResourceUpdateBatch* self, QRhiBuffer* buf, struct miqt_string data) {
	QByteArray data_QByteArray(data.data, data.len);
	self->uploadStaticBuffer(buf, data_QByteArray);
}

void qtrhi_QRhiResourceUpdateBatch_uploadTexture(QRhiResourceUpdateBatch* self, QRhiTexture* tex, QRhiTextureUploadDescription* desc) {
	self->uploadTexture(tex, *desc);
}

void qtrhi_QRhiResourceUpdateBatch_uploadTexture2(QRhiResourceUpdateBatch* self, QRhiTexture* tex, QImage* image) {
	self->uploadTexture(tex, *image);
}

void qtrhi_QRhiResourceUpdateBatch_delete(QRhiResourceUpdateBatch* self) {
	delete self;
}

QRhiDriverInfo* qtrhi_QRhiDriverInfo_new(QRhiDriverInfo* param1) {
	return new (std::nothrow) QRhiDriverInfo(*param1);
}

QRhiDriverInfo* qtrhi_QRhiDriverInfo_new2() {
	return new (std::nothrow) QRhiDriverInfo();
}

struct miqt_string qtrhi_QRhiDriverInfo_deviceName(const QRhiDriverInfo* self) {
	QByteArray deviceName_qb = self->deviceName;
	struct miqt_string deviceName_ms;
	deviceName_ms.len = deviceName_qb.length();
	deviceName_ms.data = static_cast<char*>(malloc(deviceName_ms.len));
	memcpy(deviceName_ms.data, deviceName_qb.data(), deviceName_ms.len);
	return deviceName_ms;
}

void qtrhi_QRhiDriverInfo_setDeviceName(QRhiDriverInfo* self, struct miqt_string deviceName) {
	QByteArray deviceName_QByteArray(deviceName.data, deviceName.len);
	self->deviceName = deviceName_QByteArray;
}

uint64_t qtrhi_QRhiDriverInfo_deviceId(const QRhiDriverInfo* self) {
	return self->deviceId;
}

void qtrhi_QRhiDriverInfo_setDeviceId(QRhiDriverInfo* self, uint64_t deviceId) {
	self->deviceId = static_cast<quint64>(deviceId);
}

uint64_t qtrhi_QRhiDriverInfo_vendorId(const QRhiDriverInfo* self) {
	return self->vendorId;
}

void qtrhi_QRhiDriverInfo_setVendorId(QRhiDriverInfo* self, uint64_t vendorId) {
	self->vendorId = static_cast<quint64>(vendorId);
}

int qtrhi_QRhiDriverInfo_deviceType(const QRhiDriverInfo* self) {
	QRhiDriverInfo::DeviceType deviceType_ret = self->deviceType;
	return static_cast<int>(deviceType_ret);
}

void qtrhi_QRhiDriverInfo_setDeviceType(QRhiDriverInfo* self, int deviceType) {
	self->deviceType = static_cast<QRhiDriverInfo::DeviceType>(deviceType);
}

void qtrhi_QRhiDriverInfo_delete(QRhiDriverInfo* self) {
	delete self;
}

int qtrhi_QRhi_backend(const QRhi* self) {
	QRhi::Implementation _ret = self->backend();
	return static_cast<int>(_ret);
}

const char* qtrhi_QRhi_backendName(const QRhi* self) {
	return (const char*) self->backendName();
}

const char* qtrhi_QRhi_backendNameWithImpl(int impl) {
	return (const char*) QRhi::backendName(static_cast<QRhi::Implementation>(impl));
}

QRhiDriverInfo* qtrhi_QRhi_driverInfo(const QRhi* self) {
	return new QRhiDriverInfo(self->driverInfo());
}

QRhiGraphicsPipeline* qtrhi_QRhi_newGraphicsPipeline(QRhi* self) {
	return self->newGraphicsPipeline();
}

QRhiShaderResourceBindings* qtrhi_QRhi_newShaderResourceBindings(QRhi* self) {
	return self->newShaderResourceBindings();
}

QRhiBuffer* qtrhi_QRhi_newBuffer(QRhi* self, int type, int usage, uint32_t size) {
	return self->newBuffer(static_cast<QRhiBuffer::Type>(type), static_cast<QRhiBuffer::UsageFlags>(usage), static_cast<quint32>(size));
}

QRhiTexture* qtrhi_QRhi_newTexture(QRhi* self, int format, QSize* pixelSize) {
	return self->newTexture(static_cast<QRhiTexture::Format>(format), *pixelSize);
}

QRhiTexture* qtrhi_QRhi_newTexture2(QRhi* self, int format, int width, int height, int depth) {
	return self->newTexture(static_cast<QRhiTexture::Format>(format), static_cast<int>(width), static_cast<int>(height), static_cast<int>(depth));
}

QRhiSampler* qtrhi_QRhi_newSampler(QRhi* self, int magFilter, int minFilter, int mipmapMode, int addressU, int addressV) {
	return self->newSampler(static_cast<QRhiSampler::Filter>(magFilter), static_cast<QRhiSampler::Filter>(minFilter), static_cast<QRhiSampler::Filter>(mipmapMode), static_cast<QRhiSampler::AddressMode>(addressU), static_cast<QRhiSampler::AddressMode>(addressV));
}

bool qtrhi_QRhi_isRecordingFrame(const QRhi* self) {
	return self->isRecordingFrame();
}

int qtrhi_QRhi_finish(QRhi* self) {
	QRhi::FrameOpResult _ret = self->finish();
	return static_cast<int>(_ret);
}

QRhiResourceUpdateBatch* qtrhi_QRhi_nextResourceUpdateBatch(QRhi* self) {
	return self->nextResourceUpdateBatch();
}

int qtrhi_QRhi_ubufAlignment(const QRhi* self) {
	return self->ubufAlignment();
}

int qtrhi_QRhi_ubufAligned(const QRhi* self, int v) {
	return self->ubufAligned(static_cast<int>(v));
}

bool qtrhi_QRhi_isYUpInFramebuffer(const QRhi* self) {
	return self->isYUpInFramebuffer();
}

bool qtrhi_QRhi_isFeatureSupported(const QRhi* self, int feature) {
	return self->isFeatureSupported(static_cast<QRhi::Feature>(feature));
}

bool qtrhi_QRhi_isDeviceLost(const QRhi* self) {
	return self->isDeviceLost();
}

QRhiTexture* qtrhi_QRhi_newTexture3(QRhi* self, int format, QSize* pixelSize, int sampleCount) {
	return self->newTexture(static_cast<QRhiTexture::Format>(format), *pixelSize, static_cast<int>(sampleCount));
}

QRhiTexture* qtrhi_QRhi_newTexture4(QRhi* self, int format, QSize* pixelSize, int sampleCount, int flags) {
	return self->newTexture(static_cast<QRhiTexture::Format>(format), *pixelSize, static_cast<int>(sampleCount), static_cast<QRhiTexture::Flags>(flags));
}

QRhiTexture* qtrhi_QRhi_newTexture5(QRhi* self, int format, int width, int height, int depth, int sampleCount) {
	return self->newTexture(static_cast<QRhiTexture::Format>(format), static_cast<int>(width), static_cast<int>(height), static_cast<int>(depth), static_cast<int>(sampleCount));
}

QRhiTexture* qtrhi_QRhi_newTexture6(QRhi* self, int format, int width, int height, int depth, int sampleCount, int flags) {
	return self->newTexture(static_cast<QRhiTexture::Format>(format), static_cast<int>(width), static_cast<int>(height), static_cast<int>(depth), static_cast<int>(sampleCount), static_cast<QRhiTexture::Flags>(flags));
}

QRhiSampler* qtrhi_QRhi_newSampler2(QRhi* self, int magFilter, int minFilter, int mipmapMode, int addressU, int addressV, int addressW) {
	return self->newSampler(static_cast<QRhiSampler::Filter>(magFilter), static_cast<QRhiSampler::Filter>(minFilter), static_cast<QRhiSampler::Filter>(mipmapMode), static_cast<QRhiSampler::AddressMode>(addressU), static_cast<QRhiSampler::AddressMode>(addressV), static_cast<QRhiSampler::AddressMode>(addressW));
}

void qtrhi_QRhi_delete(QRhi* self) {
	delete self;
}

QRhiGraphicsPipeline__TargetBlend* qtrhi_QRhiGraphicsPipeline__TargetBlend_new() {
	return new (std::nothrow) QRhiGraphicsPipeline::TargetBlend();
}

QRhiGraphicsPipeline__TargetBlend* qtrhi_QRhiGraphicsPipeline__TargetBlend_new2(QRhiGraphicsPipeline__TargetBlend* param1) {
	return new (std::nothrow) QRhiGraphicsPipeline::TargetBlend(*param1);
}

int qtrhi_QRhiGraphicsPipeline__TargetBlend_colorWrite(const QRhiGraphicsPipeline__TargetBlend* self) {
	QRhiGraphicsPipeline::ColorMask colorWrite_ret = self->colorWrite;
	return static_cast<int>(colorWrite_ret);
}

void qtrhi_QRhiGraphicsPipeline__TargetBlend_setColorWrite(QRhiGraphicsPipeline__TargetBlend* self, int colorWrite) {
	self->colorWrite = static_cast<QRhiGraphicsPipeline::ColorMask>(colorWrite);
}

bool qtrhi_QRhiGraphicsPipeline__TargetBlend_enable(const QRhiGraphicsPipeline__TargetBlend* self) {
	return self->enable;
}

void qtrhi_QRhiGraphicsPipeline__TargetBlend_setEnable(QRhiGraphicsPipeline__TargetBlend* self, bool enable) {
	self->enable = enable;
}

int qtrhi_QRhiGraphicsPipeline__TargetBlend_srcColor(const QRhiGraphicsPipeline__TargetBlend* self) {
	QRhiGraphicsPipeline::BlendFactor srcColor_ret = self->srcColor;
	return static_cast<int>(srcColor_ret);
}

void qtrhi_QRhiGraphicsPipeline__TargetBlend_setSrcColor(QRhiGraphicsPipeline__TargetBlend* self, int srcColor) {
	self->srcColor = static_cast<QRhiGraphicsPipeline::BlendFactor>(srcColor);
}

int qtrhi_QRhiGraphicsPipeline__TargetBlend_dstColor(const QRhiGraphicsPipeline__TargetBlend* self) {
	QRhiGraphicsPipeline::BlendFactor dstColor_ret = self->dstColor;
	return static_cast<int>(dstColor_ret);
}

void qtrhi_QRhiGraphicsPipeline__TargetBlend_setDstColor(QRhiGraphicsPipeline__TargetBlend* self, int dstColor) {
	self->dstColor = static_cast<QRhiGraphicsPipeline::BlendFactor>(dstColor);
}

int qtrhi_QRhiGraphicsPipeline__TargetBlend_opColor(const QRhiGraphicsPipeline__TargetBlend* self) {
	QRhiGraphicsPipeline::BlendOp opColor_ret = self->opColor;
	return static_cast<int>(opColor_ret);
}

void qtrhi_QRhiGraphicsPipeline__TargetBlend_setOpColor(QRhiGraphicsPipeline__TargetBlend* self, int opColor) {
	self->opColor = static_cast<QRhiGraphicsPipeline::BlendOp>(opColor);
}

int qtrhi_QRhiGraphicsPipeline__TargetBlend_srcAlpha(const QRhiGraphicsPipeline__TargetBlend* self) {
	QRhiGraphicsPipeline::BlendFactor srcAlpha_ret = self->srcAlpha;
	return static_cast<int>(srcAlpha_ret);
}

void qtrhi_QRhiGraphicsPipeline__TargetBlend_setSrcAlpha(QRhiGraphicsPipeline__TargetBlend* self, int srcAlpha) {
	self->srcAlpha = static_cast<QRhiGraphicsPipeline::BlendFactor>(srcAlpha);
}

int qtrhi_QRhiGraphicsPipeline__TargetBlend_dstAlpha(const QRhiGraphicsPipeline__TargetBlend* self) {
	QRhiGraphicsPipeline::BlendFactor dstAlpha_ret = self->dstAlpha;
	return static_cast<int>(dstAlpha_ret);
}

void qtrhi_QRhiGraphicsPipeline__TargetBlend_setDstAlpha(QRhiGraphicsPipeline__TargetBlend* self, int dstAlpha) {
	self->dstAlpha = static_cast<QRhiGraphicsPipeline::BlendFactor>(dstAlpha);
}

int qtrhi_QRhiGraphicsPipeline__TargetBlend_opAlpha(const QRhiGraphicsPipeline__TargetBlend* self) {
	QRhiGraphicsPipeline::BlendOp opAlpha_ret = self->opAlpha;
	return static_cast<int>(opAlpha_ret);
}

void qtrhi_QRhiGraphicsPipeline__TargetBlend_setOpAlpha(QRhiGraphicsPipeline__TargetBlend* self, int opAlpha) {
	self->opAlpha = static_cast<QRhiGraphicsPipeline::BlendOp>(opAlpha);
}

void qtrhi_QRhiGraphicsPipeline__TargetBlend_delete(QRhiGraphicsPipeline__TargetBlend* self) {
	delete self;
}

QRhiGraphicsPipeline__StencilOpState* qtrhi_QRhiGraphicsPipeline__StencilOpState_new() {
	return new (std::nothrow) QRhiGraphicsPipeline::StencilOpState();
}

QRhiGraphicsPipeline__StencilOpState* qtrhi_QRhiGraphicsPipeline__StencilOpState_new2(QRhiGraphicsPipeline__StencilOpState* param1) {
	return new (std::nothrow) QRhiGraphicsPipeline::StencilOpState(*param1);
}

int qtrhi_QRhiGraphicsPipeline__StencilOpState_failOp(const QRhiGraphicsPipeline__StencilOpState* self) {
	QRhiGraphicsPipeline::StencilOp failOp_ret = self->failOp;
	return static_cast<int>(failOp_ret);
}

void qtrhi_QRhiGraphicsPipeline__StencilOpState_setFailOp(QRhiGraphicsPipeline__StencilOpState* self, int failOp) {
	self->failOp = static_cast<QRhiGraphicsPipeline::StencilOp>(failOp);
}

int qtrhi_QRhiGraphicsPipeline__StencilOpState_depthFailOp(const QRhiGraphicsPipeline__StencilOpState* self) {
	QRhiGraphicsPipeline::StencilOp depthFailOp_ret = self->depthFailOp;
	return static_cast<int>(depthFailOp_ret);
}

void qtrhi_QRhiGraphicsPipeline__StencilOpState_setDepthFailOp(QRhiGraphicsPipeline__StencilOpState* self, int depthFailOp) {
	self->depthFailOp = static_cast<QRhiGraphicsPipeline::StencilOp>(depthFailOp);
}

int qtrhi_QRhiGraphicsPipeline__StencilOpState_passOp(const QRhiGraphicsPipeline__StencilOpState* self) {
	QRhiGraphicsPipeline::StencilOp passOp_ret = self->passOp;
	return static_cast<int>(passOp_ret);
}

void qtrhi_QRhiGraphicsPipeline__StencilOpState_setPassOp(QRhiGraphicsPipeline__StencilOpState* self, int passOp) {
	self->passOp = static_cast<QRhiGraphicsPipeline::StencilOp>(passOp);
}

int qtrhi_QRhiGraphicsPipeline__StencilOpState_compareOp(const QRhiGraphicsPipeline__StencilOpState* self) {
	QRhiGraphicsPipeline::CompareOp compareOp_ret = self->compareOp;
	return static_cast<int>(compareOp_ret);
}

void qtrhi_QRhiGraphicsPipeline__StencilOpState_setCompareOp(QRhiGraphicsPipeline__StencilOpState* self, int compareOp) {
	self->compareOp = static_cast<QRhiGraphicsPipeline::CompareOp>(compareOp);
}

void qtrhi_QRhiGraphicsPipeline__StencilOpState_delete(QRhiGraphicsPipeline__StencilOpState* self) {
	delete self;
}


static_assert(QT_VERSION == QT_VERSION_CHECK(6,11,2), "Regenerate QRhi bindings for this Qt version");
