//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
#include <QMatrix4x4>
#include <QRect>
#include <rhi/qrhi.h>
#include <rhi/qrhi.h>
#include <QSGNode>
#include <QSGRenderNode>
#define WORKAROUND_INNER_CLASS_DEFINITION_QSGRenderNode__RenderState
#include <qsgrendernode.h>
#include "gen_qsgrendernode.h"

#ifdef __cplusplus
extern "C" {
#endif

int qtrhi_miqt_exec_callback_QSGRenderNode_changedStates(const QSGRenderNode*, intptr_t);
void qtrhi_miqt_exec_callback_QSGRenderNode_prepare(QSGRenderNode*, intptr_t);
void qtrhi_miqt_exec_callback_QSGRenderNode_render(QSGRenderNode*, intptr_t, QSGRenderNode__RenderState*);
void qtrhi_miqt_exec_callback_QSGRenderNode_releaseResources(QSGRenderNode*, intptr_t);
int qtrhi_miqt_exec_callback_QSGRenderNode_flags(const QSGRenderNode*, intptr_t);
#ifdef __cplusplus
} /* extern C */
#endif

extern "C" void qtrhi_native_destroyed(void*);
extern "C" void qtrhi_callback_released(intptr_t);
class MiqtVirtualQSGRenderNode final : public QSGRenderNode {
public:

	MiqtVirtualQSGRenderNode(): QSGRenderNode() {}

	virtual ~MiqtVirtualQSGRenderNode() override { qtrhi_native_destroyed(this); if (handle__changedStates) qtrhi_callback_released(handle__changedStates); if (handle__prepare) qtrhi_callback_released(handle__prepare); if (handle__render) qtrhi_callback_released(handle__render); if (handle__releaseResources) qtrhi_callback_released(handle__releaseResources); if (handle__flags) qtrhi_callback_released(handle__flags);  }

	// cgo.Handle value for overwritten implementation
	intptr_t handle__changedStates = 0;

	// Subclass to allow providing a Go implementation
	virtual QSGRenderNode::StateFlags changedStates() const override {
		if (handle__changedStates == 0) {
			return QSGRenderNode::changedStates();
		}

		int callback_return_value = qtrhi_miqt_exec_callback_QSGRenderNode_changedStates(this, handle__changedStates);
		return static_cast<QSGRenderNode::StateFlags>(callback_return_value);
	}

	friend int qtrhi_QSGRenderNode_virtualbase_changedStates(const void* self);

	// cgo.Handle value for overwritten implementation
	intptr_t handle__prepare = 0;

	// Subclass to allow providing a Go implementation
	virtual void prepare() override {
		if (handle__prepare == 0) {
			QSGRenderNode::prepare();
			return;
		}

		qtrhi_miqt_exec_callback_QSGRenderNode_prepare(this, handle__prepare);

	}

	friend void qtrhi_QSGRenderNode_virtualbase_prepare(void* self);

	// cgo.Handle value for overwritten implementation
	intptr_t handle__render = 0;

	// Subclass to allow providing a Go implementation
	virtual void render(const QSGRenderNode::RenderState* state) override {
		if (handle__render == 0) {
			return; // Pure virtual, there is no base we can call
		}

		QSGRenderNode__RenderState* sigval1 = (QSGRenderNode__RenderState*) state;
		qtrhi_miqt_exec_callback_QSGRenderNode_render(this, handle__render, sigval1);

	}

	// cgo.Handle value for overwritten implementation
	intptr_t handle__releaseResources = 0;

	// Subclass to allow providing a Go implementation
	virtual void releaseResources() override {
		if (handle__releaseResources == 0) {
			QSGRenderNode::releaseResources();
			return;
		}

		qtrhi_miqt_exec_callback_QSGRenderNode_releaseResources(this, handle__releaseResources);

	}

	friend void qtrhi_QSGRenderNode_virtualbase_releaseResources(void* self);

	// cgo.Handle value for overwritten implementation
	intptr_t handle__flags = 0;

	// Subclass to allow providing a Go implementation
	virtual QSGRenderNode::RenderingFlags flags() const override {
		if (handle__flags == 0) {
			return QSGRenderNode::flags();
		}

		int callback_return_value = qtrhi_miqt_exec_callback_QSGRenderNode_flags(this, handle__flags);
		return static_cast<QSGRenderNode::RenderingFlags>(callback_return_value);
	}

	friend int qtrhi_QSGRenderNode_virtualbase_flags(const void* self);

};

QSGRenderNode* qtrhi_QSGRenderNode_new() {
	return new (std::nothrow) MiqtVirtualQSGRenderNode();
}

void qtrhi_QSGRenderNode_virtbase(QSGRenderNode* src, QSGNode** outptr_QSGNode) {
	*outptr_QSGNode = static_cast<QSGNode*>(src);
}

int qtrhi_QSGRenderNode_changedStates(const QSGRenderNode* self) {
	QSGRenderNode::StateFlags _ret = self->changedStates();
	return static_cast<int>(_ret);
}

void qtrhi_QSGRenderNode_prepare(QSGRenderNode* self) {
	self->prepare();
}

void qtrhi_QSGRenderNode_render(QSGRenderNode* self, QSGRenderNode__RenderState* state) {
	self->render(state);
}

void qtrhi_QSGRenderNode_releaseResources(QSGRenderNode* self) {
	self->releaseResources();
}

int qtrhi_QSGRenderNode_flags(const QSGRenderNode* self) {
	QSGRenderNode::RenderingFlags _ret = self->flags();
	return static_cast<int>(_ret);
}

QMatrix4x4* qtrhi_QSGRenderNode_projectionMatrix(const QSGRenderNode* self) {
	return (QMatrix4x4*) self->projectionMatrix();
}

QMatrix4x4* qtrhi_QSGRenderNode_projectionMatrixWithIndex(const QSGRenderNode* self, ptrdiff_t index) {
	return (QMatrix4x4*) self->projectionMatrix((qsizetype)(index));
}

QMatrix4x4* qtrhi_QSGRenderNode_matrix(const QSGRenderNode* self) {
	return (QMatrix4x4*) self->matrix();
}

double qtrhi_QSGRenderNode_inheritedOpacity(const QSGRenderNode* self) {
	return self->inheritedOpacity();
}

QRhiRenderTarget* qtrhi_QSGRenderNode_renderTarget(const QSGRenderNode* self) {
	return self->renderTarget();
}

QRhiCommandBuffer* qtrhi_QSGRenderNode_commandBuffer(const QSGRenderNode* self) {
	return self->commandBuffer();
}

bool qtrhi_QSGRenderNode_override_virtual_changedStates(void* self, intptr_t slot) {
	MiqtVirtualQSGRenderNode* self_cast = dynamic_cast<MiqtVirtualQSGRenderNode*>( (QSGRenderNode*)(self) );
	if (self_cast == nullptr) {
		return false;
	}

	if (self_cast->handle__changedStates != 0) return false;
	self_cast->handle__changedStates = slot;
	return true;
}

int qtrhi_QSGRenderNode_virtualbase_changedStates(const void* self) {
	MiqtVirtualQSGRenderNode::StateFlags _ret = static_cast<const MiqtVirtualQSGRenderNode*>(self)->QSGRenderNode::changedStates();
	return static_cast<int>(_ret);
}

bool qtrhi_QSGRenderNode_override_virtual_prepare(void* self, intptr_t slot) {
	MiqtVirtualQSGRenderNode* self_cast = dynamic_cast<MiqtVirtualQSGRenderNode*>( (QSGRenderNode*)(self) );
	if (self_cast == nullptr) {
		return false;
	}

	if (self_cast->handle__prepare != 0) return false;
	self_cast->handle__prepare = slot;
	return true;
}

void qtrhi_QSGRenderNode_virtualbase_prepare(void* self) {
	static_cast<MiqtVirtualQSGRenderNode*>(self)->QSGRenderNode::prepare();
}

bool qtrhi_QSGRenderNode_override_virtual_render(void* self, intptr_t slot) {
	MiqtVirtualQSGRenderNode* self_cast = dynamic_cast<MiqtVirtualQSGRenderNode*>( (QSGRenderNode*)(self) );
	if (self_cast == nullptr) {
		return false;
	}

	if (self_cast->handle__render != 0) return false;
	self_cast->handle__render = slot;
	return true;
}

bool qtrhi_QSGRenderNode_override_virtual_releaseResources(void* self, intptr_t slot) {
	MiqtVirtualQSGRenderNode* self_cast = dynamic_cast<MiqtVirtualQSGRenderNode*>( (QSGRenderNode*)(self) );
	if (self_cast == nullptr) {
		return false;
	}

	if (self_cast->handle__releaseResources != 0) return false;
	self_cast->handle__releaseResources = slot;
	return true;
}

void qtrhi_QSGRenderNode_virtualbase_releaseResources(void* self) {
	static_cast<MiqtVirtualQSGRenderNode*>(self)->QSGRenderNode::releaseResources();
}

bool qtrhi_QSGRenderNode_override_virtual_flags(void* self, intptr_t slot) {
	MiqtVirtualQSGRenderNode* self_cast = dynamic_cast<MiqtVirtualQSGRenderNode*>( (QSGRenderNode*)(self) );
	if (self_cast == nullptr) {
		return false;
	}

	if (self_cast->handle__flags != 0) return false;
	self_cast->handle__flags = slot;
	return true;
}

int qtrhi_QSGRenderNode_virtualbase_flags(const void* self) {
	MiqtVirtualQSGRenderNode::RenderingFlags _ret = static_cast<const MiqtVirtualQSGRenderNode*>(self)->QSGRenderNode::flags();
	return static_cast<int>(_ret);
}

void qtrhi_QSGRenderNode_delete(QSGRenderNode* self) {
	delete self;
}

QRect* qtrhi_QSGRenderNode__RenderState_scissorRect(const QSGRenderNode__RenderState* self) {
	return new QRect(self->scissorRect());
}

bool qtrhi_QSGRenderNode__RenderState_scissorEnabled(const QSGRenderNode__RenderState* self) {
	return self->scissorEnabled();
}

int qtrhi_QSGRenderNode__RenderState_stencilValue(const QSGRenderNode__RenderState* self) {
	return self->stencilValue();
}

bool qtrhi_QSGRenderNode__RenderState_stencilEnabled(const QSGRenderNode__RenderState* self) {
	return self->stencilEnabled();
}

void qtrhi_QSGRenderNode__RenderState_delete(QSGRenderNode__RenderState* self) {
	delete self;
}
