//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
package qtrhi

/*

#include "gen_qquickgraphicsconfiguration.h"
#include <stdlib.h>

*/
import "C"

import (
	"runtime"
	"unsafe"
)

type QQuickGraphicsConfiguration struct {
	h *C.QQuickGraphicsConfiguration
}

func (this *QQuickGraphicsConfiguration) cPointer() *C.QQuickGraphicsConfiguration {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QQuickGraphicsConfiguration) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQQuickGraphicsConfiguration constructs the type using only CGO pointers.
func newQQuickGraphicsConfiguration(h *C.QQuickGraphicsConfiguration) *QQuickGraphicsConfiguration {
	if h == nil {
		return nil
	}

	return &QQuickGraphicsConfiguration{h: h}
}

// UnsafeNewQQuickGraphicsConfiguration constructs the type using only unsafe pointers.
func UnsafeNewQQuickGraphicsConfiguration(h unsafe.Pointer) *QQuickGraphicsConfiguration {
	return newQQuickGraphicsConfiguration((*C.QQuickGraphicsConfiguration)(h))
}

// NewQQuickGraphicsConfiguration constructs a new QQuickGraphicsConfiguration object.
func NewQQuickGraphicsConfiguration() *QQuickGraphicsConfiguration {

	return newQQuickGraphicsConfiguration(C.qtrhi_QQuickGraphicsConfiguration_new())
}

// NewQQuickGraphicsConfiguration2 constructs a new QQuickGraphicsConfiguration object.
func NewQQuickGraphicsConfiguration2(other *QQuickGraphicsConfiguration) *QQuickGraphicsConfiguration {

	return newQQuickGraphicsConfiguration(C.qtrhi_QQuickGraphicsConfiguration_new2(other.cPointer()))
}

func (this *QQuickGraphicsConfiguration) SetTimestamps(enable bool) {
	C.qtrhi_QQuickGraphicsConfiguration_setTimestamps(this.h, (C.bool)(enable))
}

// Delete this object from C++ memory.
func (this *QQuickGraphicsConfiguration) Delete() {
	C.qtrhi_QQuickGraphicsConfiguration_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QQuickGraphicsConfiguration) GoGC() {
	runtime.SetFinalizer(this, func(this *QQuickGraphicsConfiguration) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}
