//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
#include <QObject>
#include <QQmlParserStatus>
#include <QQuickItem>
#define WORKAROUND_INNER_CLASS_DEFINITION_QQuickItem__UpdatePaintNodeData
#include <QQuickWindow>
#include <QSGNode>
#include <qquickitem.h>
#include "gen_qquickitem.h"

#ifdef __cplusplus
extern "C" {
#endif

QSGNode* qtrhi_miqt_exec_callback_QQuickItem_updatePaintNode(QQuickItem*, intptr_t, QSGNode*, QQuickItem__UpdatePaintNodeData*);
#ifdef __cplusplus
} /* extern C */
#endif

extern "C" void qtrhi_native_destroyed(void*);
extern "C" void qtrhi_callback_released(intptr_t);
class MiqtVirtualQQuickItem final : public QQuickItem {
public:

	MiqtVirtualQQuickItem(): QQuickItem() {}
	MiqtVirtualQQuickItem(QQuickItem* parent): QQuickItem(parent) {}

	virtual ~MiqtVirtualQQuickItem() override { qtrhi_native_destroyed(this); if (handle__updatePaintNode) qtrhi_callback_released(handle__updatePaintNode);  }

	// cgo.Handle value for overwritten implementation
	intptr_t handle__updatePaintNode = 0;

	// Subclass to allow providing a Go implementation
	virtual QSGNode* updatePaintNode(QSGNode* param1, QQuickItem::UpdatePaintNodeData* param2) override {
		if (handle__updatePaintNode == 0) {
			return QQuickItem::updatePaintNode(param1, param2);
		}

		QSGNode* sigval1 = param1;
		QQuickItem__UpdatePaintNodeData* sigval2 = param2;
		QSGNode* callback_return_value = qtrhi_miqt_exec_callback_QQuickItem_updatePaintNode(this, handle__updatePaintNode, sigval1, sigval2);
		return callback_return_value;
	}

	friend QSGNode* qtrhi_QQuickItem_virtualbase_updatePaintNode(void* self, QSGNode* param1, QQuickItem__UpdatePaintNodeData* param2);

};

QQuickItem* qtrhi_QQuickItem_new() {
	return new (std::nothrow) MiqtVirtualQQuickItem();
}

QQuickItem* qtrhi_QQuickItem_new2(QQuickItem* parent) {
	return new (std::nothrow) MiqtVirtualQQuickItem(parent);
}

void qtrhi_QQuickItem_virtbase(QQuickItem* src, QObject** outptr_QObject, QQmlParserStatus** outptr_QQmlParserStatus) {
	*outptr_QObject = static_cast<QObject*>(src);
	*outptr_QQmlParserStatus = static_cast<QQmlParserStatus*>(src);
}

QQuickWindow* qtrhi_QQuickItem_window(const QQuickItem* self) {
	return self->window();
}

double qtrhi_QQuickItem_width(const QQuickItem* self) {
	return self->width();
}

void qtrhi_QQuickItem_setWidth(QQuickItem* self, double width) {
	self->setWidth(static_cast<qreal>(width));
}

double qtrhi_QQuickItem_height(const QQuickItem* self) {
	return self->height();
}

void qtrhi_QQuickItem_setHeight(QQuickItem* self, double height) {
	self->setHeight(static_cast<qreal>(height));
}

void qtrhi_QQuickItem_setFlag(QQuickItem* self, int flag) {
	self->setFlag(static_cast<QQuickItem::Flag>(flag));
}

void qtrhi_QQuickItem_update(QQuickItem* self) {
	self->update();
}

void qtrhi_QQuickItem_setFlag2(QQuickItem* self, int flag, bool enabled) {
	self->setFlag(static_cast<QQuickItem::Flag>(flag), enabled);
}

bool qtrhi_QQuickItem_override_virtual_updatePaintNode(void* self, intptr_t slot) {
	MiqtVirtualQQuickItem* self_cast = dynamic_cast<MiqtVirtualQQuickItem*>( (QQuickItem*)(self) );
	if (self_cast == nullptr) {
		return false;
	}

	if (self_cast->handle__updatePaintNode != 0) return false;
	self_cast->handle__updatePaintNode = slot;
	return true;
}

QSGNode* qtrhi_QQuickItem_virtualbase_updatePaintNode(void* self, QSGNode* param1, QQuickItem__UpdatePaintNodeData* param2) {
	return static_cast<MiqtVirtualQQuickItem*>(self)->QQuickItem::updatePaintNode(param1, param2);
}

void qtrhi_QQuickItem_delete(QQuickItem* self) {
	delete self;
}

void qtrhi_QQuickItem__UpdatePaintNodeData_delete(QQuickItem__UpdatePaintNodeData* self) {
	delete self;
}
