//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
package qtrhi

/*

#include "gen_qsgrendernode.h"
#include <stdlib.h>

*/
import "C"

import (
	"github.com/mappu/miqt/qt6"
	"runtime"
	"runtime/cgo"
	"unsafe"
)

type QSGRenderNode__StateFlag int

const (
	QSGRenderNode__DepthState        QSGRenderNode__StateFlag = 1
	QSGRenderNode__StencilState      QSGRenderNode__StateFlag = 2
	QSGRenderNode__ScissorState      QSGRenderNode__StateFlag = 4
	QSGRenderNode__ColorState        QSGRenderNode__StateFlag = 8
	QSGRenderNode__BlendState        QSGRenderNode__StateFlag = 16
	QSGRenderNode__CullState         QSGRenderNode__StateFlag = 32
	QSGRenderNode__ViewportState     QSGRenderNode__StateFlag = 64
	QSGRenderNode__RenderTargetState QSGRenderNode__StateFlag = 128
)

type QSGRenderNode__RenderingFlag int

const (
	QSGRenderNode__BoundedRectRendering QSGRenderNode__RenderingFlag = 1
	QSGRenderNode__DepthAwareRendering  QSGRenderNode__RenderingFlag = 2
	QSGRenderNode__OpaqueRendering      QSGRenderNode__RenderingFlag = 4
	QSGRenderNode__NoExternalRendering  QSGRenderNode__RenderingFlag = 8
)

type QSGRenderNode struct {
	h *C.QSGRenderNode
	*QSGNode
}

func (this *QSGRenderNode) cPointer() *C.QSGRenderNode {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGRenderNode) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGRenderNode constructs the type using only CGO pointers.
func newQSGRenderNode(h *C.QSGRenderNode) *QSGRenderNode {
	if h == nil {
		return nil
	}
	var outptr_QSGNode *C.QSGNode = nil
	C.qtrhi_QSGRenderNode_virtbase(h, &outptr_QSGNode)

	return &QSGRenderNode{h: h,
		QSGNode: newQSGNode(outptr_QSGNode)}
}

// UnsafeNewQSGRenderNode constructs the type using only unsafe pointers.
func UnsafeNewQSGRenderNode(h unsafe.Pointer) *QSGRenderNode {
	return newQSGRenderNode((*C.QSGRenderNode)(h))
}

// NewQSGRenderNode constructs a new QSGRenderNode object.
func NewQSGRenderNode() *QSGRenderNode {

	return newQSGRenderNode(C.qtrhi_QSGRenderNode_new())
}

func (this *QSGRenderNode) ChangedStates() QSGRenderNode__StateFlag {
	return (QSGRenderNode__StateFlag)(C.qtrhi_QSGRenderNode_changedStates(this.h))
}

func (this *QSGRenderNode) Prepare() {
	C.qtrhi_QSGRenderNode_prepare(this.h)
}

func (this *QSGRenderNode) Render(state *QSGRenderNode__RenderState) {
	C.qtrhi_QSGRenderNode_render(this.h, state.cPointer())
}

func (this *QSGRenderNode) ReleaseResources() {
	C.qtrhi_QSGRenderNode_releaseResources(this.h)
}

func (this *QSGRenderNode) Flags() QSGRenderNode__RenderingFlag {
	return (QSGRenderNode__RenderingFlag)(C.qtrhi_QSGRenderNode_flags(this.h))
}

func (this *QSGRenderNode) ProjectionMatrix() *qt6.QMatrix4x4 {
	return qt6.UnsafeNewQMatrix4x4(unsafe.Pointer(C.qtrhi_QSGRenderNode_projectionMatrix(this.h)))
}

func (this *QSGRenderNode) ProjectionMatrixWithIndex(index int64) *qt6.QMatrix4x4 {
	return qt6.UnsafeNewQMatrix4x4(unsafe.Pointer(C.qtrhi_QSGRenderNode_projectionMatrixWithIndex(this.h, (C.ptrdiff_t)(index))))
}

func (this *QSGRenderNode) Matrix() *qt6.QMatrix4x4 {
	return qt6.UnsafeNewQMatrix4x4(unsafe.Pointer(C.qtrhi_QSGRenderNode_matrix(this.h)))
}

func (this *QSGRenderNode) InheritedOpacity() float64 {
	return (float64)(C.qtrhi_QSGRenderNode_inheritedOpacity(this.h))
}

func (this *QSGRenderNode) RenderTarget() *QRhiRenderTarget {
	return newQRhiRenderTarget(C.qtrhi_QSGRenderNode_renderTarget(this.h))
}

func (this *QSGRenderNode) CommandBuffer() *QRhiCommandBuffer {
	return newQRhiCommandBuffer(C.qtrhi_QSGRenderNode_commandBuffer(this.h))
}

func (this *QSGRenderNode) callVirtualBase_ChangedStates() QSGRenderNode__StateFlag {

	return (QSGRenderNode__StateFlag)(C.qtrhi_QSGRenderNode_virtualbase_changedStates(unsafe.Pointer(this.h)))

}
func (this *QSGRenderNode) OnChangedStates(slot func(super func() QSGRenderNode__StateFlag) QSGRenderNode__StateFlag) {
	handle := cgo.NewHandle(slot)
	ok := C.qtrhi_QSGRenderNode_override_virtual_changedStates(unsafe.Pointer(this.h), C.intptr_t(handle))
	if !ok {
		handle.Delete()
		panic("miqt: can only override virtual methods for directly constructed types")
	}
}

//export qtrhi_miqt_exec_callback_QSGRenderNode_changedStates
func qtrhi_miqt_exec_callback_QSGRenderNode_changedStates(self *C.QSGRenderNode, cb C.intptr_t) C.int {
	gofunc, ok := cgo.Handle(cb).Value().(func(super func() QSGRenderNode__StateFlag) QSGRenderNode__StateFlag)
	if !ok {
		panic("miqt: callback of non-callback type (heap corruption?)")
	}

	virtualReturn := gofunc((&QSGRenderNode{h: self}).callVirtualBase_ChangedStates)

	return (C.int)(virtualReturn)

}

func (this *QSGRenderNode) callVirtualBase_Prepare() {

	C.qtrhi_QSGRenderNode_virtualbase_prepare(unsafe.Pointer(this.h))

}
func (this *QSGRenderNode) OnPrepare(slot func(super func())) {
	handle := cgo.NewHandle(slot)
	ok := C.qtrhi_QSGRenderNode_override_virtual_prepare(unsafe.Pointer(this.h), C.intptr_t(handle))
	if !ok {
		handle.Delete()
		panic("miqt: can only override virtual methods for directly constructed types")
	}
}

//export qtrhi_miqt_exec_callback_QSGRenderNode_prepare
func qtrhi_miqt_exec_callback_QSGRenderNode_prepare(self *C.QSGRenderNode, cb C.intptr_t) {
	gofunc, ok := cgo.Handle(cb).Value().(func(super func()))
	if !ok {
		panic("miqt: callback of non-callback type (heap corruption?)")
	}

	gofunc((&QSGRenderNode{h: self}).callVirtualBase_Prepare)

}
func (this *QSGRenderNode) OnRender(slot func(state *QSGRenderNode__RenderState)) {
	handle := cgo.NewHandle(slot)
	ok := C.qtrhi_QSGRenderNode_override_virtual_render(unsafe.Pointer(this.h), C.intptr_t(handle))
	if !ok {
		handle.Delete()
		panic("miqt: can only override virtual methods for directly constructed types")
	}
}

//export qtrhi_miqt_exec_callback_QSGRenderNode_render
func qtrhi_miqt_exec_callback_QSGRenderNode_render(self *C.QSGRenderNode, cb C.intptr_t, state *C.QSGRenderNode__RenderState) {
	gofunc, ok := cgo.Handle(cb).Value().(func(state *QSGRenderNode__RenderState))
	if !ok {
		panic("miqt: callback of non-callback type (heap corruption?)")
	}

	// Convert all CABI parameters to Go parameters
	slotval1 := newQSGRenderNode__RenderState(state)

	gofunc(slotval1)

}

func (this *QSGRenderNode) callVirtualBase_ReleaseResources() {

	C.qtrhi_QSGRenderNode_virtualbase_releaseResources(unsafe.Pointer(this.h))

}
func (this *QSGRenderNode) OnReleaseResources(slot func(super func())) {
	handle := cgo.NewHandle(slot)
	ok := C.qtrhi_QSGRenderNode_override_virtual_releaseResources(unsafe.Pointer(this.h), C.intptr_t(handle))
	if !ok {
		handle.Delete()
		panic("miqt: can only override virtual methods for directly constructed types")
	}
}

//export qtrhi_miqt_exec_callback_QSGRenderNode_releaseResources
func qtrhi_miqt_exec_callback_QSGRenderNode_releaseResources(self *C.QSGRenderNode, cb C.intptr_t) {
	gofunc, ok := cgo.Handle(cb).Value().(func(super func()))
	if !ok {
		panic("miqt: callback of non-callback type (heap corruption?)")
	}

	gofunc((&QSGRenderNode{h: self}).callVirtualBase_ReleaseResources)

}

func (this *QSGRenderNode) callVirtualBase_Flags() QSGRenderNode__RenderingFlag {

	return (QSGRenderNode__RenderingFlag)(C.qtrhi_QSGRenderNode_virtualbase_flags(unsafe.Pointer(this.h)))

}
func (this *QSGRenderNode) OnFlags(slot func(super func() QSGRenderNode__RenderingFlag) QSGRenderNode__RenderingFlag) {
	handle := cgo.NewHandle(slot)
	ok := C.qtrhi_QSGRenderNode_override_virtual_flags(unsafe.Pointer(this.h), C.intptr_t(handle))
	if !ok {
		handle.Delete()
		panic("miqt: can only override virtual methods for directly constructed types")
	}
}

//export qtrhi_miqt_exec_callback_QSGRenderNode_flags
func qtrhi_miqt_exec_callback_QSGRenderNode_flags(self *C.QSGRenderNode, cb C.intptr_t) C.int {
	gofunc, ok := cgo.Handle(cb).Value().(func(super func() QSGRenderNode__RenderingFlag) QSGRenderNode__RenderingFlag)
	if !ok {
		panic("miqt: callback of non-callback type (heap corruption?)")
	}

	virtualReturn := gofunc((&QSGRenderNode{h: self}).callVirtualBase_Flags)

	return (C.int)(virtualReturn)

}

// Delete this object from C++ memory.
func (this *QSGRenderNode) Delete() {
	C.qtrhi_QSGRenderNode_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QSGRenderNode) GoGC() {
	runtime.SetFinalizer(this, func(this *QSGRenderNode) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QSGRenderNode__RenderState struct {
	h *C.QSGRenderNode__RenderState
}

func (this *QSGRenderNode__RenderState) cPointer() *C.QSGRenderNode__RenderState {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGRenderNode__RenderState) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGRenderNode__RenderState constructs the type using only CGO pointers.
func newQSGRenderNode__RenderState(h *C.QSGRenderNode__RenderState) *QSGRenderNode__RenderState {
	if h == nil {
		return nil
	}

	return &QSGRenderNode__RenderState{h: h}
}

// UnsafeNewQSGRenderNode__RenderState constructs the type using only unsafe pointers.
func UnsafeNewQSGRenderNode__RenderState(h unsafe.Pointer) *QSGRenderNode__RenderState {
	return newQSGRenderNode__RenderState((*C.QSGRenderNode__RenderState)(h))
}

func (this *QSGRenderNode__RenderState) ScissorRect() *qt6.QRect {
	_goptr := qt6.UnsafeNewQRect(unsafe.Pointer(C.qtrhi_QSGRenderNode__RenderState_scissorRect(this.h)))
	return _goptr
}

func (this *QSGRenderNode__RenderState) ScissorEnabled() bool {
	return (bool)(C.qtrhi_QSGRenderNode__RenderState_scissorEnabled(this.h))
}

func (this *QSGRenderNode__RenderState) StencilValue() int {
	return (int)(C.qtrhi_QSGRenderNode__RenderState_stencilValue(this.h))
}

func (this *QSGRenderNode__RenderState) StencilEnabled() bool {
	return (bool)(C.qtrhi_QSGRenderNode__RenderState_stencilEnabled(this.h))
}

// Delete this object from C++ memory.
func (this *QSGRenderNode__RenderState) Delete() {
	C.qtrhi_QSGRenderNode__RenderState_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QSGRenderNode__RenderState) GoGC() {
	runtime.SetFinalizer(this, func(this *QSGRenderNode__RenderState) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}
