//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
package qtrhi

/*

#include "gen_qsgnode.h"
#include <stdlib.h>

*/
import "C"

import (
	"runtime"
	"unsafe"
)

type QSGNode__NodeType int

const (
	QSGNode__BasicNodeType     QSGNode__NodeType = 0
	QSGNode__GeometryNodeType  QSGNode__NodeType = 1
	QSGNode__TransformNodeType QSGNode__NodeType = 2
	QSGNode__ClipNodeType      QSGNode__NodeType = 3
	QSGNode__OpacityNodeType   QSGNode__NodeType = 4
	QSGNode__RootNodeType      QSGNode__NodeType = 5
	QSGNode__RenderNodeType    QSGNode__NodeType = 6
)

type QSGNode__Flag int

const (
	QSGNode__OwnedByParent      QSGNode__Flag = 1
	QSGNode__UsePreprocess      QSGNode__Flag = 2
	QSGNode__OwnsGeometry       QSGNode__Flag = 65536
	QSGNode__OwnsMaterial       QSGNode__Flag = 131072
	QSGNode__OwnsOpaqueMaterial QSGNode__Flag = 262144
	QSGNode__IsVisitableNode    QSGNode__Flag = 16777216
)

type QSGNode__DirtyStateBit int

const (
	QSGNode__DirtySubtreeBlocked  QSGNode__DirtyStateBit = 128
	QSGNode__DirtyMatrix          QSGNode__DirtyStateBit = 256
	QSGNode__DirtyNodeAdded       QSGNode__DirtyStateBit = 1024
	QSGNode__DirtyNodeRemoved     QSGNode__DirtyStateBit = 2048
	QSGNode__DirtyGeometry        QSGNode__DirtyStateBit = 4096
	QSGNode__DirtyMaterial        QSGNode__DirtyStateBit = 8192
	QSGNode__DirtyOpacity         QSGNode__DirtyStateBit = 16384
	QSGNode__DirtyForceUpdate     QSGNode__DirtyStateBit = 32768
	QSGNode__DirtyUsePreprocess   QSGNode__DirtyStateBit = 2
	QSGNode__DirtyPropagationMask QSGNode__DirtyStateBit = 50432
)

type QSGNode struct {
	h *C.QSGNode
}

func (this *QSGNode) cPointer() *C.QSGNode {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGNode) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGNode constructs the type using only CGO pointers.
func newQSGNode(h *C.QSGNode) *QSGNode {
	if h == nil {
		return nil
	}

	return &QSGNode{h: h}
}

// UnsafeNewQSGNode constructs the type using only unsafe pointers.
func UnsafeNewQSGNode(h unsafe.Pointer) *QSGNode {
	return newQSGNode((*C.QSGNode)(h))
}

// NewQSGNode constructs a new QSGNode object.
func NewQSGNode() *QSGNode {

	return newQSGNode(C.qtrhi_QSGNode_new())
}

// Delete this object from C++ memory.
func (this *QSGNode) Delete() {
	C.qtrhi_QSGNode_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QSGNode) GoGC() {
	runtime.SetFinalizer(this, func(this *QSGNode) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}
