//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
package qtrhi

/*

#include "gen_qshader.h"
#include <stdlib.h>

*/
import "C"

import (
	"runtime"
	"unsafe"
)

type QShaderVersion__Flag int

const (
	QShaderVersion__GlslEs QShaderVersion__Flag = 1
)

type QShader__Stage int

const (
	QShader__VertexStage                 QShader__Stage = 0
	QShader__TessellationControlStage    QShader__Stage = 1
	QShader__TessellationEvaluationStage QShader__Stage = 2
	QShader__GeometryStage               QShader__Stage = 3
	QShader__FragmentStage               QShader__Stage = 4
	QShader__ComputeStage                QShader__Stage = 5
)

type QShader__Source int

const (
	QShader__SpirvShader    QShader__Source = 0
	QShader__GlslShader     QShader__Source = 1
	QShader__HlslShader     QShader__Source = 2
	QShader__DxbcShader     QShader__Source = 3
	QShader__MslShader      QShader__Source = 4
	QShader__DxilShader     QShader__Source = 5
	QShader__MetalLibShader QShader__Source = 6
	QShader__WgslShader     QShader__Source = 7
)

type QShader__Variant int

const (
	QShader__StandardShader                     QShader__Variant = 0
	QShader__BatchableVertexShader              QShader__Variant = 1
	QShader__UInt16IndexedVertexAsComputeShader QShader__Variant = 2
	QShader__UInt32IndexedVertexAsComputeShader QShader__Variant = 3
	QShader__NonIndexedVertexAsComputeShader    QShader__Variant = 4
	QShader__HdrCapableFragmentShader           QShader__Variant = 5
)

type QShader__SerializedFormatVersion int

const (
	QShader__Latest QShader__SerializedFormatVersion = 0
	QShader__Qt_6_5 QShader__SerializedFormatVersion = 1
	QShader__Qt_6_4 QShader__SerializedFormatVersion = 2
)

type QShader struct {
	h *C.QShader
}

func (this *QShader) cPointer() *C.QShader {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QShader) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQShader constructs the type using only CGO pointers.
func newQShader(h *C.QShader) *QShader {
	if h == nil {
		return nil
	}

	return &QShader{h: h}
}

// UnsafeNewQShader constructs the type using only unsafe pointers.
func UnsafeNewQShader(h unsafe.Pointer) *QShader {
	return newQShader((*C.QShader)(h))
}

// NewQShader constructs a new QShader object.
func NewQShader() *QShader {

	return newQShader(C.qtrhi_QShader_new())
}

// NewQShader2 constructs a new QShader object.
func NewQShader2(other *QShader) *QShader {

	return newQShader(C.qtrhi_QShader_new2(other.cPointer()))
}

func (this *QShader) IsValid() bool {
	return (bool)(C.qtrhi_QShader_isValid(this.h))
}

func QShader_FromSerialized(data []byte) *QShader {
	data_alias := C.struct_miqt_string{}
	if len(data) > 0 {
		data_alias.data = (*C.char)(unsafe.Pointer(&data[0]))
	} else {
		data_alias.data = (*C.char)(unsafe.Pointer(nil))
	}
	data_alias.len = C.size_t(len(data))
	_goptr := newQShader(C.qtrhi_QShader_fromSerialized(data_alias))
	return _goptr
}

// Delete this object from C++ memory.
func (this *QShader) Delete() {
	C.qtrhi_QShader_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QShader) GoGC() {
	runtime.SetFinalizer(this, func(this *QShader) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}
