//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
package qtrhi

/*

#include "gen_qlibrary.h"
#include <stdlib.h>

*/
import "C"

import (
	"github.com/mappu/miqt/qt6"
	"unsafe"
)

type QLibrary__LoadHint int

const (
	QLibrary__ResolveAllSymbolsHint     QLibrary__LoadHint = 1
	QLibrary__ExportExternalSymbolsHint QLibrary__LoadHint = 2
	QLibrary__LoadArchiveMemberHint     QLibrary__LoadHint = 4
	QLibrary__PreventUnloadHint         QLibrary__LoadHint = 8
	QLibrary__DeepBindHint              QLibrary__LoadHint = 16
)

type QLibrary struct {
	h *C.QLibrary
	*qt6.QObject
}

func (this *QLibrary) cPointer() *C.QLibrary {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QLibrary) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQLibrary constructs the type using only CGO pointers.
func newQLibrary(h *C.QLibrary) *QLibrary {
	if h == nil {
		return nil
	}
	var outptr_QObject *C.QObject = nil
	C.qtrhi_QLibrary_virtbase(h, &outptr_QObject)

	return &QLibrary{h: h,
		QObject: qt6.UnsafeNewQObject(unsafe.Pointer(outptr_QObject))}
}

// UnsafeNewQLibrary constructs the type using only unsafe pointers.
func UnsafeNewQLibrary(h unsafe.Pointer) *QLibrary {
	return newQLibrary((*C.QLibrary)(h))
}

// LibraryHasSymbol checks an exported symbol in the named runtime library.
func LibraryHasSymbol(fileName string, verNum int, symbol string) bool {
	fileName_ms := C.struct_miqt_string{}
	fileName_ms.data = C.CString(fileName)
	fileName_ms.len = C.size_t(len(fileName))
	defer C.free(unsafe.Pointer(fileName_ms.data))
	symbol_Cstring := C.CString(symbol)
	defer C.free(unsafe.Pointer(symbol_Cstring))
	return (bool)(C.qtrhi_QLibrary_resolve(fileName_ms, (C.int)(verNum), symbol_Cstring))
}
