//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
#include <QImage>
#include <QQuickGraphicsConfiguration>
#include <QQuickWindow>
#include <rhi/qrhi.h>
#include <QWindow>
#include <qquickwindow.h>
#include "gen_qquickwindow.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern C */
#endif

extern "C" void qtrhi_native_destroyed(void*);
extern "C" void qtrhi_callback_released(intptr_t);
void qtrhi_QQuickWindow_virtbase(QQuickWindow* src, QWindow** outptr_QWindow) {
	*outptr_QWindow = static_cast<QWindow*>(src);
}

QImage* qtrhi_QQuickWindow_grabWindow(QQuickWindow* self) {
	return new QImage(self->grabWindow());
}

double qtrhi_QQuickWindow_effectiveDevicePixelRatio(const QQuickWindow* self) {
	return self->effectiveDevicePixelRatio();
}

void qtrhi_QQuickWindow_setGraphicsConfiguration(QQuickWindow* self, QQuickGraphicsConfiguration* config) {
	self->setGraphicsConfiguration(*config);
}

QRhi* qtrhi_QQuickWindow_rhi(const QQuickWindow* self) {
	return self->rhi();
}
