//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
#include <QLibrary>
#include <QObject>
#include <QString>
#include <QByteArray>
#include <cstring>
#include <qlibrary.h>
#include "gen_qlibrary.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern C */
#endif

extern "C" void qtrhi_native_destroyed(void*);
extern "C" void qtrhi_callback_released(intptr_t);
void qtrhi_QLibrary_virtbase(QLibrary* src, QObject** outptr_QObject) {
	*outptr_QObject = static_cast<QObject*>(src);
}

bool qtrhi_QLibrary_resolve(struct miqt_string fileName, int verNum, const char* symbol) {
	QString fileName_QString = QString::fromUtf8(fileName.data, fileName.len);
	return QLibrary::resolve(fileName_QString, static_cast<int>(verNum), symbol);
}
