//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
package qtrhi

/*

#include "gen_qrhi.h"
#include <stdlib.h>

*/
import "C"

import (
	"github.com/mappu/miqt/qt6"
	"runtime"
	"unsafe"
)

type QRhiVertexInputBinding__Classification int

const (
	QRhiVertexInputBinding__PerVertex   QRhiVertexInputBinding__Classification = 0
	QRhiVertexInputBinding__PerInstance QRhiVertexInputBinding__Classification = 1
)

type QRhiVertexInputAttribute__Format int

const (
	QRhiVertexInputAttribute__Float4     QRhiVertexInputAttribute__Format = 0
	QRhiVertexInputAttribute__Float3     QRhiVertexInputAttribute__Format = 1
	QRhiVertexInputAttribute__Float2     QRhiVertexInputAttribute__Format = 2
	QRhiVertexInputAttribute__Float      QRhiVertexInputAttribute__Format = 3
	QRhiVertexInputAttribute__UNormByte4 QRhiVertexInputAttribute__Format = 4
	QRhiVertexInputAttribute__UNormByte2 QRhiVertexInputAttribute__Format = 5
	QRhiVertexInputAttribute__UNormByte  QRhiVertexInputAttribute__Format = 6
	QRhiVertexInputAttribute__UInt4      QRhiVertexInputAttribute__Format = 7
	QRhiVertexInputAttribute__UInt3      QRhiVertexInputAttribute__Format = 8
	QRhiVertexInputAttribute__UInt2      QRhiVertexInputAttribute__Format = 9
	QRhiVertexInputAttribute__UInt       QRhiVertexInputAttribute__Format = 10
	QRhiVertexInputAttribute__SInt4      QRhiVertexInputAttribute__Format = 11
	QRhiVertexInputAttribute__SInt3      QRhiVertexInputAttribute__Format = 12
	QRhiVertexInputAttribute__SInt2      QRhiVertexInputAttribute__Format = 13
	QRhiVertexInputAttribute__SInt       QRhiVertexInputAttribute__Format = 14
	QRhiVertexInputAttribute__Half4      QRhiVertexInputAttribute__Format = 15
	QRhiVertexInputAttribute__Half3      QRhiVertexInputAttribute__Format = 16
	QRhiVertexInputAttribute__Half2      QRhiVertexInputAttribute__Format = 17
	QRhiVertexInputAttribute__Half       QRhiVertexInputAttribute__Format = 18
	QRhiVertexInputAttribute__UShort4    QRhiVertexInputAttribute__Format = 19
	QRhiVertexInputAttribute__UShort3    QRhiVertexInputAttribute__Format = 20
	QRhiVertexInputAttribute__UShort2    QRhiVertexInputAttribute__Format = 21
	QRhiVertexInputAttribute__UShort     QRhiVertexInputAttribute__Format = 22
	QRhiVertexInputAttribute__SShort4    QRhiVertexInputAttribute__Format = 23
	QRhiVertexInputAttribute__SShort3    QRhiVertexInputAttribute__Format = 24
	QRhiVertexInputAttribute__SShort2    QRhiVertexInputAttribute__Format = 25
	QRhiVertexInputAttribute__SShort     QRhiVertexInputAttribute__Format = 26
)

type QRhiShaderStage__Type int

const (
	QRhiShaderStage__Vertex                 QRhiShaderStage__Type = 0
	QRhiShaderStage__TessellationControl    QRhiShaderStage__Type = 1
	QRhiShaderStage__TessellationEvaluation QRhiShaderStage__Type = 2
	QRhiShaderStage__Geometry               QRhiShaderStage__Type = 3
	QRhiShaderStage__Fragment               QRhiShaderStage__Type = 4
	QRhiShaderStage__Compute                QRhiShaderStage__Type = 5
)

type QRhiShaderResourceBinding__Type int

const (
	QRhiShaderResourceBinding__UniformBuffer   QRhiShaderResourceBinding__Type = 0
	QRhiShaderResourceBinding__SampledTexture  QRhiShaderResourceBinding__Type = 1
	QRhiShaderResourceBinding__Texture         QRhiShaderResourceBinding__Type = 2
	QRhiShaderResourceBinding__Sampler         QRhiShaderResourceBinding__Type = 3
	QRhiShaderResourceBinding__ImageLoad       QRhiShaderResourceBinding__Type = 4
	QRhiShaderResourceBinding__ImageStore      QRhiShaderResourceBinding__Type = 5
	QRhiShaderResourceBinding__ImageLoadStore  QRhiShaderResourceBinding__Type = 6
	QRhiShaderResourceBinding__BufferLoad      QRhiShaderResourceBinding__Type = 7
	QRhiShaderResourceBinding__BufferStore     QRhiShaderResourceBinding__Type = 8
	QRhiShaderResourceBinding__BufferLoadStore QRhiShaderResourceBinding__Type = 9
)

type QRhiShaderResourceBinding__StageFlag int

const (
	QRhiShaderResourceBinding__VertexStage                 QRhiShaderResourceBinding__StageFlag = 1
	QRhiShaderResourceBinding__TessellationControlStage    QRhiShaderResourceBinding__StageFlag = 2
	QRhiShaderResourceBinding__TessellationEvaluationStage QRhiShaderResourceBinding__StageFlag = 4
	QRhiShaderResourceBinding__GeometryStage               QRhiShaderResourceBinding__StageFlag = 8
	QRhiShaderResourceBinding__FragmentStage               QRhiShaderResourceBinding__StageFlag = 16
	QRhiShaderResourceBinding__ComputeStage                QRhiShaderResourceBinding__StageFlag = 32
)

type QRhiResource__Type int

const (
	QRhiResource__Buffer                 QRhiResource__Type = 0
	QRhiResource__Texture                QRhiResource__Type = 1
	QRhiResource__Sampler                QRhiResource__Type = 2
	QRhiResource__RenderBuffer           QRhiResource__Type = 3
	QRhiResource__RenderPassDescriptor   QRhiResource__Type = 4
	QRhiResource__SwapChainRenderTarget  QRhiResource__Type = 5
	QRhiResource__TextureRenderTarget    QRhiResource__Type = 6
	QRhiResource__ShaderResourceBindings QRhiResource__Type = 7
	QRhiResource__GraphicsPipeline       QRhiResource__Type = 8
	QRhiResource__SwapChain              QRhiResource__Type = 9
	QRhiResource__ComputePipeline        QRhiResource__Type = 10
	QRhiResource__CommandBuffer          QRhiResource__Type = 11
	QRhiResource__ShadingRateMap         QRhiResource__Type = 12
)

type QRhiBuffer__Type int

const (
	QRhiBuffer__Immutable QRhiBuffer__Type = 0
	QRhiBuffer__Static    QRhiBuffer__Type = 1
	QRhiBuffer__Dynamic   QRhiBuffer__Type = 2
)

type QRhiBuffer__UsageFlag int

const (
	QRhiBuffer__VertexBuffer  QRhiBuffer__UsageFlag = 1
	QRhiBuffer__IndexBuffer   QRhiBuffer__UsageFlag = 2
	QRhiBuffer__UniformBuffer QRhiBuffer__UsageFlag = 4
	QRhiBuffer__StorageBuffer QRhiBuffer__UsageFlag = 8
)

type QRhiTexture__Flag int

const (
	QRhiTexture__RenderTarget          QRhiTexture__Flag = 1
	QRhiTexture__CubeMap               QRhiTexture__Flag = 4
	QRhiTexture__MipMapped             QRhiTexture__Flag = 8
	QRhiTexture__sRGB                  QRhiTexture__Flag = 16
	QRhiTexture__UsedAsTransferSource  QRhiTexture__Flag = 32
	QRhiTexture__UsedWithGenerateMips  QRhiTexture__Flag = 64
	QRhiTexture__UsedWithLoadStore     QRhiTexture__Flag = 128
	QRhiTexture__UsedAsCompressedAtlas QRhiTexture__Flag = 256
	QRhiTexture__ExternalOES           QRhiTexture__Flag = 512
	QRhiTexture__ThreeDimensional      QRhiTexture__Flag = 1024
	QRhiTexture__TextureRectangleGL    QRhiTexture__Flag = 2048
	QRhiTexture__TextureArray          QRhiTexture__Flag = 4096
	QRhiTexture__OneDimensional        QRhiTexture__Flag = 8192
	QRhiTexture__UsedAsShadingRateMap  QRhiTexture__Flag = 16384
)

type QRhiTexture__Format int

const (
	QRhiTexture__UnknownFormat QRhiTexture__Format = 0
	QRhiTexture__RGBA8         QRhiTexture__Format = 1
	QRhiTexture__BGRA8         QRhiTexture__Format = 2
	QRhiTexture__R8            QRhiTexture__Format = 3
	QRhiTexture__RG8           QRhiTexture__Format = 4
	QRhiTexture__R16           QRhiTexture__Format = 5
	QRhiTexture__RG16          QRhiTexture__Format = 6
	QRhiTexture__RED_OR_ALPHA8 QRhiTexture__Format = 7
	QRhiTexture__RGBA16F       QRhiTexture__Format = 8
	QRhiTexture__RGBA32F       QRhiTexture__Format = 9
	QRhiTexture__R16F          QRhiTexture__Format = 10
	QRhiTexture__R32F          QRhiTexture__Format = 11
	QRhiTexture__RGB10A2       QRhiTexture__Format = 12
	QRhiTexture__R8SI          QRhiTexture__Format = 13
	QRhiTexture__R32SI         QRhiTexture__Format = 14
	QRhiTexture__RG32SI        QRhiTexture__Format = 15
	QRhiTexture__RGBA32SI      QRhiTexture__Format = 16
	QRhiTexture__R8UI          QRhiTexture__Format = 17
	QRhiTexture__R32UI         QRhiTexture__Format = 18
	QRhiTexture__RG32UI        QRhiTexture__Format = 19
	QRhiTexture__RGBA32UI      QRhiTexture__Format = 20
	QRhiTexture__D16           QRhiTexture__Format = 21
	QRhiTexture__D24           QRhiTexture__Format = 22
	QRhiTexture__D24S8         QRhiTexture__Format = 23
	QRhiTexture__D32F          QRhiTexture__Format = 24
	QRhiTexture__D32FS8        QRhiTexture__Format = 25
	QRhiTexture__BC1           QRhiTexture__Format = 26
	QRhiTexture__BC2           QRhiTexture__Format = 27
	QRhiTexture__BC3           QRhiTexture__Format = 28
	QRhiTexture__BC4           QRhiTexture__Format = 29
	QRhiTexture__BC5           QRhiTexture__Format = 30
	QRhiTexture__BC6H          QRhiTexture__Format = 31
	QRhiTexture__BC7           QRhiTexture__Format = 32
	QRhiTexture__ETC2_RGB8     QRhiTexture__Format = 33
	QRhiTexture__ETC2_RGB8A1   QRhiTexture__Format = 34
	QRhiTexture__ETC2_RGBA8    QRhiTexture__Format = 35
	QRhiTexture__ASTC_4x4      QRhiTexture__Format = 36
	QRhiTexture__ASTC_5x4      QRhiTexture__Format = 37
	QRhiTexture__ASTC_5x5      QRhiTexture__Format = 38
	QRhiTexture__ASTC_6x5      QRhiTexture__Format = 39
	QRhiTexture__ASTC_6x6      QRhiTexture__Format = 40
	QRhiTexture__ASTC_8x5      QRhiTexture__Format = 41
	QRhiTexture__ASTC_8x6      QRhiTexture__Format = 42
	QRhiTexture__ASTC_8x8      QRhiTexture__Format = 43
	QRhiTexture__ASTC_10x5     QRhiTexture__Format = 44
	QRhiTexture__ASTC_10x6     QRhiTexture__Format = 45
	QRhiTexture__ASTC_10x8     QRhiTexture__Format = 46
	QRhiTexture__ASTC_10x10    QRhiTexture__Format = 47
	QRhiTexture__ASTC_12x10    QRhiTexture__Format = 48
	QRhiTexture__ASTC_12x12    QRhiTexture__Format = 49
)

type QRhiSampler__Filter int

const (
	QRhiSampler__None    QRhiSampler__Filter = 0
	QRhiSampler__Nearest QRhiSampler__Filter = 1
	QRhiSampler__Linear  QRhiSampler__Filter = 2
)

type QRhiSampler__AddressMode int

const (
	QRhiSampler__Repeat      QRhiSampler__AddressMode = 0
	QRhiSampler__ClampToEdge QRhiSampler__AddressMode = 1
	QRhiSampler__Mirror      QRhiSampler__AddressMode = 2
)

type QRhiSampler__CompareOp int

const (
	QRhiSampler__Never          QRhiSampler__CompareOp = 0
	QRhiSampler__Less           QRhiSampler__CompareOp = 1
	QRhiSampler__Equal          QRhiSampler__CompareOp = 2
	QRhiSampler__LessOrEqual    QRhiSampler__CompareOp = 3
	QRhiSampler__Greater        QRhiSampler__CompareOp = 4
	QRhiSampler__NotEqual       QRhiSampler__CompareOp = 5
	QRhiSampler__GreaterOrEqual QRhiSampler__CompareOp = 6
	QRhiSampler__Always         QRhiSampler__CompareOp = 7
)

type QRhiRenderBuffer__Type int

const (
	QRhiRenderBuffer__DepthStencil QRhiRenderBuffer__Type = 0
	QRhiRenderBuffer__Color        QRhiRenderBuffer__Type = 1
)

type QRhiRenderBuffer__Flag int

const (
	QRhiRenderBuffer__UsedWithSwapChainOnly QRhiRenderBuffer__Flag = 1
)

type QRhiTextureRenderTarget__Flag int

const (
	QRhiTextureRenderTarget__PreserveColorContents          QRhiTextureRenderTarget__Flag = 1
	QRhiTextureRenderTarget__PreserveDepthStencilContents   QRhiTextureRenderTarget__Flag = 2
	QRhiTextureRenderTarget__DoNotStoreDepthStencilContents QRhiTextureRenderTarget__Flag = 4
)

type QRhiShaderResourceBindings__UpdateFlag int

const (
	QRhiShaderResourceBindings__BindingsAreSorted QRhiShaderResourceBindings__UpdateFlag = 1
)

type QRhiGraphicsPipeline__Flag int

const (
	QRhiGraphicsPipeline__UsesBlendConstants          QRhiGraphicsPipeline__Flag = 1
	QRhiGraphicsPipeline__UsesStencilRef              QRhiGraphicsPipeline__Flag = 2
	QRhiGraphicsPipeline__UsesScissor                 QRhiGraphicsPipeline__Flag = 4
	QRhiGraphicsPipeline__CompileShadersWithDebugInfo QRhiGraphicsPipeline__Flag = 8
	QRhiGraphicsPipeline__UsesShadingRate             QRhiGraphicsPipeline__Flag = 16
)

type QRhiGraphicsPipeline__Topology int

const (
	QRhiGraphicsPipeline__Triangles     QRhiGraphicsPipeline__Topology = 0
	QRhiGraphicsPipeline__TriangleStrip QRhiGraphicsPipeline__Topology = 1
	QRhiGraphicsPipeline__TriangleFan   QRhiGraphicsPipeline__Topology = 2
	QRhiGraphicsPipeline__Lines         QRhiGraphicsPipeline__Topology = 3
	QRhiGraphicsPipeline__LineStrip     QRhiGraphicsPipeline__Topology = 4
	QRhiGraphicsPipeline__Points        QRhiGraphicsPipeline__Topology = 5
	QRhiGraphicsPipeline__Patches       QRhiGraphicsPipeline__Topology = 6
)

type QRhiGraphicsPipeline__CullMode int

const (
	QRhiGraphicsPipeline__None  QRhiGraphicsPipeline__CullMode = 0
	QRhiGraphicsPipeline__Front QRhiGraphicsPipeline__CullMode = 1
	QRhiGraphicsPipeline__Back  QRhiGraphicsPipeline__CullMode = 2
)

type QRhiGraphicsPipeline__FrontFace int

const (
	QRhiGraphicsPipeline__CCW QRhiGraphicsPipeline__FrontFace = 0
	QRhiGraphicsPipeline__CW  QRhiGraphicsPipeline__FrontFace = 1
)

type QRhiGraphicsPipeline__ColorMaskComponent int

const (
	QRhiGraphicsPipeline__R QRhiGraphicsPipeline__ColorMaskComponent = 1
	QRhiGraphicsPipeline__G QRhiGraphicsPipeline__ColorMaskComponent = 2
	QRhiGraphicsPipeline__B QRhiGraphicsPipeline__ColorMaskComponent = 4
	QRhiGraphicsPipeline__A QRhiGraphicsPipeline__ColorMaskComponent = 8
)

type QRhiGraphicsPipeline__BlendFactor int

const (
	QRhiGraphicsPipeline__Zero                  QRhiGraphicsPipeline__BlendFactor = 0
	QRhiGraphicsPipeline__One                   QRhiGraphicsPipeline__BlendFactor = 1
	QRhiGraphicsPipeline__SrcColor              QRhiGraphicsPipeline__BlendFactor = 2
	QRhiGraphicsPipeline__OneMinusSrcColor      QRhiGraphicsPipeline__BlendFactor = 3
	QRhiGraphicsPipeline__DstColor              QRhiGraphicsPipeline__BlendFactor = 4
	QRhiGraphicsPipeline__OneMinusDstColor      QRhiGraphicsPipeline__BlendFactor = 5
	QRhiGraphicsPipeline__SrcAlpha              QRhiGraphicsPipeline__BlendFactor = 6
	QRhiGraphicsPipeline__OneMinusSrcAlpha      QRhiGraphicsPipeline__BlendFactor = 7
	QRhiGraphicsPipeline__DstAlpha              QRhiGraphicsPipeline__BlendFactor = 8
	QRhiGraphicsPipeline__OneMinusDstAlpha      QRhiGraphicsPipeline__BlendFactor = 9
	QRhiGraphicsPipeline__ConstantColor         QRhiGraphicsPipeline__BlendFactor = 10
	QRhiGraphicsPipeline__OneMinusConstantColor QRhiGraphicsPipeline__BlendFactor = 11
	QRhiGraphicsPipeline__ConstantAlpha         QRhiGraphicsPipeline__BlendFactor = 12
	QRhiGraphicsPipeline__OneMinusConstantAlpha QRhiGraphicsPipeline__BlendFactor = 13
	QRhiGraphicsPipeline__SrcAlphaSaturate      QRhiGraphicsPipeline__BlendFactor = 14
	QRhiGraphicsPipeline__Src1Color             QRhiGraphicsPipeline__BlendFactor = 15
	QRhiGraphicsPipeline__OneMinusSrc1Color     QRhiGraphicsPipeline__BlendFactor = 16
	QRhiGraphicsPipeline__Src1Alpha             QRhiGraphicsPipeline__BlendFactor = 17
	QRhiGraphicsPipeline__OneMinusSrc1Alpha     QRhiGraphicsPipeline__BlendFactor = 18
)

type QRhiGraphicsPipeline__BlendOp int

const (
	QRhiGraphicsPipeline__Add             QRhiGraphicsPipeline__BlendOp = 0
	QRhiGraphicsPipeline__Subtract        QRhiGraphicsPipeline__BlendOp = 1
	QRhiGraphicsPipeline__ReverseSubtract QRhiGraphicsPipeline__BlendOp = 2
	QRhiGraphicsPipeline__Min             QRhiGraphicsPipeline__BlendOp = 3
	QRhiGraphicsPipeline__Max             QRhiGraphicsPipeline__BlendOp = 4
)

type QRhiGraphicsPipeline__CompareOp int

const (
	QRhiGraphicsPipeline__Never          QRhiGraphicsPipeline__CompareOp = 0
	QRhiGraphicsPipeline__Less           QRhiGraphicsPipeline__CompareOp = 1
	QRhiGraphicsPipeline__Equal          QRhiGraphicsPipeline__CompareOp = 2
	QRhiGraphicsPipeline__LessOrEqual    QRhiGraphicsPipeline__CompareOp = 3
	QRhiGraphicsPipeline__Greater        QRhiGraphicsPipeline__CompareOp = 4
	QRhiGraphicsPipeline__NotEqual       QRhiGraphicsPipeline__CompareOp = 5
	QRhiGraphicsPipeline__GreaterOrEqual QRhiGraphicsPipeline__CompareOp = 6
	QRhiGraphicsPipeline__Always         QRhiGraphicsPipeline__CompareOp = 7
)

type QRhiGraphicsPipeline__StencilOp int

const (
	QRhiGraphicsPipeline__StencilZero       QRhiGraphicsPipeline__StencilOp = 0
	QRhiGraphicsPipeline__Keep              QRhiGraphicsPipeline__StencilOp = 1
	QRhiGraphicsPipeline__Replace           QRhiGraphicsPipeline__StencilOp = 2
	QRhiGraphicsPipeline__IncrementAndClamp QRhiGraphicsPipeline__StencilOp = 3
	QRhiGraphicsPipeline__DecrementAndClamp QRhiGraphicsPipeline__StencilOp = 4
	QRhiGraphicsPipeline__Invert            QRhiGraphicsPipeline__StencilOp = 5
	QRhiGraphicsPipeline__IncrementAndWrap  QRhiGraphicsPipeline__StencilOp = 6
	QRhiGraphicsPipeline__DecrementAndWrap  QRhiGraphicsPipeline__StencilOp = 7
)

type QRhiGraphicsPipeline__PolygonMode int

const (
	QRhiGraphicsPipeline__Fill QRhiGraphicsPipeline__PolygonMode = 0
	QRhiGraphicsPipeline__Line QRhiGraphicsPipeline__PolygonMode = 1
)

type QRhiSwapChainHdrInfo__LimitsType int

const (
	QRhiSwapChainHdrInfo__LuminanceInNits     QRhiSwapChainHdrInfo__LimitsType = 0
	QRhiSwapChainHdrInfo__ColorComponentValue QRhiSwapChainHdrInfo__LimitsType = 1
)

type QRhiSwapChainHdrInfo__LuminanceBehavior int

const (
	QRhiSwapChainHdrInfo__SceneReferred   QRhiSwapChainHdrInfo__LuminanceBehavior = 0
	QRhiSwapChainHdrInfo__DisplayReferred QRhiSwapChainHdrInfo__LuminanceBehavior = 1
)

type QRhiSwapChain__Flag int

const (
	QRhiSwapChain__SurfaceHasPreMulAlpha    QRhiSwapChain__Flag = 1
	QRhiSwapChain__SurfaceHasNonPreMulAlpha QRhiSwapChain__Flag = 2
	QRhiSwapChain__sRGB                     QRhiSwapChain__Flag = 4
	QRhiSwapChain__UsedAsTransferSource     QRhiSwapChain__Flag = 8
	QRhiSwapChain__NoVSync                  QRhiSwapChain__Flag = 16
	QRhiSwapChain__MinimalBufferCount       QRhiSwapChain__Flag = 32
)

type QRhiSwapChain__Format int

const (
	QRhiSwapChain__SDR                        QRhiSwapChain__Format = 0
	QRhiSwapChain__HDRExtendedSrgbLinear      QRhiSwapChain__Format = 1
	QRhiSwapChain__HDR10                      QRhiSwapChain__Format = 2
	QRhiSwapChain__HDRExtendedDisplayP3Linear QRhiSwapChain__Format = 3
)

type QRhiSwapChain__StereoTargetBuffer int

const (
	QRhiSwapChain__LeftBuffer  QRhiSwapChain__StereoTargetBuffer = 0
	QRhiSwapChain__RightBuffer QRhiSwapChain__StereoTargetBuffer = 1
)

type QRhiComputePipeline__Flag int

const (
	QRhiComputePipeline__CompileShadersWithDebugInfo QRhiComputePipeline__Flag = 1
)

type QRhiCommandBuffer__IndexFormat int

const (
	QRhiCommandBuffer__IndexUInt16 QRhiCommandBuffer__IndexFormat = 0
	QRhiCommandBuffer__IndexUInt32 QRhiCommandBuffer__IndexFormat = 1
)

type QRhiCommandBuffer__BeginPassFlag int

const (
	QRhiCommandBuffer__ExternalContent               QRhiCommandBuffer__BeginPassFlag = 1
	QRhiCommandBuffer__DoNotTrackResourcesForCompute QRhiCommandBuffer__BeginPassFlag = 2
)

type QRhiDriverInfo__DeviceType int

const (
	QRhiDriverInfo__UnknownDevice    QRhiDriverInfo__DeviceType = 0
	QRhiDriverInfo__IntegratedDevice QRhiDriverInfo__DeviceType = 1
	QRhiDriverInfo__DiscreteDevice   QRhiDriverInfo__DeviceType = 2
	QRhiDriverInfo__ExternalDevice   QRhiDriverInfo__DeviceType = 3
	QRhiDriverInfo__VirtualDevice    QRhiDriverInfo__DeviceType = 4
	QRhiDriverInfo__CpuDevice        QRhiDriverInfo__DeviceType = 5
)

type QRhi__Implementation int

const (
	QRhi__Null      QRhi__Implementation = 0
	QRhi__Vulkan    QRhi__Implementation = 1
	QRhi__OpenGLES2 QRhi__Implementation = 2
	QRhi__D3D11     QRhi__Implementation = 3
	QRhi__Metal     QRhi__Implementation = 4
	QRhi__D3D12     QRhi__Implementation = 5
)

type QRhi__Flag int

const (
	QRhi__EnableDebugMarkers          QRhi__Flag = 1
	QRhi__PreferSoftwareRenderer      QRhi__Flag = 2
	QRhi__EnablePipelineCacheDataSave QRhi__Flag = 4
	QRhi__EnableTimestamps            QRhi__Flag = 8
	QRhi__SuppressSmokeTestWarnings   QRhi__Flag = 16
)

type QRhi__FrameOpResult int

const (
	QRhi__FrameOpSuccess            QRhi__FrameOpResult = 0
	QRhi__FrameOpError              QRhi__FrameOpResult = 1
	QRhi__FrameOpSwapChainOutOfDate QRhi__FrameOpResult = 2
	QRhi__FrameOpDeviceLost         QRhi__FrameOpResult = 3
)

type QRhi__Feature int

const (
	QRhi__MultisampleTexture                       QRhi__Feature = 1
	QRhi__MultisampleRenderBuffer                  QRhi__Feature = 2
	QRhi__DebugMarkers                             QRhi__Feature = 3
	QRhi__Timestamps                               QRhi__Feature = 4
	QRhi__Instancing                               QRhi__Feature = 5
	QRhi__CustomInstanceStepRate                   QRhi__Feature = 6
	QRhi__PrimitiveRestart                         QRhi__Feature = 7
	QRhi__NonDynamicUniformBuffers                 QRhi__Feature = 8
	QRhi__NonFourAlignedEffectiveIndexBufferOffset QRhi__Feature = 9
	QRhi__NPOTTextureRepeat                        QRhi__Feature = 10
	QRhi__RedOrAlpha8IsRed                         QRhi__Feature = 11
	QRhi__ElementIndexUint                         QRhi__Feature = 12
	QRhi__Compute                                  QRhi__Feature = 13
	QRhi__WideLines                                QRhi__Feature = 14
	QRhi__VertexShaderPointSize                    QRhi__Feature = 15
	QRhi__BaseVertex                               QRhi__Feature = 16
	QRhi__BaseInstance                             QRhi__Feature = 17
	QRhi__TriangleFanTopology                      QRhi__Feature = 18
	QRhi__ReadBackNonUniformBuffer                 QRhi__Feature = 19
	QRhi__ReadBackNonBaseMipLevel                  QRhi__Feature = 20
	QRhi__TexelFetch                               QRhi__Feature = 21
	QRhi__RenderToNonBaseMipLevel                  QRhi__Feature = 22
	QRhi__IntAttributes                            QRhi__Feature = 23
	QRhi__ScreenSpaceDerivatives                   QRhi__Feature = 24
	QRhi__ReadBackAnyTextureFormat                 QRhi__Feature = 25
	QRhi__PipelineCacheDataLoadSave                QRhi__Feature = 26
	QRhi__ImageDataStride                          QRhi__Feature = 27
	QRhi__RenderBufferImport                       QRhi__Feature = 28
	QRhi__ThreeDimensionalTextures                 QRhi__Feature = 29
	QRhi__RenderTo3DTextureSlice                   QRhi__Feature = 30
	QRhi__TextureArrays                            QRhi__Feature = 31
	QRhi__Tessellation                             QRhi__Feature = 32
	QRhi__GeometryShader                           QRhi__Feature = 33
	QRhi__TextureArrayRange                        QRhi__Feature = 34
	QRhi__NonFillPolygonMode                       QRhi__Feature = 35
	QRhi__OneDimensionalTextures                   QRhi__Feature = 36
	QRhi__OneDimensionalTextureMipmaps             QRhi__Feature = 37
	QRhi__HalfAttributes                           QRhi__Feature = 38
	QRhi__RenderToOneDimensionalTexture            QRhi__Feature = 39
	QRhi__ThreeDimensionalTextureMipmaps           QRhi__Feature = 40
	QRhi__MultiView                                QRhi__Feature = 41
	QRhi__TextureViewFormat                        QRhi__Feature = 42
	QRhi__ResolveDepthStencil                      QRhi__Feature = 43
	QRhi__VariableRateShading                      QRhi__Feature = 44
	QRhi__VariableRateShadingMap                   QRhi__Feature = 45
	QRhi__VariableRateShadingMapWithTexture        QRhi__Feature = 46
	QRhi__PerRenderTargetBlending                  QRhi__Feature = 47
	QRhi__SampleVariables                          QRhi__Feature = 48
	QRhi__InstanceIndexIncludesBaseInstance        QRhi__Feature = 49
	QRhi__DepthClamp                               QRhi__Feature = 50
)

type QRhi__EndFrameFlag int

const (
	QRhi__SkipPresent QRhi__EndFrameFlag = 1
)

type QRhi__ResourceLimit int

const (
	QRhi__TextureSizeMin              QRhi__ResourceLimit = 1
	QRhi__TextureSizeMax              QRhi__ResourceLimit = 2
	QRhi__MaxColorAttachments         QRhi__ResourceLimit = 3
	QRhi__FramesInFlight              QRhi__ResourceLimit = 4
	QRhi__MaxAsyncReadbackFrames      QRhi__ResourceLimit = 5
	QRhi__MaxThreadGroupsPerDimension QRhi__ResourceLimit = 6
	QRhi__MaxThreadsPerThreadGroup    QRhi__ResourceLimit = 7
	QRhi__MaxThreadGroupX             QRhi__ResourceLimit = 8
	QRhi__MaxThreadGroupY             QRhi__ResourceLimit = 9
	QRhi__MaxThreadGroupZ             QRhi__ResourceLimit = 10
	QRhi__TextureArraySizeMax         QRhi__ResourceLimit = 11
	QRhi__MaxUniformBufferRange       QRhi__ResourceLimit = 12
	QRhi__MaxVertexInputs             QRhi__ResourceLimit = 13
	QRhi__MaxVertexOutputs            QRhi__ResourceLimit = 14
	QRhi__ShadingRateImageTileSize    QRhi__ResourceLimit = 15
)

type QRhiViewport struct {
	h *C.QRhiViewport
}

func (this *QRhiViewport) cPointer() *C.QRhiViewport {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiViewport) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiViewport constructs the type using only CGO pointers.
func newQRhiViewport(h *C.QRhiViewport) *QRhiViewport {
	if h == nil {
		return nil
	}

	return &QRhiViewport{h: h}
}

// UnsafeNewQRhiViewport constructs the type using only unsafe pointers.
func UnsafeNewQRhiViewport(h unsafe.Pointer) *QRhiViewport {
	return newQRhiViewport((*C.QRhiViewport)(h))
}

// NewQRhiViewport constructs a new QRhiViewport object.
func NewQRhiViewport() *QRhiViewport {

	return newQRhiViewport(C.qtrhi_QRhiViewport_new())
}

// NewQRhiViewport2 constructs a new QRhiViewport object.
func NewQRhiViewport2(x float32, y float32, w float32, h float32) *QRhiViewport {

	return newQRhiViewport(C.qtrhi_QRhiViewport_new2((C.float)(x), (C.float)(y), (C.float)(w), (C.float)(h)))
}

// NewQRhiViewport3 constructs a new QRhiViewport object.
func NewQRhiViewport3(param1 *QRhiViewport) *QRhiViewport {

	return newQRhiViewport(C.qtrhi_QRhiViewport_new3(param1.cPointer()))
}

// NewQRhiViewport4 constructs a new QRhiViewport object.
func NewQRhiViewport4(x float32, y float32, w float32, h float32, minDepth float32) *QRhiViewport {

	return newQRhiViewport(C.qtrhi_QRhiViewport_new4((C.float)(x), (C.float)(y), (C.float)(w), (C.float)(h), (C.float)(minDepth)))
}

// NewQRhiViewport5 constructs a new QRhiViewport object.
func NewQRhiViewport5(x float32, y float32, w float32, h float32, minDepth float32, maxDepth float32) *QRhiViewport {

	return newQRhiViewport(C.qtrhi_QRhiViewport_new5((C.float)(x), (C.float)(y), (C.float)(w), (C.float)(h), (C.float)(minDepth), (C.float)(maxDepth)))
}

// Delete this object from C++ memory.
func (this *QRhiViewport) Delete() {
	C.qtrhi_QRhiViewport_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiViewport) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiViewport) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiScissor struct {
	h *C.QRhiScissor
}

func (this *QRhiScissor) cPointer() *C.QRhiScissor {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiScissor) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiScissor constructs the type using only CGO pointers.
func newQRhiScissor(h *C.QRhiScissor) *QRhiScissor {
	if h == nil {
		return nil
	}

	return &QRhiScissor{h: h}
}

// UnsafeNewQRhiScissor constructs the type using only unsafe pointers.
func UnsafeNewQRhiScissor(h unsafe.Pointer) *QRhiScissor {
	return newQRhiScissor((*C.QRhiScissor)(h))
}

// NewQRhiScissor constructs a new QRhiScissor object.
func NewQRhiScissor() *QRhiScissor {

	return newQRhiScissor(C.qtrhi_QRhiScissor_new())
}

// NewQRhiScissor2 constructs a new QRhiScissor object.
func NewQRhiScissor2(x int, y int, w int, h int) *QRhiScissor {

	return newQRhiScissor(C.qtrhi_QRhiScissor_new2((C.int)(x), (C.int)(y), (C.int)(w), (C.int)(h)))
}

// NewQRhiScissor3 constructs a new QRhiScissor object.
func NewQRhiScissor3(param1 *QRhiScissor) *QRhiScissor {

	return newQRhiScissor(C.qtrhi_QRhiScissor_new3(param1.cPointer()))
}

// Delete this object from C++ memory.
func (this *QRhiScissor) Delete() {
	C.qtrhi_QRhiScissor_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiScissor) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiScissor) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiVertexInputBinding struct {
	h *C.QRhiVertexInputBinding
}

func (this *QRhiVertexInputBinding) cPointer() *C.QRhiVertexInputBinding {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiVertexInputBinding) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiVertexInputBinding constructs the type using only CGO pointers.
func newQRhiVertexInputBinding(h *C.QRhiVertexInputBinding) *QRhiVertexInputBinding {
	if h == nil {
		return nil
	}

	return &QRhiVertexInputBinding{h: h}
}

// UnsafeNewQRhiVertexInputBinding constructs the type using only unsafe pointers.
func UnsafeNewQRhiVertexInputBinding(h unsafe.Pointer) *QRhiVertexInputBinding {
	return newQRhiVertexInputBinding((*C.QRhiVertexInputBinding)(h))
}

// NewQRhiVertexInputBinding constructs a new QRhiVertexInputBinding object.
func NewQRhiVertexInputBinding() *QRhiVertexInputBinding {

	return newQRhiVertexInputBinding(C.qtrhi_QRhiVertexInputBinding_new())
}

// NewQRhiVertexInputBinding2 constructs a new QRhiVertexInputBinding object.
func NewQRhiVertexInputBinding2(stride uint32) *QRhiVertexInputBinding {

	return newQRhiVertexInputBinding(C.qtrhi_QRhiVertexInputBinding_new2((C.uint32_t)(stride)))
}

// NewQRhiVertexInputBinding3 constructs a new QRhiVertexInputBinding object.
func NewQRhiVertexInputBinding3(param1 *QRhiVertexInputBinding) *QRhiVertexInputBinding {

	return newQRhiVertexInputBinding(C.qtrhi_QRhiVertexInputBinding_new3(param1.cPointer()))
}

// NewQRhiVertexInputBinding4 constructs a new QRhiVertexInputBinding object.
func NewQRhiVertexInputBinding4(stride uint32, cls QRhiVertexInputBinding__Classification) *QRhiVertexInputBinding {

	return newQRhiVertexInputBinding(C.qtrhi_QRhiVertexInputBinding_new4((C.uint32_t)(stride), (C.int)(cls)))
}

// NewQRhiVertexInputBinding5 constructs a new QRhiVertexInputBinding object.
func NewQRhiVertexInputBinding5(stride uint32, cls QRhiVertexInputBinding__Classification, stepRate uint32) *QRhiVertexInputBinding {

	return newQRhiVertexInputBinding(C.qtrhi_QRhiVertexInputBinding_new5((C.uint32_t)(stride), (C.int)(cls), (C.uint32_t)(stepRate)))
}

// Delete this object from C++ memory.
func (this *QRhiVertexInputBinding) Delete() {
	C.qtrhi_QRhiVertexInputBinding_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiVertexInputBinding) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiVertexInputBinding) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiVertexInputAttribute struct {
	h *C.QRhiVertexInputAttribute
}

func (this *QRhiVertexInputAttribute) cPointer() *C.QRhiVertexInputAttribute {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiVertexInputAttribute) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiVertexInputAttribute constructs the type using only CGO pointers.
func newQRhiVertexInputAttribute(h *C.QRhiVertexInputAttribute) *QRhiVertexInputAttribute {
	if h == nil {
		return nil
	}

	return &QRhiVertexInputAttribute{h: h}
}

// UnsafeNewQRhiVertexInputAttribute constructs the type using only unsafe pointers.
func UnsafeNewQRhiVertexInputAttribute(h unsafe.Pointer) *QRhiVertexInputAttribute {
	return newQRhiVertexInputAttribute((*C.QRhiVertexInputAttribute)(h))
}

// NewQRhiVertexInputAttribute constructs a new QRhiVertexInputAttribute object.
func NewQRhiVertexInputAttribute() *QRhiVertexInputAttribute {

	return newQRhiVertexInputAttribute(C.qtrhi_QRhiVertexInputAttribute_new())
}

// NewQRhiVertexInputAttribute2 constructs a new QRhiVertexInputAttribute object.
func NewQRhiVertexInputAttribute2(binding int, location int, format QRhiVertexInputAttribute__Format, offset uint32) *QRhiVertexInputAttribute {

	return newQRhiVertexInputAttribute(C.qtrhi_QRhiVertexInputAttribute_new2((C.int)(binding), (C.int)(location), (C.int)(format), (C.uint32_t)(offset)))
}

// NewQRhiVertexInputAttribute3 constructs a new QRhiVertexInputAttribute object.
func NewQRhiVertexInputAttribute3(param1 *QRhiVertexInputAttribute) *QRhiVertexInputAttribute {

	return newQRhiVertexInputAttribute(C.qtrhi_QRhiVertexInputAttribute_new3(param1.cPointer()))
}

// NewQRhiVertexInputAttribute4 constructs a new QRhiVertexInputAttribute object.
func NewQRhiVertexInputAttribute4(binding int, location int, format QRhiVertexInputAttribute__Format, offset uint32, matrixSlice int) *QRhiVertexInputAttribute {

	return newQRhiVertexInputAttribute(C.qtrhi_QRhiVertexInputAttribute_new4((C.int)(binding), (C.int)(location), (C.int)(format), (C.uint32_t)(offset), (C.int)(matrixSlice)))
}

// Delete this object from C++ memory.
func (this *QRhiVertexInputAttribute) Delete() {
	C.qtrhi_QRhiVertexInputAttribute_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiVertexInputAttribute) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiVertexInputAttribute) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiVertexInputLayout struct {
	h *C.QRhiVertexInputLayout
}

func (this *QRhiVertexInputLayout) cPointer() *C.QRhiVertexInputLayout {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiVertexInputLayout) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiVertexInputLayout constructs the type using only CGO pointers.
func newQRhiVertexInputLayout(h *C.QRhiVertexInputLayout) *QRhiVertexInputLayout {
	if h == nil {
		return nil
	}

	return &QRhiVertexInputLayout{h: h}
}

// UnsafeNewQRhiVertexInputLayout constructs the type using only unsafe pointers.
func UnsafeNewQRhiVertexInputLayout(h unsafe.Pointer) *QRhiVertexInputLayout {
	return newQRhiVertexInputLayout((*C.QRhiVertexInputLayout)(h))
}

// NewQRhiVertexInputLayout constructs a new QRhiVertexInputLayout object.
func NewQRhiVertexInputLayout() *QRhiVertexInputLayout {

	return newQRhiVertexInputLayout(C.qtrhi_QRhiVertexInputLayout_new())
}

// NewQRhiVertexInputLayout2 constructs a new QRhiVertexInputLayout object.
func NewQRhiVertexInputLayout2(param1 *QRhiVertexInputLayout) *QRhiVertexInputLayout {

	return newQRhiVertexInputLayout(C.qtrhi_QRhiVertexInputLayout_new2(param1.cPointer()))
}

func (this *QRhiVertexInputLayout) SetBindings(list []QRhiVertexInputBinding) {
	list_CArray := (*[0xffff]*C.QRhiVertexInputBinding)(C.malloc(C.size_t(8 * len(list))))
	defer C.free(unsafe.Pointer(list_CArray))
	for i := range list {
		list_CArray[i] = list[i].cPointer()
	}
	list_ma := C.struct_miqt_array{len: C.size_t(len(list)), data: unsafe.Pointer(list_CArray)}
	C.qtrhi_QRhiVertexInputLayout_setBindings(this.h, list_ma)
}

func (this *QRhiVertexInputLayout) SetAttributes(list []QRhiVertexInputAttribute) {
	list_CArray := (*[0xffff]*C.QRhiVertexInputAttribute)(C.malloc(C.size_t(8 * len(list))))
	defer C.free(unsafe.Pointer(list_CArray))
	for i := range list {
		list_CArray[i] = list[i].cPointer()
	}
	list_ma := C.struct_miqt_array{len: C.size_t(len(list)), data: unsafe.Pointer(list_CArray)}
	C.qtrhi_QRhiVertexInputLayout_setAttributes(this.h, list_ma)
}

// Delete this object from C++ memory.
func (this *QRhiVertexInputLayout) Delete() {
	C.qtrhi_QRhiVertexInputLayout_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiVertexInputLayout) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiVertexInputLayout) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiShaderStage struct {
	h *C.QRhiShaderStage
}

func (this *QRhiShaderStage) cPointer() *C.QRhiShaderStage {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiShaderStage) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiShaderStage constructs the type using only CGO pointers.
func newQRhiShaderStage(h *C.QRhiShaderStage) *QRhiShaderStage {
	if h == nil {
		return nil
	}

	return &QRhiShaderStage{h: h}
}

// UnsafeNewQRhiShaderStage constructs the type using only unsafe pointers.
func UnsafeNewQRhiShaderStage(h unsafe.Pointer) *QRhiShaderStage {
	return newQRhiShaderStage((*C.QRhiShaderStage)(h))
}

// NewQRhiShaderStage constructs a new QRhiShaderStage object.
func NewQRhiShaderStage() *QRhiShaderStage {

	return newQRhiShaderStage(C.qtrhi_QRhiShaderStage_new())
}

// NewQRhiShaderStage2 constructs a new QRhiShaderStage object.
func NewQRhiShaderStage2(typeVal QRhiShaderStage__Type, shader *QShader) *QRhiShaderStage {

	return newQRhiShaderStage(C.qtrhi_QRhiShaderStage_new2((C.int)(typeVal), shader.cPointer()))
}

// NewQRhiShaderStage3 constructs a new QRhiShaderStage object.
func NewQRhiShaderStage3(param1 *QRhiShaderStage) *QRhiShaderStage {

	return newQRhiShaderStage(C.qtrhi_QRhiShaderStage_new3(param1.cPointer()))
}

// NewQRhiShaderStage4 constructs a new QRhiShaderStage object.
func NewQRhiShaderStage4(typeVal QRhiShaderStage__Type, shader *QShader, v QShader__Variant) *QRhiShaderStage {

	return newQRhiShaderStage(C.qtrhi_QRhiShaderStage_new4((C.int)(typeVal), shader.cPointer(), (C.int)(v)))
}

// Delete this object from C++ memory.
func (this *QRhiShaderStage) Delete() {
	C.qtrhi_QRhiShaderStage_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiShaderStage) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiShaderStage) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiShaderResourceBinding struct {
	h *C.QRhiShaderResourceBinding
}

func (this *QRhiShaderResourceBinding) cPointer() *C.QRhiShaderResourceBinding {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiShaderResourceBinding) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiShaderResourceBinding constructs the type using only CGO pointers.
func newQRhiShaderResourceBinding(h *C.QRhiShaderResourceBinding) *QRhiShaderResourceBinding {
	if h == nil {
		return nil
	}

	return &QRhiShaderResourceBinding{h: h}
}

// UnsafeNewQRhiShaderResourceBinding constructs the type using only unsafe pointers.
func UnsafeNewQRhiShaderResourceBinding(h unsafe.Pointer) *QRhiShaderResourceBinding {
	return newQRhiShaderResourceBinding((*C.QRhiShaderResourceBinding)(h))
}

// NewQRhiShaderResourceBinding constructs a new QRhiShaderResourceBinding object.
func NewQRhiShaderResourceBinding() *QRhiShaderResourceBinding {

	return newQRhiShaderResourceBinding(C.qtrhi_QRhiShaderResourceBinding_new())
}

// NewQRhiShaderResourceBinding2 constructs a new QRhiShaderResourceBinding object.
func NewQRhiShaderResourceBinding2(param1 *QRhiShaderResourceBinding) *QRhiShaderResourceBinding {

	return newQRhiShaderResourceBinding(C.qtrhi_QRhiShaderResourceBinding_new2(param1.cPointer()))
}

func QRhiShaderResourceBinding_UniformBufferWithDynamicOffset(binding int, stage QRhiShaderResourceBinding__StageFlag, buf *QRhiBuffer, size uint32) *QRhiShaderResourceBinding {
	_goptr := newQRhiShaderResourceBinding(C.qtrhi_QRhiShaderResourceBinding_uniformBufferWithDynamicOffset((C.int)(binding), (C.int)(stage), buf.cPointer(), (C.uint32_t)(size)))
	return _goptr
}

func QRhiShaderResourceBinding_SampledTexture(binding int, stage QRhiShaderResourceBinding__StageFlag, tex *QRhiTexture, sampler *QRhiSampler) *QRhiShaderResourceBinding {
	_goptr := newQRhiShaderResourceBinding(C.qtrhi_QRhiShaderResourceBinding_sampledTexture((C.int)(binding), (C.int)(stage), tex.cPointer(), sampler.cPointer()))
	return _goptr
}

// Delete this object from C++ memory.
func (this *QRhiShaderResourceBinding) Delete() {
	C.qtrhi_QRhiShaderResourceBinding_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiShaderResourceBinding) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiShaderResourceBinding) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiTextureSubresourceUploadDescription struct {
	h *C.QRhiTextureSubresourceUploadDescription
}

func (this *QRhiTextureSubresourceUploadDescription) cPointer() *C.QRhiTextureSubresourceUploadDescription {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiTextureSubresourceUploadDescription) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiTextureSubresourceUploadDescription constructs the type using only CGO pointers.
func newQRhiTextureSubresourceUploadDescription(h *C.QRhiTextureSubresourceUploadDescription) *QRhiTextureSubresourceUploadDescription {
	if h == nil {
		return nil
	}

	return &QRhiTextureSubresourceUploadDescription{h: h}
}

// UnsafeNewQRhiTextureSubresourceUploadDescription constructs the type using only unsafe pointers.
func UnsafeNewQRhiTextureSubresourceUploadDescription(h unsafe.Pointer) *QRhiTextureSubresourceUploadDescription {
	return newQRhiTextureSubresourceUploadDescription((*C.QRhiTextureSubresourceUploadDescription)(h))
}

// NewQRhiTextureSubresourceUploadDescription constructs a new QRhiTextureSubresourceUploadDescription object.
func NewQRhiTextureSubresourceUploadDescription() *QRhiTextureSubresourceUploadDescription {

	return newQRhiTextureSubresourceUploadDescription(C.qtrhi_QRhiTextureSubresourceUploadDescription_new())
}

// NewQRhiTextureSubresourceUploadDescription2 constructs a new QRhiTextureSubresourceUploadDescription object.
func NewQRhiTextureSubresourceUploadDescription2(image *qt6.QImage) *QRhiTextureSubresourceUploadDescription {

	return newQRhiTextureSubresourceUploadDescription(C.qtrhi_QRhiTextureSubresourceUploadDescription_new2((*C.QImage)(image.UnsafePointer())))
}

// NewQRhiTextureSubresourceUploadDescription3 constructs a new QRhiTextureSubresourceUploadDescription object.
func NewQRhiTextureSubresourceUploadDescription3(data unsafe.Pointer, size uint32) *QRhiTextureSubresourceUploadDescription {

	return newQRhiTextureSubresourceUploadDescription(C.qtrhi_QRhiTextureSubresourceUploadDescription_new3(data, (C.uint32_t)(size)))
}

// NewQRhiTextureSubresourceUploadDescription4 constructs a new QRhiTextureSubresourceUploadDescription object.
func NewQRhiTextureSubresourceUploadDescription4(data []byte) *QRhiTextureSubresourceUploadDescription {
	data_alias := C.struct_miqt_string{}
	if len(data) > 0 {
		data_alias.data = (*C.char)(unsafe.Pointer(&data[0]))
	} else {
		data_alias.data = (*C.char)(unsafe.Pointer(nil))
	}
	data_alias.len = C.size_t(len(data))

	return newQRhiTextureSubresourceUploadDescription(C.qtrhi_QRhiTextureSubresourceUploadDescription_new4(data_alias))
}

// NewQRhiTextureSubresourceUploadDescription5 constructs a new QRhiTextureSubresourceUploadDescription object.
func NewQRhiTextureSubresourceUploadDescription5(param1 *QRhiTextureSubresourceUploadDescription) *QRhiTextureSubresourceUploadDescription {

	return newQRhiTextureSubresourceUploadDescription(C.qtrhi_QRhiTextureSubresourceUploadDescription_new5(param1.cPointer()))
}

func (this *QRhiTextureSubresourceUploadDescription) SetDestinationTopLeft(p *qt6.QPoint) {
	C.qtrhi_QRhiTextureSubresourceUploadDescription_setDestinationTopLeft(this.h, (*C.QPoint)(p.UnsafePointer()))
}

func (this *QRhiTextureSubresourceUploadDescription) SetSourceSize(size *qt6.QSize) {
	C.qtrhi_QRhiTextureSubresourceUploadDescription_setSourceSize(this.h, (*C.QSize)(size.UnsafePointer()))
}

// Delete this object from C++ memory.
func (this *QRhiTextureSubresourceUploadDescription) Delete() {
	C.qtrhi_QRhiTextureSubresourceUploadDescription_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiTextureSubresourceUploadDescription) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiTextureSubresourceUploadDescription) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiTextureUploadEntry struct {
	h *C.QRhiTextureUploadEntry
}

func (this *QRhiTextureUploadEntry) cPointer() *C.QRhiTextureUploadEntry {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiTextureUploadEntry) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiTextureUploadEntry constructs the type using only CGO pointers.
func newQRhiTextureUploadEntry(h *C.QRhiTextureUploadEntry) *QRhiTextureUploadEntry {
	if h == nil {
		return nil
	}

	return &QRhiTextureUploadEntry{h: h}
}

// UnsafeNewQRhiTextureUploadEntry constructs the type using only unsafe pointers.
func UnsafeNewQRhiTextureUploadEntry(h unsafe.Pointer) *QRhiTextureUploadEntry {
	return newQRhiTextureUploadEntry((*C.QRhiTextureUploadEntry)(h))
}

// NewQRhiTextureUploadEntry constructs a new QRhiTextureUploadEntry object.
func NewQRhiTextureUploadEntry() *QRhiTextureUploadEntry {

	return newQRhiTextureUploadEntry(C.qtrhi_QRhiTextureUploadEntry_new())
}

// NewQRhiTextureUploadEntry2 constructs a new QRhiTextureUploadEntry object.
func NewQRhiTextureUploadEntry2(layer int, level int, desc *QRhiTextureSubresourceUploadDescription) *QRhiTextureUploadEntry {

	return newQRhiTextureUploadEntry(C.qtrhi_QRhiTextureUploadEntry_new2((C.int)(layer), (C.int)(level), desc.cPointer()))
}

// NewQRhiTextureUploadEntry3 constructs a new QRhiTextureUploadEntry object.
func NewQRhiTextureUploadEntry3(param1 *QRhiTextureUploadEntry) *QRhiTextureUploadEntry {

	return newQRhiTextureUploadEntry(C.qtrhi_QRhiTextureUploadEntry_new3(param1.cPointer()))
}

// Delete this object from C++ memory.
func (this *QRhiTextureUploadEntry) Delete() {
	C.qtrhi_QRhiTextureUploadEntry_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiTextureUploadEntry) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiTextureUploadEntry) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiTextureUploadDescription struct {
	h *C.QRhiTextureUploadDescription
}

func (this *QRhiTextureUploadDescription) cPointer() *C.QRhiTextureUploadDescription {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiTextureUploadDescription) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiTextureUploadDescription constructs the type using only CGO pointers.
func newQRhiTextureUploadDescription(h *C.QRhiTextureUploadDescription) *QRhiTextureUploadDescription {
	if h == nil {
		return nil
	}

	return &QRhiTextureUploadDescription{h: h}
}

// UnsafeNewQRhiTextureUploadDescription constructs the type using only unsafe pointers.
func UnsafeNewQRhiTextureUploadDescription(h unsafe.Pointer) *QRhiTextureUploadDescription {
	return newQRhiTextureUploadDescription((*C.QRhiTextureUploadDescription)(h))
}

// NewQRhiTextureUploadDescription constructs a new QRhiTextureUploadDescription object.
func NewQRhiTextureUploadDescription() *QRhiTextureUploadDescription {

	return newQRhiTextureUploadDescription(C.qtrhi_QRhiTextureUploadDescription_new())
}

// NewQRhiTextureUploadDescription2 constructs a new QRhiTextureUploadDescription object.
func NewQRhiTextureUploadDescription2(entry *QRhiTextureUploadEntry) *QRhiTextureUploadDescription {

	return newQRhiTextureUploadDescription(C.qtrhi_QRhiTextureUploadDescription_new2(entry.cPointer()))
}

// NewQRhiTextureUploadDescription3 constructs a new QRhiTextureUploadDescription object.
func NewQRhiTextureUploadDescription3(param1 *QRhiTextureUploadDescription) *QRhiTextureUploadDescription {

	return newQRhiTextureUploadDescription(C.qtrhi_QRhiTextureUploadDescription_new3(param1.cPointer()))
}

func (this *QRhiTextureUploadDescription) SetEntries(list []QRhiTextureUploadEntry) {
	list_CArray := (*[0xffff]*C.QRhiTextureUploadEntry)(C.malloc(C.size_t(8 * len(list))))
	defer C.free(unsafe.Pointer(list_CArray))
	for i := range list {
		list_CArray[i] = list[i].cPointer()
	}
	list_ma := C.struct_miqt_array{len: C.size_t(len(list)), data: unsafe.Pointer(list_CArray)}
	C.qtrhi_QRhiTextureUploadDescription_setEntries(this.h, list_ma)
}

// Delete this object from C++ memory.
func (this *QRhiTextureUploadDescription) Delete() {
	C.qtrhi_QRhiTextureUploadDescription_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiTextureUploadDescription) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiTextureUploadDescription) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiResource struct {
	h *C.QRhiResource
}

func (this *QRhiResource) cPointer() *C.QRhiResource {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiResource) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiResource constructs the type using only CGO pointers.
func newQRhiResource(h *C.QRhiResource) *QRhiResource {
	if h == nil {
		return nil
	}

	return &QRhiResource{h: h}
}

// UnsafeNewQRhiResource constructs the type using only unsafe pointers.
func UnsafeNewQRhiResource(h unsafe.Pointer) *QRhiResource {
	return newQRhiResource((*C.QRhiResource)(h))
}

func (this *QRhiResource) Destroy() {
	C.qtrhi_QRhiResource_destroy(this.h)
}

func (this *QRhiResource) DeleteLater() {
	C.qtrhi_QRhiResource_deleteLater(this.h)
}

func (this *QRhiResource) SetName(name []byte) {
	name_alias := C.struct_miqt_string{}
	if len(name) > 0 {
		name_alias.data = (*C.char)(unsafe.Pointer(&name[0]))
	} else {
		name_alias.data = (*C.char)(unsafe.Pointer(nil))
	}
	name_alias.len = C.size_t(len(name))
	C.qtrhi_QRhiResource_setName(this.h, name_alias)
}

// Delete this object from C++ memory.
func (this *QRhiResource) Delete() {
	C.qtrhi_QRhiResource_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiResource) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiResource) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiBuffer struct {
	h *C.QRhiBuffer
	*QRhiResource
}

func (this *QRhiBuffer) cPointer() *C.QRhiBuffer {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiBuffer) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiBuffer constructs the type using only CGO pointers.
func newQRhiBuffer(h *C.QRhiBuffer) *QRhiBuffer {
	if h == nil {
		return nil
	}
	var outptr_QRhiResource *C.QRhiResource = nil
	C.qtrhi_QRhiBuffer_virtbase(h, &outptr_QRhiResource)

	return &QRhiBuffer{h: h,
		QRhiResource: newQRhiResource(outptr_QRhiResource)}
}

// UnsafeNewQRhiBuffer constructs the type using only unsafe pointers.
func UnsafeNewQRhiBuffer(h unsafe.Pointer) *QRhiBuffer {
	return newQRhiBuffer((*C.QRhiBuffer)(h))
}

func (this *QRhiBuffer) Size() uint32 {
	return (uint32)(C.qtrhi_QRhiBuffer_size(this.h))
}

func (this *QRhiBuffer) Create() bool {
	return (bool)(C.qtrhi_QRhiBuffer_create(this.h))
}

// Delete this object from C++ memory.
func (this *QRhiBuffer) Delete() {
	C.qtrhi_QRhiBuffer_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiBuffer) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiBuffer) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiTexture struct {
	h *C.QRhiTexture
	*QRhiResource
}

func (this *QRhiTexture) cPointer() *C.QRhiTexture {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiTexture) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiTexture constructs the type using only CGO pointers.
func newQRhiTexture(h *C.QRhiTexture) *QRhiTexture {
	if h == nil {
		return nil
	}
	var outptr_QRhiResource *C.QRhiResource = nil
	C.qtrhi_QRhiTexture_virtbase(h, &outptr_QRhiResource)

	return &QRhiTexture{h: h,
		QRhiResource: newQRhiResource(outptr_QRhiResource)}
}

// UnsafeNewQRhiTexture constructs the type using only unsafe pointers.
func UnsafeNewQRhiTexture(h unsafe.Pointer) *QRhiTexture {
	return newQRhiTexture((*C.QRhiTexture)(h))
}

func (this *QRhiTexture) PixelSize() *qt6.QSize {
	_goptr := qt6.UnsafeNewQSize(unsafe.Pointer(C.qtrhi_QRhiTexture_pixelSize(this.h)))
	return _goptr
}

func (this *QRhiTexture) Create() bool {
	return (bool)(C.qtrhi_QRhiTexture_create(this.h))
}

// Delete this object from C++ memory.
func (this *QRhiTexture) Delete() {
	C.qtrhi_QRhiTexture_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiTexture) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiTexture) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiSampler struct {
	h *C.QRhiSampler
	*QRhiResource
}

func (this *QRhiSampler) cPointer() *C.QRhiSampler {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiSampler) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiSampler constructs the type using only CGO pointers.
func newQRhiSampler(h *C.QRhiSampler) *QRhiSampler {
	if h == nil {
		return nil
	}
	var outptr_QRhiResource *C.QRhiResource = nil
	C.qtrhi_QRhiSampler_virtbase(h, &outptr_QRhiResource)

	return &QRhiSampler{h: h,
		QRhiResource: newQRhiResource(outptr_QRhiResource)}
}

// UnsafeNewQRhiSampler constructs the type using only unsafe pointers.
func UnsafeNewQRhiSampler(h unsafe.Pointer) *QRhiSampler {
	return newQRhiSampler((*C.QRhiSampler)(h))
}

func (this *QRhiSampler) Create() bool {
	return (bool)(C.qtrhi_QRhiSampler_create(this.h))
}

// Delete this object from C++ memory.
func (this *QRhiSampler) Delete() {
	C.qtrhi_QRhiSampler_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiSampler) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiSampler) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiRenderPassDescriptor struct {
	h *C.QRhiRenderPassDescriptor
	*QRhiResource
}

func (this *QRhiRenderPassDescriptor) cPointer() *C.QRhiRenderPassDescriptor {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiRenderPassDescriptor) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiRenderPassDescriptor constructs the type using only CGO pointers.
func newQRhiRenderPassDescriptor(h *C.QRhiRenderPassDescriptor) *QRhiRenderPassDescriptor {
	if h == nil {
		return nil
	}
	var outptr_QRhiResource *C.QRhiResource = nil
	C.qtrhi_QRhiRenderPassDescriptor_virtbase(h, &outptr_QRhiResource)

	return &QRhiRenderPassDescriptor{h: h,
		QRhiResource: newQRhiResource(outptr_QRhiResource)}
}

// UnsafeNewQRhiRenderPassDescriptor constructs the type using only unsafe pointers.
func UnsafeNewQRhiRenderPassDescriptor(h unsafe.Pointer) *QRhiRenderPassDescriptor {
	return newQRhiRenderPassDescriptor((*C.QRhiRenderPassDescriptor)(h))
}

func (this *QRhiRenderPassDescriptor) IsCompatible(other *QRhiRenderPassDescriptor) bool {
	return (bool)(C.qtrhi_QRhiRenderPassDescriptor_isCompatible(this.h, other.cPointer()))
}

func (this *QRhiRenderPassDescriptor) SerializedFormat() []uint32 {
	var _ma C.struct_miqt_array = C.qtrhi_QRhiRenderPassDescriptor_serializedFormat(this.h)
	_ret := make([]uint32, int(_ma.len))
	_outCast := (*[0xffff]C.uint32_t)(unsafe.Pointer(_ma.data)) // hey ya
	for i := 0; i < int(_ma.len); i++ {
		_ret[i] = (uint32)(_outCast[i])
	}
	return _ret
}

// Delete this object from C++ memory.
func (this *QRhiRenderPassDescriptor) Delete() {
	C.qtrhi_QRhiRenderPassDescriptor_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiRenderPassDescriptor) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiRenderPassDescriptor) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiRenderTarget struct {
	h *C.QRhiRenderTarget
	*QRhiResource
}

func (this *QRhiRenderTarget) cPointer() *C.QRhiRenderTarget {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiRenderTarget) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiRenderTarget constructs the type using only CGO pointers.
func newQRhiRenderTarget(h *C.QRhiRenderTarget) *QRhiRenderTarget {
	if h == nil {
		return nil
	}
	var outptr_QRhiResource *C.QRhiResource = nil
	C.qtrhi_QRhiRenderTarget_virtbase(h, &outptr_QRhiResource)

	return &QRhiRenderTarget{h: h,
		QRhiResource: newQRhiResource(outptr_QRhiResource)}
}

// UnsafeNewQRhiRenderTarget constructs the type using only unsafe pointers.
func UnsafeNewQRhiRenderTarget(h unsafe.Pointer) *QRhiRenderTarget {
	return newQRhiRenderTarget((*C.QRhiRenderTarget)(h))
}

func (this *QRhiRenderTarget) PixelSize() *qt6.QSize {
	_goptr := qt6.UnsafeNewQSize(unsafe.Pointer(C.qtrhi_QRhiRenderTarget_pixelSize(this.h)))
	return _goptr
}

func (this *QRhiRenderTarget) SampleCount() int {
	return (int)(C.qtrhi_QRhiRenderTarget_sampleCount(this.h))
}

func (this *QRhiRenderTarget) RenderPassDescriptor() *QRhiRenderPassDescriptor {
	return newQRhiRenderPassDescriptor(C.qtrhi_QRhiRenderTarget_renderPassDescriptor(this.h))
}

// Delete this object from C++ memory.
func (this *QRhiRenderTarget) Delete() {
	C.qtrhi_QRhiRenderTarget_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiRenderTarget) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiRenderTarget) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiShaderResourceBindings struct {
	h *C.QRhiShaderResourceBindings
	*QRhiResource
}

func (this *QRhiShaderResourceBindings) cPointer() *C.QRhiShaderResourceBindings {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiShaderResourceBindings) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiShaderResourceBindings constructs the type using only CGO pointers.
func newQRhiShaderResourceBindings(h *C.QRhiShaderResourceBindings) *QRhiShaderResourceBindings {
	if h == nil {
		return nil
	}
	var outptr_QRhiResource *C.QRhiResource = nil
	C.qtrhi_QRhiShaderResourceBindings_virtbase(h, &outptr_QRhiResource)

	return &QRhiShaderResourceBindings{h: h,
		QRhiResource: newQRhiResource(outptr_QRhiResource)}
}

// UnsafeNewQRhiShaderResourceBindings constructs the type using only unsafe pointers.
func UnsafeNewQRhiShaderResourceBindings(h unsafe.Pointer) *QRhiShaderResourceBindings {
	return newQRhiShaderResourceBindings((*C.QRhiShaderResourceBindings)(h))
}

func (this *QRhiShaderResourceBindings) SetBindings(list []QRhiShaderResourceBinding) {
	list_CArray := (*[0xffff]*C.QRhiShaderResourceBinding)(C.malloc(C.size_t(8 * len(list))))
	defer C.free(unsafe.Pointer(list_CArray))
	for i := range list {
		list_CArray[i] = list[i].cPointer()
	}
	list_ma := C.struct_miqt_array{len: C.size_t(len(list)), data: unsafe.Pointer(list_CArray)}
	C.qtrhi_QRhiShaderResourceBindings_setBindings(this.h, list_ma)
}

func (this *QRhiShaderResourceBindings) Create() bool {
	return (bool)(C.qtrhi_QRhiShaderResourceBindings_create(this.h))
}

// Delete this object from C++ memory.
func (this *QRhiShaderResourceBindings) Delete() {
	C.qtrhi_QRhiShaderResourceBindings_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiShaderResourceBindings) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiShaderResourceBindings) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiGraphicsPipeline struct {
	h *C.QRhiGraphicsPipeline
	*QRhiResource
}

func (this *QRhiGraphicsPipeline) cPointer() *C.QRhiGraphicsPipeline {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiGraphicsPipeline) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiGraphicsPipeline constructs the type using only CGO pointers.
func newQRhiGraphicsPipeline(h *C.QRhiGraphicsPipeline) *QRhiGraphicsPipeline {
	if h == nil {
		return nil
	}
	var outptr_QRhiResource *C.QRhiResource = nil
	C.qtrhi_QRhiGraphicsPipeline_virtbase(h, &outptr_QRhiResource)

	return &QRhiGraphicsPipeline{h: h,
		QRhiResource: newQRhiResource(outptr_QRhiResource)}
}

// UnsafeNewQRhiGraphicsPipeline constructs the type using only unsafe pointers.
func UnsafeNewQRhiGraphicsPipeline(h unsafe.Pointer) *QRhiGraphicsPipeline {
	return newQRhiGraphicsPipeline((*C.QRhiGraphicsPipeline)(h))
}

func (this *QRhiGraphicsPipeline) SetFlags(f QRhiGraphicsPipeline__Flag) {
	C.qtrhi_QRhiGraphicsPipeline_setFlags(this.h, (C.int)(f))
}

func (this *QRhiGraphicsPipeline) SetTargetBlends(list []QRhiGraphicsPipeline__TargetBlend) {
	list_CArray := (*[0xffff]*C.QRhiGraphicsPipeline__TargetBlend)(C.malloc(C.size_t(8 * len(list))))
	defer C.free(unsafe.Pointer(list_CArray))
	for i := range list {
		list_CArray[i] = list[i].cPointer()
	}
	list_ma := C.struct_miqt_array{len: C.size_t(len(list)), data: unsafe.Pointer(list_CArray)}
	C.qtrhi_QRhiGraphicsPipeline_setTargetBlends(this.h, list_ma)
}

func (this *QRhiGraphicsPipeline) SetDepthTest(enable bool) {
	C.qtrhi_QRhiGraphicsPipeline_setDepthTest(this.h, (C.bool)(enable))
}

func (this *QRhiGraphicsPipeline) SetDepthWrite(enable bool) {
	C.qtrhi_QRhiGraphicsPipeline_setDepthWrite(this.h, (C.bool)(enable))
}

func (this *QRhiGraphicsPipeline) SetStencilTest(enable bool) {
	C.qtrhi_QRhiGraphicsPipeline_setStencilTest(this.h, (C.bool)(enable))
}

func (this *QRhiGraphicsPipeline) SetStencilFront(state *QRhiGraphicsPipeline__StencilOpState) {
	C.qtrhi_QRhiGraphicsPipeline_setStencilFront(this.h, state.cPointer())
}

func (this *QRhiGraphicsPipeline) SetStencilBack(state *QRhiGraphicsPipeline__StencilOpState) {
	C.qtrhi_QRhiGraphicsPipeline_setStencilBack(this.h, state.cPointer())
}

func (this *QRhiGraphicsPipeline) SetStencilReadMask(mask uint32) {
	C.qtrhi_QRhiGraphicsPipeline_setStencilReadMask(this.h, (C.uint32_t)(mask))
}

func (this *QRhiGraphicsPipeline) SetStencilWriteMask(mask uint32) {
	C.qtrhi_QRhiGraphicsPipeline_setStencilWriteMask(this.h, (C.uint32_t)(mask))
}

func (this *QRhiGraphicsPipeline) SetSampleCount(s int) {
	C.qtrhi_QRhiGraphicsPipeline_setSampleCount(this.h, (C.int)(s))
}

func (this *QRhiGraphicsPipeline) SetShaderStages(list []QRhiShaderStage) {
	list_CArray := (*[0xffff]*C.QRhiShaderStage)(C.malloc(C.size_t(8 * len(list))))
	defer C.free(unsafe.Pointer(list_CArray))
	for i := range list {
		list_CArray[i] = list[i].cPointer()
	}
	list_ma := C.struct_miqt_array{len: C.size_t(len(list)), data: unsafe.Pointer(list_CArray)}
	C.qtrhi_QRhiGraphicsPipeline_setShaderStages(this.h, list_ma)
}

func (this *QRhiGraphicsPipeline) SetVertexInputLayout(layout *QRhiVertexInputLayout) {
	C.qtrhi_QRhiGraphicsPipeline_setVertexInputLayout(this.h, layout.cPointer())
}

func (this *QRhiGraphicsPipeline) SetShaderResourceBindings(srb *QRhiShaderResourceBindings) {
	C.qtrhi_QRhiGraphicsPipeline_setShaderResourceBindings(this.h, srb.cPointer())
}

func (this *QRhiGraphicsPipeline) SetRenderPassDescriptor(desc *QRhiRenderPassDescriptor) {
	C.qtrhi_QRhiGraphicsPipeline_setRenderPassDescriptor(this.h, desc.cPointer())
}

func (this *QRhiGraphicsPipeline) Create() bool {
	return (bool)(C.qtrhi_QRhiGraphicsPipeline_create(this.h))
}

// Delete this object from C++ memory.
func (this *QRhiGraphicsPipeline) Delete() {
	C.qtrhi_QRhiGraphicsPipeline_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiGraphicsPipeline) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiGraphicsPipeline) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiCommandBuffer struct {
	h *C.QRhiCommandBuffer
	*QRhiResource
}

func (this *QRhiCommandBuffer) cPointer() *C.QRhiCommandBuffer {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiCommandBuffer) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiCommandBuffer constructs the type using only CGO pointers.
func newQRhiCommandBuffer(h *C.QRhiCommandBuffer) *QRhiCommandBuffer {
	if h == nil {
		return nil
	}
	var outptr_QRhiResource *C.QRhiResource = nil
	C.qtrhi_QRhiCommandBuffer_virtbase(h, &outptr_QRhiResource)

	return &QRhiCommandBuffer{h: h,
		QRhiResource: newQRhiResource(outptr_QRhiResource)}
}

// UnsafeNewQRhiCommandBuffer constructs the type using only unsafe pointers.
func UnsafeNewQRhiCommandBuffer(h unsafe.Pointer) *QRhiCommandBuffer {
	return newQRhiCommandBuffer((*C.QRhiCommandBuffer)(h))
}

func (this *QRhiCommandBuffer) ResourceUpdate(resourceUpdates *QRhiResourceUpdateBatch) {
	C.qtrhi_QRhiCommandBuffer_resourceUpdate(this.h, resourceUpdates.cPointer())
}

func (this *QRhiCommandBuffer) SetGraphicsPipeline(ps *QRhiGraphicsPipeline) {
	C.qtrhi_QRhiCommandBuffer_setGraphicsPipeline(this.h, ps.cPointer())
}

func (this *QRhiCommandBuffer) SetShaderResources() {
	C.qtrhi_QRhiCommandBuffer_setShaderResources(this.h)
}

func (this *QRhiCommandBuffer) SetVertexInput(startBinding int, bindingCount int, bindings struct {
	First  *QRhiBuffer
	Second uint32
}) {
	if bindingCount != 1 {
		panic("qtrhi: expected one vertex binding")
	}
	bindings_First_CArray := (*[0xffff]*C.QRhiBuffer)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(bindings_First_CArray))
	bindings_Second_CArray := (*[0xffff]C.uint32_t)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(bindings_Second_CArray))
	bindings_First_CArray[0] = bindings.First.cPointer()
	bindings_Second_CArray[0] = (C.uint32_t)(bindings.Second)
	bindings_pair := C.struct_miqt_map{
		len:    1,
		keys:   unsafe.Pointer(bindings_First_CArray),
		values: unsafe.Pointer(bindings_Second_CArray),
	}
	C.qtrhi_QRhiCommandBuffer_setVertexInput(this.h, (C.int)(startBinding), (C.int)(bindingCount), bindings_pair)
}

func (this *QRhiCommandBuffer) SetViewport(viewport *QRhiViewport) {
	C.qtrhi_QRhiCommandBuffer_setViewport(this.h, viewport.cPointer())
}

func (this *QRhiCommandBuffer) SetScissor(scissor *QRhiScissor) {
	C.qtrhi_QRhiCommandBuffer_setScissor(this.h, scissor.cPointer())
}

func (this *QRhiCommandBuffer) SetStencilRef(refValue uint32) {
	C.qtrhi_QRhiCommandBuffer_setStencilRef(this.h, (C.uint32_t)(refValue))
}

func (this *QRhiCommandBuffer) Draw(vertexCount uint32) {
	C.qtrhi_QRhiCommandBuffer_draw(this.h, (C.uint32_t)(vertexCount))
}

func (this *QRhiCommandBuffer) DrawIndexed(indexCount uint32) {
	C.qtrhi_QRhiCommandBuffer_drawIndexed(this.h, (C.uint32_t)(indexCount))
}

func (this *QRhiCommandBuffer) LastCompletedGpuTime() float64 {
	return (float64)(C.qtrhi_QRhiCommandBuffer_lastCompletedGpuTime(this.h))
}

func (this *QRhiCommandBuffer) SetShaderResourcesWithSrb(srb *QRhiShaderResourceBindings) {
	C.qtrhi_QRhiCommandBuffer_setShaderResourcesWithSrb(this.h, srb.cPointer())
}

func (this *QRhiCommandBuffer) SetShaderResources2(srb *QRhiShaderResourceBindings, dynamicOffsetCount int) {
	if dynamicOffsetCount != 0 {
		panic("qtrhi: no offset array supplied")
	}
	C.qtrhi_QRhiCommandBuffer_setShaderResources2(this.h, srb.cPointer(), (C.int)(dynamicOffsetCount))
}

func (this *QRhiCommandBuffer) SetShaderResources3(srb *QRhiShaderResourceBindings, dynamicOffsetCount int, dynamicOffsets struct {
	First  int
	Second uint32
}) {
	if dynamicOffsetCount != 1 {
		panic("qtrhi: expected one dynamic offset")
	}
	dynamicOffsets_First_CArray := (*[0xffff]C.int)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(dynamicOffsets_First_CArray))
	dynamicOffsets_Second_CArray := (*[0xffff]C.uint32_t)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(dynamicOffsets_Second_CArray))
	dynamicOffsets_First_CArray[0] = (C.int)(dynamicOffsets.First)
	dynamicOffsets_Second_CArray[0] = (C.uint32_t)(dynamicOffsets.Second)
	dynamicOffsets_pair := C.struct_miqt_map{
		len:    1,
		keys:   unsafe.Pointer(dynamicOffsets_First_CArray),
		values: unsafe.Pointer(dynamicOffsets_Second_CArray),
	}
	C.qtrhi_QRhiCommandBuffer_setShaderResources3(this.h, srb.cPointer(), (C.int)(dynamicOffsetCount), dynamicOffsets_pair)
}

func (this *QRhiCommandBuffer) SetVertexInput2(startBinding int, bindingCount int, bindings struct {
	First  *QRhiBuffer
	Second uint32
}, indexBuf *QRhiBuffer) {
	if bindingCount != 1 {
		panic("qtrhi: expected one vertex binding")
	}
	bindings_First_CArray := (*[0xffff]*C.QRhiBuffer)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(bindings_First_CArray))
	bindings_Second_CArray := (*[0xffff]C.uint32_t)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(bindings_Second_CArray))
	bindings_First_CArray[0] = bindings.First.cPointer()
	bindings_Second_CArray[0] = (C.uint32_t)(bindings.Second)
	bindings_pair := C.struct_miqt_map{
		len:    1,
		keys:   unsafe.Pointer(bindings_First_CArray),
		values: unsafe.Pointer(bindings_Second_CArray),
	}
	C.qtrhi_QRhiCommandBuffer_setVertexInput2(this.h, (C.int)(startBinding), (C.int)(bindingCount), bindings_pair, indexBuf.cPointer())
}

func (this *QRhiCommandBuffer) SetVertexInput3(startBinding int, bindingCount int, bindings struct {
	First  *QRhiBuffer
	Second uint32
}, indexBuf *QRhiBuffer, indexOffset uint32) {
	if bindingCount != 1 {
		panic("qtrhi: expected one vertex binding")
	}
	bindings_First_CArray := (*[0xffff]*C.QRhiBuffer)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(bindings_First_CArray))
	bindings_Second_CArray := (*[0xffff]C.uint32_t)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(bindings_Second_CArray))
	bindings_First_CArray[0] = bindings.First.cPointer()
	bindings_Second_CArray[0] = (C.uint32_t)(bindings.Second)
	bindings_pair := C.struct_miqt_map{
		len:    1,
		keys:   unsafe.Pointer(bindings_First_CArray),
		values: unsafe.Pointer(bindings_Second_CArray),
	}
	C.qtrhi_QRhiCommandBuffer_setVertexInput3(this.h, (C.int)(startBinding), (C.int)(bindingCount), bindings_pair, indexBuf.cPointer(), (C.uint32_t)(indexOffset))
}

func (this *QRhiCommandBuffer) SetVertexInput4(startBinding int, bindingCount int, bindings struct {
	First  *QRhiBuffer
	Second uint32
}, indexBuf *QRhiBuffer, indexOffset uint32, indexFormat QRhiCommandBuffer__IndexFormat) {
	if bindingCount != 1 {
		panic("qtrhi: expected one vertex binding")
	}
	bindings_First_CArray := (*[0xffff]*C.QRhiBuffer)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(bindings_First_CArray))
	bindings_Second_CArray := (*[0xffff]C.uint32_t)(C.malloc(C.size_t(8)))
	defer C.free(unsafe.Pointer(bindings_Second_CArray))
	bindings_First_CArray[0] = bindings.First.cPointer()
	bindings_Second_CArray[0] = (C.uint32_t)(bindings.Second)
	bindings_pair := C.struct_miqt_map{
		len:    1,
		keys:   unsafe.Pointer(bindings_First_CArray),
		values: unsafe.Pointer(bindings_Second_CArray),
	}
	C.qtrhi_QRhiCommandBuffer_setVertexInput4(this.h, (C.int)(startBinding), (C.int)(bindingCount), bindings_pair, indexBuf.cPointer(), (C.uint32_t)(indexOffset), (C.int)(indexFormat))
}

func (this *QRhiCommandBuffer) Draw2(vertexCount uint32, instanceCount uint32) {
	C.qtrhi_QRhiCommandBuffer_draw2(this.h, (C.uint32_t)(vertexCount), (C.uint32_t)(instanceCount))
}

func (this *QRhiCommandBuffer) Draw3(vertexCount uint32, instanceCount uint32, firstVertex uint32) {
	C.qtrhi_QRhiCommandBuffer_draw3(this.h, (C.uint32_t)(vertexCount), (C.uint32_t)(instanceCount), (C.uint32_t)(firstVertex))
}

func (this *QRhiCommandBuffer) Draw4(vertexCount uint32, instanceCount uint32, firstVertex uint32, firstInstance uint32) {
	C.qtrhi_QRhiCommandBuffer_draw4(this.h, (C.uint32_t)(vertexCount), (C.uint32_t)(instanceCount), (C.uint32_t)(firstVertex), (C.uint32_t)(firstInstance))
}

func (this *QRhiCommandBuffer) DrawIndexed2(indexCount uint32, instanceCount uint32) {
	C.qtrhi_QRhiCommandBuffer_drawIndexed2(this.h, (C.uint32_t)(indexCount), (C.uint32_t)(instanceCount))
}

func (this *QRhiCommandBuffer) DrawIndexed3(indexCount uint32, instanceCount uint32, firstIndex uint32) {
	C.qtrhi_QRhiCommandBuffer_drawIndexed3(this.h, (C.uint32_t)(indexCount), (C.uint32_t)(instanceCount), (C.uint32_t)(firstIndex))
}

func (this *QRhiCommandBuffer) DrawIndexed4(indexCount uint32, instanceCount uint32, firstIndex uint32, vertexOffset int32) {
	C.qtrhi_QRhiCommandBuffer_drawIndexed4(this.h, (C.uint32_t)(indexCount), (C.uint32_t)(instanceCount), (C.uint32_t)(firstIndex), (C.int32_t)(vertexOffset))
}

func (this *QRhiCommandBuffer) DrawIndexed5(indexCount uint32, instanceCount uint32, firstIndex uint32, vertexOffset int32, firstInstance uint32) {
	C.qtrhi_QRhiCommandBuffer_drawIndexed5(this.h, (C.uint32_t)(indexCount), (C.uint32_t)(instanceCount), (C.uint32_t)(firstIndex), (C.int32_t)(vertexOffset), (C.uint32_t)(firstInstance))
}

// Delete this object from C++ memory.
func (this *QRhiCommandBuffer) Delete() {
	C.qtrhi_QRhiCommandBuffer_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiCommandBuffer) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiCommandBuffer) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiResourceUpdateBatch struct {
	h *C.QRhiResourceUpdateBatch
}

func (this *QRhiResourceUpdateBatch) cPointer() *C.QRhiResourceUpdateBatch {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiResourceUpdateBatch) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiResourceUpdateBatch constructs the type using only CGO pointers.
func newQRhiResourceUpdateBatch(h *C.QRhiResourceUpdateBatch) *QRhiResourceUpdateBatch {
	if h == nil {
		return nil
	}

	return &QRhiResourceUpdateBatch{h: h}
}

// UnsafeNewQRhiResourceUpdateBatch constructs the type using only unsafe pointers.
func UnsafeNewQRhiResourceUpdateBatch(h unsafe.Pointer) *QRhiResourceUpdateBatch {
	return newQRhiResourceUpdateBatch((*C.QRhiResourceUpdateBatch)(h))
}

func (this *QRhiResourceUpdateBatch) Release() {
	C.qtrhi_QRhiResourceUpdateBatch_release(this.h)
}

func (this *QRhiResourceUpdateBatch) UpdateDynamicBuffer(buf *QRhiBuffer, offset uint32, size uint32, data unsafe.Pointer) {
	C.qtrhi_QRhiResourceUpdateBatch_updateDynamicBuffer(this.h, buf.cPointer(), (C.uint32_t)(offset), (C.uint32_t)(size), data)
}

func (this *QRhiResourceUpdateBatch) UpdateDynamicBuffer2(buf *QRhiBuffer, offset uint32, data []byte) {
	data_alias := C.struct_miqt_string{}
	if len(data) > 0 {
		data_alias.data = (*C.char)(unsafe.Pointer(&data[0]))
	} else {
		data_alias.data = (*C.char)(unsafe.Pointer(nil))
	}
	data_alias.len = C.size_t(len(data))
	C.qtrhi_QRhiResourceUpdateBatch_updateDynamicBuffer2(this.h, buf.cPointer(), (C.uint32_t)(offset), data_alias)
}

func (this *QRhiResourceUpdateBatch) UploadStaticBuffer(buf *QRhiBuffer, offset uint32, size uint32, data unsafe.Pointer) {
	C.qtrhi_QRhiResourceUpdateBatch_uploadStaticBuffer(this.h, buf.cPointer(), (C.uint32_t)(offset), (C.uint32_t)(size), data)
}

func (this *QRhiResourceUpdateBatch) UploadStaticBuffer2(buf *QRhiBuffer, offset uint32, data []byte) {
	data_alias := C.struct_miqt_string{}
	if len(data) > 0 {
		data_alias.data = (*C.char)(unsafe.Pointer(&data[0]))
	} else {
		data_alias.data = (*C.char)(unsafe.Pointer(nil))
	}
	data_alias.len = C.size_t(len(data))
	C.qtrhi_QRhiResourceUpdateBatch_uploadStaticBuffer2(this.h, buf.cPointer(), (C.uint32_t)(offset), data_alias)
}

func (this *QRhiResourceUpdateBatch) UploadStaticBuffer3(buf *QRhiBuffer, data unsafe.Pointer) {
	C.qtrhi_QRhiResourceUpdateBatch_uploadStaticBuffer3(this.h, buf.cPointer(), data)
}

func (this *QRhiResourceUpdateBatch) UploadStaticBuffer4(buf *QRhiBuffer, data []byte) {
	data_alias := C.struct_miqt_string{}
	if len(data) > 0 {
		data_alias.data = (*C.char)(unsafe.Pointer(&data[0]))
	} else {
		data_alias.data = (*C.char)(unsafe.Pointer(nil))
	}
	data_alias.len = C.size_t(len(data))
	C.qtrhi_QRhiResourceUpdateBatch_uploadStaticBuffer4(this.h, buf.cPointer(), data_alias)
}

func (this *QRhiResourceUpdateBatch) UploadTexture(tex *QRhiTexture, desc *QRhiTextureUploadDescription) {
	C.qtrhi_QRhiResourceUpdateBatch_uploadTexture(this.h, tex.cPointer(), desc.cPointer())
}

func (this *QRhiResourceUpdateBatch) UploadTexture2(tex *QRhiTexture, image *qt6.QImage) {
	C.qtrhi_QRhiResourceUpdateBatch_uploadTexture2(this.h, tex.cPointer(), (*C.QImage)(image.UnsafePointer()))
}

// Delete this object from C++ memory.
func (this *QRhiResourceUpdateBatch) Delete() {
	C.qtrhi_QRhiResourceUpdateBatch_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiResourceUpdateBatch) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiResourceUpdateBatch) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiDriverInfo struct {
	h *C.QRhiDriverInfo
}

func (this *QRhiDriverInfo) cPointer() *C.QRhiDriverInfo {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiDriverInfo) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiDriverInfo constructs the type using only CGO pointers.
func newQRhiDriverInfo(h *C.QRhiDriverInfo) *QRhiDriverInfo {
	if h == nil {
		return nil
	}

	return &QRhiDriverInfo{h: h}
}

// UnsafeNewQRhiDriverInfo constructs the type using only unsafe pointers.
func UnsafeNewQRhiDriverInfo(h unsafe.Pointer) *QRhiDriverInfo {
	return newQRhiDriverInfo((*C.QRhiDriverInfo)(h))
}

// NewQRhiDriverInfo constructs a new QRhiDriverInfo object.
func NewQRhiDriverInfo(param1 *QRhiDriverInfo) *QRhiDriverInfo {

	return newQRhiDriverInfo(C.qtrhi_QRhiDriverInfo_new(param1.cPointer()))
}

// NewQRhiDriverInfo2 constructs a new QRhiDriverInfo object.
func NewQRhiDriverInfo2() *QRhiDriverInfo {

	return newQRhiDriverInfo(C.qtrhi_QRhiDriverInfo_new2())
}

func (this *QRhiDriverInfo) DeviceName() []byte {
	var deviceName_bytearray C.struct_miqt_string = C.qtrhi_QRhiDriverInfo_deviceName(this.h)
	deviceName_ret := C.GoBytes(unsafe.Pointer(deviceName_bytearray.data), C.int(int64(deviceName_bytearray.len)))
	C.free(unsafe.Pointer(deviceName_bytearray.data))
	return deviceName_ret
}

func (this *QRhiDriverInfo) SetDeviceName(deviceName []byte) {
	deviceName_alias := C.struct_miqt_string{}
	if len(deviceName) > 0 {
		deviceName_alias.data = (*C.char)(unsafe.Pointer(&deviceName[0]))
	} else {
		deviceName_alias.data = (*C.char)(unsafe.Pointer(nil))
	}
	deviceName_alias.len = C.size_t(len(deviceName))
	C.qtrhi_QRhiDriverInfo_setDeviceName(this.h, deviceName_alias)
}

func (this *QRhiDriverInfo) DeviceId() uint64 {
	return (uint64)(C.qtrhi_QRhiDriverInfo_deviceId(this.h))
}

func (this *QRhiDriverInfo) SetDeviceId(deviceId uint64) {
	C.qtrhi_QRhiDriverInfo_setDeviceId(this.h, (C.uint64_t)(deviceId))
}

func (this *QRhiDriverInfo) VendorId() uint64 {
	return (uint64)(C.qtrhi_QRhiDriverInfo_vendorId(this.h))
}

func (this *QRhiDriverInfo) SetVendorId(vendorId uint64) {
	C.qtrhi_QRhiDriverInfo_setVendorId(this.h, (C.uint64_t)(vendorId))
}

func (this *QRhiDriverInfo) DeviceType() QRhiDriverInfo__DeviceType {
	return (QRhiDriverInfo__DeviceType)(C.qtrhi_QRhiDriverInfo_deviceType(this.h))
}

func (this *QRhiDriverInfo) SetDeviceType(deviceType QRhiDriverInfo__DeviceType) {
	C.qtrhi_QRhiDriverInfo_setDeviceType(this.h, (C.int)(deviceType))
}

// Delete this object from C++ memory.
func (this *QRhiDriverInfo) Delete() {
	C.qtrhi_QRhiDriverInfo_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiDriverInfo) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiDriverInfo) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhi struct {
	h *C.QRhi
}

func (this *QRhi) cPointer() *C.QRhi {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhi) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhi constructs the type using only CGO pointers.
func newQRhi(h *C.QRhi) *QRhi {
	if h == nil {
		return nil
	}

	return &QRhi{h: h}
}

// UnsafeNewQRhi constructs the type using only unsafe pointers.
func UnsafeNewQRhi(h unsafe.Pointer) *QRhi {
	return newQRhi((*C.QRhi)(h))
}

func (this *QRhi) Backend() QRhi__Implementation {
	return (QRhi__Implementation)(C.qtrhi_QRhi_backend(this.h))
}

func (this *QRhi) BackendName() string {
	_ret := C.qtrhi_QRhi_backendName(this.h)
	return C.GoString(_ret)
}

func QRhi_BackendNameWithImpl(impl QRhi__Implementation) string {
	_ret := C.qtrhi_QRhi_backendNameWithImpl((C.int)(impl))
	return C.GoString(_ret)
}

func (this *QRhi) DriverInfo() *QRhiDriverInfo {
	_goptr := newQRhiDriverInfo(C.qtrhi_QRhi_driverInfo(this.h))
	return _goptr
}

func (this *QRhi) NewGraphicsPipeline() *QRhiGraphicsPipeline {
	return newQRhiGraphicsPipeline(C.qtrhi_QRhi_newGraphicsPipeline(this.h))
}

func (this *QRhi) NewShaderResourceBindings() *QRhiShaderResourceBindings {
	return newQRhiShaderResourceBindings(C.qtrhi_QRhi_newShaderResourceBindings(this.h))
}

func (this *QRhi) NewBuffer(typeVal QRhiBuffer__Type, usage QRhiBuffer__UsageFlag, size uint32) *QRhiBuffer {
	return newQRhiBuffer(C.qtrhi_QRhi_newBuffer(this.h, (C.int)(typeVal), (C.int)(usage), (C.uint32_t)(size)))
}

func (this *QRhi) NewTexture(format QRhiTexture__Format, pixelSize *qt6.QSize) *QRhiTexture {
	return newQRhiTexture(C.qtrhi_QRhi_newTexture(this.h, (C.int)(format), (*C.QSize)(pixelSize.UnsafePointer())))
}

func (this *QRhi) NewTexture2(format QRhiTexture__Format, width int, height int, depth int) *QRhiTexture {
	return newQRhiTexture(C.qtrhi_QRhi_newTexture2(this.h, (C.int)(format), (C.int)(width), (C.int)(height), (C.int)(depth)))
}

func (this *QRhi) NewSampler(magFilter QRhiSampler__Filter, minFilter QRhiSampler__Filter, mipmapMode QRhiSampler__Filter, addressU QRhiSampler__AddressMode, addressV QRhiSampler__AddressMode) *QRhiSampler {
	return newQRhiSampler(C.qtrhi_QRhi_newSampler(this.h, (C.int)(magFilter), (C.int)(minFilter), (C.int)(mipmapMode), (C.int)(addressU), (C.int)(addressV)))
}

func (this *QRhi) IsRecordingFrame() bool {
	return (bool)(C.qtrhi_QRhi_isRecordingFrame(this.h))
}

func (this *QRhi) Finish() QRhi__FrameOpResult {
	return (QRhi__FrameOpResult)(C.qtrhi_QRhi_finish(this.h))
}

func (this *QRhi) NextResourceUpdateBatch() *QRhiResourceUpdateBatch {
	return newQRhiResourceUpdateBatch(C.qtrhi_QRhi_nextResourceUpdateBatch(this.h))
}

func (this *QRhi) UbufAlignment() int {
	return (int)(C.qtrhi_QRhi_ubufAlignment(this.h))
}

func (this *QRhi) UbufAligned(v int) int {
	return (int)(C.qtrhi_QRhi_ubufAligned(this.h, (C.int)(v)))
}

func (this *QRhi) IsYUpInFramebuffer() bool {
	return (bool)(C.qtrhi_QRhi_isYUpInFramebuffer(this.h))
}

func (this *QRhi) IsFeatureSupported(feature QRhi__Feature) bool {
	return (bool)(C.qtrhi_QRhi_isFeatureSupported(this.h, (C.int)(feature)))
}

func (this *QRhi) IsDeviceLost() bool {
	return (bool)(C.qtrhi_QRhi_isDeviceLost(this.h))
}

func (this *QRhi) NewTexture3(format QRhiTexture__Format, pixelSize *qt6.QSize, sampleCount int) *QRhiTexture {
	return newQRhiTexture(C.qtrhi_QRhi_newTexture3(this.h, (C.int)(format), (*C.QSize)(pixelSize.UnsafePointer()), (C.int)(sampleCount)))
}

func (this *QRhi) NewTexture4(format QRhiTexture__Format, pixelSize *qt6.QSize, sampleCount int, flags QRhiTexture__Flag) *QRhiTexture {
	return newQRhiTexture(C.qtrhi_QRhi_newTexture4(this.h, (C.int)(format), (*C.QSize)(pixelSize.UnsafePointer()), (C.int)(sampleCount), (C.int)(flags)))
}

func (this *QRhi) NewTexture5(format QRhiTexture__Format, width int, height int, depth int, sampleCount int) *QRhiTexture {
	return newQRhiTexture(C.qtrhi_QRhi_newTexture5(this.h, (C.int)(format), (C.int)(width), (C.int)(height), (C.int)(depth), (C.int)(sampleCount)))
}

func (this *QRhi) NewTexture6(format QRhiTexture__Format, width int, height int, depth int, sampleCount int, flags QRhiTexture__Flag) *QRhiTexture {
	return newQRhiTexture(C.qtrhi_QRhi_newTexture6(this.h, (C.int)(format), (C.int)(width), (C.int)(height), (C.int)(depth), (C.int)(sampleCount), (C.int)(flags)))
}

func (this *QRhi) NewSampler2(magFilter QRhiSampler__Filter, minFilter QRhiSampler__Filter, mipmapMode QRhiSampler__Filter, addressU QRhiSampler__AddressMode, addressV QRhiSampler__AddressMode, addressW QRhiSampler__AddressMode) *QRhiSampler {
	return newQRhiSampler(C.qtrhi_QRhi_newSampler2(this.h, (C.int)(magFilter), (C.int)(minFilter), (C.int)(mipmapMode), (C.int)(addressU), (C.int)(addressV), (C.int)(addressW)))
}

// Delete this object from C++ memory.
func (this *QRhi) Delete() {
	C.qtrhi_QRhi_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhi) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhi) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiGraphicsPipeline__TargetBlend struct {
	h *C.QRhiGraphicsPipeline__TargetBlend
}

func (this *QRhiGraphicsPipeline__TargetBlend) cPointer() *C.QRhiGraphicsPipeline__TargetBlend {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiGraphicsPipeline__TargetBlend) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiGraphicsPipeline__TargetBlend constructs the type using only CGO pointers.
func newQRhiGraphicsPipeline__TargetBlend(h *C.QRhiGraphicsPipeline__TargetBlend) *QRhiGraphicsPipeline__TargetBlend {
	if h == nil {
		return nil
	}

	return &QRhiGraphicsPipeline__TargetBlend{h: h}
}

// UnsafeNewQRhiGraphicsPipeline__TargetBlend constructs the type using only unsafe pointers.
func UnsafeNewQRhiGraphicsPipeline__TargetBlend(h unsafe.Pointer) *QRhiGraphicsPipeline__TargetBlend {
	return newQRhiGraphicsPipeline__TargetBlend((*C.QRhiGraphicsPipeline__TargetBlend)(h))
}

// NewQRhiGraphicsPipeline__TargetBlend constructs a new QRhiGraphicsPipeline::TargetBlend object.
func NewQRhiGraphicsPipeline__TargetBlend() *QRhiGraphicsPipeline__TargetBlend {

	return newQRhiGraphicsPipeline__TargetBlend(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_new())
}

// NewQRhiGraphicsPipeline__TargetBlend2 constructs a new QRhiGraphicsPipeline::TargetBlend object.
func NewQRhiGraphicsPipeline__TargetBlend2(param1 *QRhiGraphicsPipeline__TargetBlend) *QRhiGraphicsPipeline__TargetBlend {

	return newQRhiGraphicsPipeline__TargetBlend(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_new2(param1.cPointer()))
}

func (this *QRhiGraphicsPipeline__TargetBlend) ColorWrite() QRhiGraphicsPipeline__ColorMaskComponent {
	return (QRhiGraphicsPipeline__ColorMaskComponent)(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_colorWrite(this.h))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SetColorWrite(colorWrite QRhiGraphicsPipeline__ColorMaskComponent) {
	C.qtrhi_QRhiGraphicsPipeline__TargetBlend_setColorWrite(this.h, (C.int)(colorWrite))
}

func (this *QRhiGraphicsPipeline__TargetBlend) Enable() bool {
	return (bool)(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_enable(this.h))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SetEnable(enable bool) {
	C.qtrhi_QRhiGraphicsPipeline__TargetBlend_setEnable(this.h, (C.bool)(enable))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SrcColor() QRhiGraphicsPipeline__BlendFactor {
	return (QRhiGraphicsPipeline__BlendFactor)(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_srcColor(this.h))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SetSrcColor(srcColor QRhiGraphicsPipeline__BlendFactor) {
	C.qtrhi_QRhiGraphicsPipeline__TargetBlend_setSrcColor(this.h, (C.int)(srcColor))
}

func (this *QRhiGraphicsPipeline__TargetBlend) DstColor() QRhiGraphicsPipeline__BlendFactor {
	return (QRhiGraphicsPipeline__BlendFactor)(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_dstColor(this.h))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SetDstColor(dstColor QRhiGraphicsPipeline__BlendFactor) {
	C.qtrhi_QRhiGraphicsPipeline__TargetBlend_setDstColor(this.h, (C.int)(dstColor))
}

func (this *QRhiGraphicsPipeline__TargetBlend) OpColor() QRhiGraphicsPipeline__BlendOp {
	return (QRhiGraphicsPipeline__BlendOp)(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_opColor(this.h))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SetOpColor(opColor QRhiGraphicsPipeline__BlendOp) {
	C.qtrhi_QRhiGraphicsPipeline__TargetBlend_setOpColor(this.h, (C.int)(opColor))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SrcAlpha() QRhiGraphicsPipeline__BlendFactor {
	return (QRhiGraphicsPipeline__BlendFactor)(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_srcAlpha(this.h))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SetSrcAlpha(srcAlpha QRhiGraphicsPipeline__BlendFactor) {
	C.qtrhi_QRhiGraphicsPipeline__TargetBlend_setSrcAlpha(this.h, (C.int)(srcAlpha))
}

func (this *QRhiGraphicsPipeline__TargetBlend) DstAlpha() QRhiGraphicsPipeline__BlendFactor {
	return (QRhiGraphicsPipeline__BlendFactor)(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_dstAlpha(this.h))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SetDstAlpha(dstAlpha QRhiGraphicsPipeline__BlendFactor) {
	C.qtrhi_QRhiGraphicsPipeline__TargetBlend_setDstAlpha(this.h, (C.int)(dstAlpha))
}

func (this *QRhiGraphicsPipeline__TargetBlend) OpAlpha() QRhiGraphicsPipeline__BlendOp {
	return (QRhiGraphicsPipeline__BlendOp)(C.qtrhi_QRhiGraphicsPipeline__TargetBlend_opAlpha(this.h))
}

func (this *QRhiGraphicsPipeline__TargetBlend) SetOpAlpha(opAlpha QRhiGraphicsPipeline__BlendOp) {
	C.qtrhi_QRhiGraphicsPipeline__TargetBlend_setOpAlpha(this.h, (C.int)(opAlpha))
}

// Delete this object from C++ memory.
func (this *QRhiGraphicsPipeline__TargetBlend) Delete() {
	C.qtrhi_QRhiGraphicsPipeline__TargetBlend_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiGraphicsPipeline__TargetBlend) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiGraphicsPipeline__TargetBlend) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QRhiGraphicsPipeline__StencilOpState struct {
	h *C.QRhiGraphicsPipeline__StencilOpState
}

func (this *QRhiGraphicsPipeline__StencilOpState) cPointer() *C.QRhiGraphicsPipeline__StencilOpState {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QRhiGraphicsPipeline__StencilOpState) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQRhiGraphicsPipeline__StencilOpState constructs the type using only CGO pointers.
func newQRhiGraphicsPipeline__StencilOpState(h *C.QRhiGraphicsPipeline__StencilOpState) *QRhiGraphicsPipeline__StencilOpState {
	if h == nil {
		return nil
	}

	return &QRhiGraphicsPipeline__StencilOpState{h: h}
}

// UnsafeNewQRhiGraphicsPipeline__StencilOpState constructs the type using only unsafe pointers.
func UnsafeNewQRhiGraphicsPipeline__StencilOpState(h unsafe.Pointer) *QRhiGraphicsPipeline__StencilOpState {
	return newQRhiGraphicsPipeline__StencilOpState((*C.QRhiGraphicsPipeline__StencilOpState)(h))
}

// NewQRhiGraphicsPipeline__StencilOpState constructs a new QRhiGraphicsPipeline::StencilOpState object.
func NewQRhiGraphicsPipeline__StencilOpState() *QRhiGraphicsPipeline__StencilOpState {

	return newQRhiGraphicsPipeline__StencilOpState(C.qtrhi_QRhiGraphicsPipeline__StencilOpState_new())
}

// NewQRhiGraphicsPipeline__StencilOpState2 constructs a new QRhiGraphicsPipeline::StencilOpState object.
func NewQRhiGraphicsPipeline__StencilOpState2(param1 *QRhiGraphicsPipeline__StencilOpState) *QRhiGraphicsPipeline__StencilOpState {

	return newQRhiGraphicsPipeline__StencilOpState(C.qtrhi_QRhiGraphicsPipeline__StencilOpState_new2(param1.cPointer()))
}

func (this *QRhiGraphicsPipeline__StencilOpState) FailOp() QRhiGraphicsPipeline__StencilOp {
	return (QRhiGraphicsPipeline__StencilOp)(C.qtrhi_QRhiGraphicsPipeline__StencilOpState_failOp(this.h))
}

func (this *QRhiGraphicsPipeline__StencilOpState) SetFailOp(failOp QRhiGraphicsPipeline__StencilOp) {
	C.qtrhi_QRhiGraphicsPipeline__StencilOpState_setFailOp(this.h, (C.int)(failOp))
}

func (this *QRhiGraphicsPipeline__StencilOpState) DepthFailOp() QRhiGraphicsPipeline__StencilOp {
	return (QRhiGraphicsPipeline__StencilOp)(C.qtrhi_QRhiGraphicsPipeline__StencilOpState_depthFailOp(this.h))
}

func (this *QRhiGraphicsPipeline__StencilOpState) SetDepthFailOp(depthFailOp QRhiGraphicsPipeline__StencilOp) {
	C.qtrhi_QRhiGraphicsPipeline__StencilOpState_setDepthFailOp(this.h, (C.int)(depthFailOp))
}

func (this *QRhiGraphicsPipeline__StencilOpState) PassOp() QRhiGraphicsPipeline__StencilOp {
	return (QRhiGraphicsPipeline__StencilOp)(C.qtrhi_QRhiGraphicsPipeline__StencilOpState_passOp(this.h))
}

func (this *QRhiGraphicsPipeline__StencilOpState) SetPassOp(passOp QRhiGraphicsPipeline__StencilOp) {
	C.qtrhi_QRhiGraphicsPipeline__StencilOpState_setPassOp(this.h, (C.int)(passOp))
}

func (this *QRhiGraphicsPipeline__StencilOpState) CompareOp() QRhiGraphicsPipeline__CompareOp {
	return (QRhiGraphicsPipeline__CompareOp)(C.qtrhi_QRhiGraphicsPipeline__StencilOpState_compareOp(this.h))
}

func (this *QRhiGraphicsPipeline__StencilOpState) SetCompareOp(compareOp QRhiGraphicsPipeline__CompareOp) {
	C.qtrhi_QRhiGraphicsPipeline__StencilOpState_setCompareOp(this.h, (C.int)(compareOp))
}

// Delete this object from C++ memory.
func (this *QRhiGraphicsPipeline__StencilOpState) Delete() {
	C.qtrhi_QRhiGraphicsPipeline__StencilOpState_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QRhiGraphicsPipeline__StencilOpState) GoGC() {
	runtime.SetFinalizer(this, func(this *QRhiGraphicsPipeline__StencilOpState) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

// QtVersion is the exact Qt SDK version used for generation.
const QtVersion = "6.11.2"
