//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
#include <memory>
#include <QImage>
#include <QQuickGraphicsConfiguration>
#include <QQuickWindow>
#include <rhi/qrhi.h>
#include <QWindow>
#include <qquickwindow.h>
#include "gen_qquickwindow.h"

#ifdef __cplusplus
extern "C" {
#endif

void qtrhi_miqt_exec_callback_QQuickWindow_beforeSynchronizing(intptr_t);
void qtrhi_miqt_exec_callback_QQuickWindow_beforeRendering(intptr_t);
void qtrhi_miqt_exec_callback_QQuickWindow_afterRendering(intptr_t);
void qtrhi_miqt_exec_callback_QQuickWindow_beforeFrameBegin(intptr_t);
void qtrhi_miqt_exec_callback_QQuickWindow_afterFrameEnd(intptr_t);
#ifdef __cplusplus
} /* extern C */
#endif

extern "C" void qtrhi_native_destroyed(void*);
extern "C" void qtrhi_callback_released(intptr_t);
void qtrhi_QQuickWindow_virtbase(QQuickWindow* src, QWindow** outptr_QWindow) {
	*outptr_QWindow = static_cast<QWindow*>(src);
}

QImage* qtrhi_QQuickWindow_grabWindow(QQuickWindow* self) {
	return new QImage(self->grabWindow());
}

double qtrhi_QQuickWindow_effectiveDevicePixelRatio(const QQuickWindow* self) {
	return self->effectiveDevicePixelRatio();
}

void qtrhi_QQuickWindow_setGraphicsConfiguration(QQuickWindow* self, QQuickGraphicsConfiguration* config) {
	self->setGraphicsConfiguration(*config);
}

QRhi* qtrhi_QQuickWindow_rhi(const QQuickWindow* self) {
	return self->rhi();
}

void qtrhi_QQuickWindow_beforeSynchronizing(QQuickWindow* self) {
	self->beforeSynchronizing();
}

void* qtrhi_QQuickWindow_connect_beforeSynchronizing(QQuickWindow* self, intptr_t slot) {
	auto qtrhi_lifetime = std::shared_ptr<intptr_t>(new intptr_t(slot), [](intptr_t *p) { qtrhi_callback_released(*p); delete p; });
	auto connection = QQuickWindow::connect(self, static_cast<void (QQuickWindow::*)()>(&QQuickWindow::beforeSynchronizing), self, [qtrhi_lifetime]() {
		const auto qtrhi_call_lifetime = qtrhi_lifetime;
		qtrhi_miqt_exec_callback_QQuickWindow_beforeSynchronizing(*qtrhi_call_lifetime);
	}, Qt::DirectConnection);
	return new QMetaObject::Connection(connection);
}

void qtrhi_QQuickWindow_beforeRendering(QQuickWindow* self) {
	self->beforeRendering();
}

void* qtrhi_QQuickWindow_connect_beforeRendering(QQuickWindow* self, intptr_t slot) {
	auto qtrhi_lifetime = std::shared_ptr<intptr_t>(new intptr_t(slot), [](intptr_t *p) { qtrhi_callback_released(*p); delete p; });
	auto connection = QQuickWindow::connect(self, static_cast<void (QQuickWindow::*)()>(&QQuickWindow::beforeRendering), self, [qtrhi_lifetime]() {
		const auto qtrhi_call_lifetime = qtrhi_lifetime;
		qtrhi_miqt_exec_callback_QQuickWindow_beforeRendering(*qtrhi_call_lifetime);
	}, Qt::DirectConnection);
	return new QMetaObject::Connection(connection);
}

void qtrhi_QQuickWindow_afterRendering(QQuickWindow* self) {
	self->afterRendering();
}

void* qtrhi_QQuickWindow_connect_afterRendering(QQuickWindow* self, intptr_t slot) {
	auto qtrhi_lifetime = std::shared_ptr<intptr_t>(new intptr_t(slot), [](intptr_t *p) { qtrhi_callback_released(*p); delete p; });
	auto connection = QQuickWindow::connect(self, static_cast<void (QQuickWindow::*)()>(&QQuickWindow::afterRendering), self, [qtrhi_lifetime]() {
		const auto qtrhi_call_lifetime = qtrhi_lifetime;
		qtrhi_miqt_exec_callback_QQuickWindow_afterRendering(*qtrhi_call_lifetime);
	}, Qt::DirectConnection);
	return new QMetaObject::Connection(connection);
}

void qtrhi_QQuickWindow_beforeFrameBegin(QQuickWindow* self) {
	self->beforeFrameBegin();
}

void* qtrhi_QQuickWindow_connect_beforeFrameBegin(QQuickWindow* self, intptr_t slot) {
	auto qtrhi_lifetime = std::shared_ptr<intptr_t>(new intptr_t(slot), [](intptr_t *p) { qtrhi_callback_released(*p); delete p; });
	auto connection = QQuickWindow::connect(self, static_cast<void (QQuickWindow::*)()>(&QQuickWindow::beforeFrameBegin), self, [qtrhi_lifetime]() {
		const auto qtrhi_call_lifetime = qtrhi_lifetime;
		qtrhi_miqt_exec_callback_QQuickWindow_beforeFrameBegin(*qtrhi_call_lifetime);
	}, Qt::DirectConnection);
	return new QMetaObject::Connection(connection);
}

void qtrhi_QQuickWindow_afterFrameEnd(QQuickWindow* self) {
	self->afterFrameEnd();
}

void* qtrhi_QQuickWindow_connect_afterFrameEnd(QQuickWindow* self, intptr_t slot) {
	auto qtrhi_lifetime = std::shared_ptr<intptr_t>(new intptr_t(slot), [](intptr_t *p) { qtrhi_callback_released(*p); delete p; });
	auto connection = QQuickWindow::connect(self, static_cast<void (QQuickWindow::*)()>(&QQuickWindow::afterFrameEnd), self, [qtrhi_lifetime]() {
		const auto qtrhi_call_lifetime = qtrhi_lifetime;
		qtrhi_miqt_exec_callback_QQuickWindow_afterFrameEnd(*qtrhi_call_lifetime);
	}, Qt::DirectConnection);
	return new QMetaObject::Connection(connection);
}
