//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
#include <QByteArray>
#include <rhi/qshader.h>
#include <rhi/qshader.h>
#include "gen_qshader.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern C */
#endif

extern "C" void qtrhi_native_destroyed(void*);
extern "C" void qtrhi_callback_released(intptr_t);
QShader* qtrhi_QShader_new() {
	return new (std::nothrow) QShader();
}

QShader* qtrhi_QShader_new2(QShader* other) {
	return new (std::nothrow) QShader(*other);
}

bool qtrhi_QShader_isValid(const QShader* self) {
	return self->isValid();
}

QShader* qtrhi_QShader_fromSerialized(struct miqt_string data) {
	QByteArray data_QByteArray(data.data, data.len);
	return new QShader(QShader::fromSerialized(data_QByteArray));
}

void qtrhi_QShader_delete(QShader* self) {
	delete self;
}
