//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
#include <QQuickGraphicsConfiguration>
#include <qquickgraphicsconfiguration.h>
#include "gen_qquickgraphicsconfiguration.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern C */
#endif

extern "C" void qtrhi_native_destroyed(void*);
extern "C" void qtrhi_callback_released(intptr_t);
QQuickGraphicsConfiguration* qtrhi_QQuickGraphicsConfiguration_new() {
	return new (std::nothrow) QQuickGraphicsConfiguration();
}

QQuickGraphicsConfiguration* qtrhi_QQuickGraphicsConfiguration_new2(QQuickGraphicsConfiguration* other) {
	return new (std::nothrow) QQuickGraphicsConfiguration(*other);
}

void qtrhi_QQuickGraphicsConfiguration_setTimestamps(QQuickGraphicsConfiguration* self, bool enable) {
	self->setTimestamps(enable);
}

void qtrhi_QQuickGraphicsConfiguration_delete(QQuickGraphicsConfiguration* self) {
	delete self;
}
