//go:build vecmap_rhi

// Code generated by qt-rhi-gen using MIQT v0.14.0; DO NOT EDIT.
package qtrhi

/*

#include "gen_qquickwindow.h"
#include <stdlib.h>

*/
import "C"

import (
	"github.com/mappu/miqt/qt6"
	"runtime/cgo"
	"unsafe"
)

type QQuickWindow__CreateTextureOption int

const (
	QQuickWindow__TextureHasAlphaChannel QQuickWindow__CreateTextureOption = 1
	QQuickWindow__TextureHasMipmaps      QQuickWindow__CreateTextureOption = 2
	QQuickWindow__TextureOwnsGLTexture   QQuickWindow__CreateTextureOption = 4
	QQuickWindow__TextureCanUseAtlas     QQuickWindow__CreateTextureOption = 8
	QQuickWindow__TextureIsOpaque        QQuickWindow__CreateTextureOption = 16
)

type QQuickWindow__RenderStage int

const (
	QQuickWindow__BeforeSynchronizingStage QQuickWindow__RenderStage = 0
	QQuickWindow__AfterSynchronizingStage  QQuickWindow__RenderStage = 1
	QQuickWindow__BeforeRenderingStage     QQuickWindow__RenderStage = 2
	QQuickWindow__AfterRenderingStage      QQuickWindow__RenderStage = 3
	QQuickWindow__AfterSwapStage           QQuickWindow__RenderStage = 4
	QQuickWindow__NoStage                  QQuickWindow__RenderStage = 5
)

type QQuickWindow__SceneGraphError int

const (
	QQuickWindow__ContextNotAvailable QQuickWindow__SceneGraphError = 1
)

type QQuickWindow__TextRenderType int

const (
	QQuickWindow__QtTextRendering     QQuickWindow__TextRenderType = 0
	QQuickWindow__NativeTextRendering QQuickWindow__TextRenderType = 1
	QQuickWindow__CurveTextRendering  QQuickWindow__TextRenderType = 2
)

type QQuickWindow struct {
	h *C.QQuickWindow
	*qt6.QWindow
}

func (this *QQuickWindow) cPointer() *C.QQuickWindow {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QQuickWindow) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQQuickWindow constructs the type using only CGO pointers.
func newQQuickWindow(h *C.QQuickWindow) *QQuickWindow {
	if h == nil {
		return nil
	}
	var outptr_QWindow *C.QWindow = nil
	C.qtrhi_QQuickWindow_virtbase(h, &outptr_QWindow)

	return &QQuickWindow{h: h,
		QWindow: qt6.UnsafeNewQWindow(unsafe.Pointer(outptr_QWindow))}
}

// UnsafeNewQQuickWindow constructs the type using only unsafe pointers.
func UnsafeNewQQuickWindow(h unsafe.Pointer) *QQuickWindow {
	return newQQuickWindow((*C.QQuickWindow)(h))
}

func (this *QQuickWindow) GrabWindow() *qt6.QImage {
	_goptr := qt6.UnsafeNewQImage(unsafe.Pointer(C.qtrhi_QQuickWindow_grabWindow(this.h)))
	return _goptr
}

func (this *QQuickWindow) EffectiveDevicePixelRatio() float64 {
	return (float64)(C.qtrhi_QQuickWindow_effectiveDevicePixelRatio(this.h))
}

func (this *QQuickWindow) SetGraphicsConfiguration(config *QQuickGraphicsConfiguration) {
	C.qtrhi_QQuickWindow_setGraphicsConfiguration(this.h, config.cPointer())
}

func (this *QQuickWindow) Rhi() *QRhi {
	return newQRhi(C.qtrhi_QQuickWindow_rhi(this.h))
}

func (this *QQuickWindow) AfterFrameEnd() {
	C.qtrhi_QQuickWindow_afterFrameEnd(this.h)
}
func (this *QQuickWindow) OnAfterFrameEnd(slot func()) *SignalConnection {
	return newSignalConnection(unsafe.Pointer(C.qtrhi_QQuickWindow_connect_afterFrameEnd(this.h, C.intptr_t(cgo.NewHandle(slot)))))
}

//export qtrhi_miqt_exec_callback_QQuickWindow_afterFrameEnd
func qtrhi_miqt_exec_callback_QQuickWindow_afterFrameEnd(cb C.intptr_t) {
	gofunc, ok := cgo.Handle(cb).Value().(func())
	if !ok {
		panic("miqt: callback of non-callback type (heap corruption?)")
	}

	gofunc()
}
