// Code generated by miqt; DO NOT EDIT.

package quick

/*

#include "gen_qsgflatcolormaterial.h"
#include <stdlib.h>

*/
import "C"

import (
	"github.com/mappu/miqt/qt6"
	"runtime"
	"unsafe"
)

type QSGFlatColorMaterial struct {
	h *C.QSGFlatColorMaterial
	*QSGMaterial
}

func (this *QSGFlatColorMaterial) cPointer() *C.QSGFlatColorMaterial {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGFlatColorMaterial) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGFlatColorMaterial constructs the type using only CGO pointers.
func newQSGFlatColorMaterial(h *C.QSGFlatColorMaterial) *QSGFlatColorMaterial {
	if h == nil {
		return nil
	}
	var outptr_QSGMaterial *C.QSGMaterial = nil
	C.QSGFlatColorMaterial_virtbase(h, &outptr_QSGMaterial)

	return &QSGFlatColorMaterial{h: h,
		QSGMaterial: newQSGMaterial(outptr_QSGMaterial)}
}

// UnsafeNewQSGFlatColorMaterial constructs the type using only unsafe pointers.
func UnsafeNewQSGFlatColorMaterial(h unsafe.Pointer) *QSGFlatColorMaterial {
	return newQSGFlatColorMaterial((*C.QSGFlatColorMaterial)(h))
}

// NewQSGFlatColorMaterial constructs a new QSGFlatColorMaterial object.
func NewQSGFlatColorMaterial() *QSGFlatColorMaterial {

	return newQSGFlatColorMaterial(C.QSGFlatColorMaterial_new())
}

func (this *QSGFlatColorMaterial) SetColor(color *qt6.QColor) {
	C.QSGFlatColorMaterial_setColor(this.h, (*C.QColor)(color.UnsafePointer()))
}

// Delete this object from C++ memory.
func (this *QSGFlatColorMaterial) Delete() {
	C.QSGFlatColorMaterial_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QSGFlatColorMaterial) GoGC() {
	runtime.SetFinalizer(this, func(this *QSGFlatColorMaterial) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}
