// Code generated by miqt; DO NOT EDIT.

package quick

/*

#include "gen_qsggeometry.h"
#include <stdlib.h>

*/
import "C"

import (
	"runtime"
	"unsafe"
)

type QSGGeometry__AttributeType int

const (
	QSGGeometry__UnknownAttribute   QSGGeometry__AttributeType = 0
	QSGGeometry__PositionAttribute  QSGGeometry__AttributeType = 1
	QSGGeometry__ColorAttribute     QSGGeometry__AttributeType = 2
	QSGGeometry__TexCoordAttribute  QSGGeometry__AttributeType = 3
	QSGGeometry__TexCoord1Attribute QSGGeometry__AttributeType = 4
	QSGGeometry__TexCoord2Attribute QSGGeometry__AttributeType = 5
)

type QSGGeometry__DataPattern int

const (
	QSGGeometry__AlwaysUploadPattern QSGGeometry__DataPattern = 0
	QSGGeometry__StreamPattern       QSGGeometry__DataPattern = 1
	QSGGeometry__DynamicPattern      QSGGeometry__DataPattern = 2
	QSGGeometry__StaticPattern       QSGGeometry__DataPattern = 3
)

type QSGGeometry__DrawingMode int

const (
	QSGGeometry__DrawPoints        QSGGeometry__DrawingMode = 0
	QSGGeometry__DrawLines         QSGGeometry__DrawingMode = 1
	QSGGeometry__DrawLineLoop      QSGGeometry__DrawingMode = 2
	QSGGeometry__DrawLineStrip     QSGGeometry__DrawingMode = 3
	QSGGeometry__DrawTriangles     QSGGeometry__DrawingMode = 4
	QSGGeometry__DrawTriangleStrip QSGGeometry__DrawingMode = 5
	QSGGeometry__DrawTriangleFan   QSGGeometry__DrawingMode = 6
)

type QSGGeometry__Type int

const (
	QSGGeometry__ByteType          QSGGeometry__Type = 5120
	QSGGeometry__UnsignedByteType  QSGGeometry__Type = 5121
	QSGGeometry__ShortType         QSGGeometry__Type = 5122
	QSGGeometry__UnsignedShortType QSGGeometry__Type = 5123
	QSGGeometry__IntType           QSGGeometry__Type = 5124
	QSGGeometry__UnsignedIntType   QSGGeometry__Type = 5125
	QSGGeometry__FloatType         QSGGeometry__Type = 5126
	QSGGeometry__Bytes2Type        QSGGeometry__Type = 5127
	QSGGeometry__Bytes3Type        QSGGeometry__Type = 5128
	QSGGeometry__Bytes4Type        QSGGeometry__Type = 5129
	QSGGeometry__DoubleType        QSGGeometry__Type = 5130
)

type QSGGeometry struct {
	h *C.QSGGeometry
}

func (this *QSGGeometry) cPointer() *C.QSGGeometry {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGGeometry) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGGeometry constructs the type using only CGO pointers.
func newQSGGeometry(h *C.QSGGeometry) *QSGGeometry {
	if h == nil {
		return nil
	}

	return &QSGGeometry{h: h}
}

// UnsafeNewQSGGeometry constructs the type using only unsafe pointers.
func UnsafeNewQSGGeometry(h unsafe.Pointer) *QSGGeometry {
	return newQSGGeometry((*C.QSGGeometry)(h))
}

// NewQSGGeometry constructs a new QSGGeometry object.
func NewQSGGeometry(attribs *QSGGeometry__AttributeSet, vertexCount int) *QSGGeometry {

	return newQSGGeometry(C.QSGGeometry_new(attribs.cPointer(), (C.int)(vertexCount)))
}

// NewQSGGeometry2 constructs a new QSGGeometry object.
func NewQSGGeometry2(attribs *QSGGeometry__AttributeSet, vertexCount int, indexCount int) *QSGGeometry {

	return newQSGGeometry(C.QSGGeometry_new2(attribs.cPointer(), (C.int)(vertexCount), (C.int)(indexCount)))
}

// NewQSGGeometry3 constructs a new QSGGeometry object.
func NewQSGGeometry3(attribs *QSGGeometry__AttributeSet, vertexCount int, indexCount int, indexType int) *QSGGeometry {

	return newQSGGeometry(C.QSGGeometry_new3(attribs.cPointer(), (C.int)(vertexCount), (C.int)(indexCount), (C.int)(indexType)))
}

func QSGGeometry_DefaultAttributes_Point2D() *QSGGeometry__AttributeSet {
	return newQSGGeometry__AttributeSet(C.QSGGeometry_defaultAttributes_Point2D())
}

func (this *QSGGeometry) SetDrawingMode(mode uint) {
	C.QSGGeometry_setDrawingMode(this.h, (C.uint)(mode))
}

func (this *QSGGeometry) VertexDataAsPoint2D() *QSGGeometry__Point2D {
	return newQSGGeometry__Point2D(C.QSGGeometry_vertexDataAsPoint2D(this.h))
}

func (this *QSGGeometry) VertexDataAsPoint2D2() *QSGGeometry__Point2D {
	return newQSGGeometry__Point2D(C.QSGGeometry_vertexDataAsPoint2D2(this.h))
}

func (this *QSGGeometry) MarkVertexDataDirty() {
	C.QSGGeometry_markVertexDataDirty(this.h)
}

// Delete this object from C++ memory.
func (this *QSGGeometry) Delete() {
	C.QSGGeometry_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QSGGeometry) GoGC() {
	runtime.SetFinalizer(this, func(this *QSGGeometry) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QSGGeometry__AttributeSet struct {
	h *C.QSGGeometry__AttributeSet
}

func (this *QSGGeometry__AttributeSet) cPointer() *C.QSGGeometry__AttributeSet {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGGeometry__AttributeSet) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGGeometry__AttributeSet constructs the type using only CGO pointers.
func newQSGGeometry__AttributeSet(h *C.QSGGeometry__AttributeSet) *QSGGeometry__AttributeSet {
	if h == nil {
		return nil
	}

	return &QSGGeometry__AttributeSet{h: h}
}

// UnsafeNewQSGGeometry__AttributeSet constructs the type using only unsafe pointers.
func UnsafeNewQSGGeometry__AttributeSet(h unsafe.Pointer) *QSGGeometry__AttributeSet {
	return newQSGGeometry__AttributeSet((*C.QSGGeometry__AttributeSet)(h))
}

type QSGGeometry__Point2D struct {
	h *C.QSGGeometry__Point2D
}

func (this *QSGGeometry__Point2D) cPointer() *C.QSGGeometry__Point2D {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGGeometry__Point2D) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGGeometry__Point2D constructs the type using only CGO pointers.
func newQSGGeometry__Point2D(h *C.QSGGeometry__Point2D) *QSGGeometry__Point2D {
	if h == nil {
		return nil
	}

	return &QSGGeometry__Point2D{h: h}
}

// UnsafeNewQSGGeometry__Point2D constructs the type using only unsafe pointers.
func UnsafeNewQSGGeometry__Point2D(h unsafe.Pointer) *QSGGeometry__Point2D {
	return newQSGGeometry__Point2D((*C.QSGGeometry__Point2D)(h))
}

func (this *QSGGeometry__Point2D) X() float32 {
	return (float32)(C.QSGGeometry__Point2D_x(this.h))
}

func (this *QSGGeometry__Point2D) SetX(x float32) {
	C.QSGGeometry__Point2D_setX(this.h, (C.float)(x))
}

func (this *QSGGeometry__Point2D) Y() float32 {
	return (float32)(C.QSGGeometry__Point2D_y(this.h))
}

func (this *QSGGeometry__Point2D) SetY(y float32) {
	C.QSGGeometry__Point2D_setY(this.h, (C.float)(y))
}

func (this *QSGGeometry__Point2D) Set(nx float32, ny float32) {
	C.QSGGeometry__Point2D_set(this.h, (C.float)(nx), (C.float)(ny))
}
