// Code generated by miqt; DO NOT EDIT.

package quick

/*

#include "gen_qsgmaterial.h"
#include <stdlib.h>

*/
import "C"

import (
	"runtime"
	"unsafe"
)

type QSGMaterial__Flag int

const (
	QSGMaterial__Blending                          QSGMaterial__Flag = 1
	QSGMaterial__RequiresDeterminant               QSGMaterial__Flag = 2
	QSGMaterial__RequiresFullMatrixExceptTranslate QSGMaterial__Flag = 6
	QSGMaterial__RequiresFullMatrix                QSGMaterial__Flag = 14
	QSGMaterial__NoBatching                        QSGMaterial__Flag = 16
	QSGMaterial__MultiView2                        QSGMaterial__Flag = 65536
	QSGMaterial__MultiView3                        QSGMaterial__Flag = 131072
	QSGMaterial__MultiView4                        QSGMaterial__Flag = 262144
	QSGMaterial__CustomCompileStep                 QSGMaterial__Flag = 16
)

type QSGMaterial struct {
	h *C.QSGMaterial
}

func (this *QSGMaterial) cPointer() *C.QSGMaterial {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGMaterial) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGMaterial constructs the type using only CGO pointers.
func newQSGMaterial(h *C.QSGMaterial) *QSGMaterial {
	if h == nil {
		return nil
	}

	return &QSGMaterial{h: h}
}

// UnsafeNewQSGMaterial constructs the type using only unsafe pointers.
func UnsafeNewQSGMaterial(h unsafe.Pointer) *QSGMaterial {
	return newQSGMaterial((*C.QSGMaterial)(h))
}

// Delete this object from C++ memory.
func (this *QSGMaterial) Delete() {
	C.QSGMaterial_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QSGMaterial) GoGC() {
	runtime.SetFinalizer(this, func(this *QSGMaterial) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}
