// Code generated by miqt; DO NOT EDIT.

package quick

/*

#include "gen_qquickitem.h"
#include <stdlib.h>

*/
import "C"

import (
	"github.com/mappu/miqt/qt6"
	"github.com/mappu/miqt/qt6/qml"
	"runtime"
	"runtime/cgo"
	"unsafe"
)

type QQuickItem__Flag int

const (
	QQuickItem__ItemClipsChildrenToShape QQuickItem__Flag = 1
	QQuickItem__ItemAcceptsInputMethod   QQuickItem__Flag = 2
	QQuickItem__ItemIsFocusScope         QQuickItem__Flag = 4
	QQuickItem__ItemHasContents          QQuickItem__Flag = 8
	QQuickItem__ItemAcceptsDrops         QQuickItem__Flag = 16
	QQuickItem__ItemIsViewport           QQuickItem__Flag = 32
	QQuickItem__ItemObservesViewport     QQuickItem__Flag = 64
)

type QQuickItem__ItemChange int

const (
	QQuickItem__ItemChildAddedChange           QQuickItem__ItemChange = 0
	QQuickItem__ItemChildRemovedChange         QQuickItem__ItemChange = 1
	QQuickItem__ItemSceneChange                QQuickItem__ItemChange = 2
	QQuickItem__ItemVisibleHasChanged          QQuickItem__ItemChange = 3
	QQuickItem__ItemParentHasChanged           QQuickItem__ItemChange = 4
	QQuickItem__ItemOpacityHasChanged          QQuickItem__ItemChange = 5
	QQuickItem__ItemActiveFocusHasChanged      QQuickItem__ItemChange = 6
	QQuickItem__ItemRotationHasChanged         QQuickItem__ItemChange = 7
	QQuickItem__ItemAntialiasingHasChanged     QQuickItem__ItemChange = 8
	QQuickItem__ItemDevicePixelRatioHasChanged QQuickItem__ItemChange = 9
	QQuickItem__ItemEnabledHasChanged          QQuickItem__ItemChange = 10
	QQuickItem__ItemScaleHasChanged            QQuickItem__ItemChange = 11
	QQuickItem__ItemTransformHasChanged        QQuickItem__ItemChange = 12
)

type QQuickItem__TransformOrigin int

const (
	QQuickItem__TopLeft     QQuickItem__TransformOrigin = 0
	QQuickItem__Top         QQuickItem__TransformOrigin = 1
	QQuickItem__TopRight    QQuickItem__TransformOrigin = 2
	QQuickItem__Left        QQuickItem__TransformOrigin = 3
	QQuickItem__Center      QQuickItem__TransformOrigin = 4
	QQuickItem__Right       QQuickItem__TransformOrigin = 5
	QQuickItem__BottomLeft  QQuickItem__TransformOrigin = 6
	QQuickItem__Bottom      QQuickItem__TransformOrigin = 7
	QQuickItem__BottomRight QQuickItem__TransformOrigin = 8
)

type QQuickItem struct {
	h *C.QQuickItem
	*qt6.QObject
	*qml.QQmlParserStatus
}

func (this *QQuickItem) cPointer() *C.QQuickItem {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QQuickItem) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQQuickItem constructs the type using only CGO pointers.
func newQQuickItem(h *C.QQuickItem) *QQuickItem {
	if h == nil {
		return nil
	}
	var outptr_QObject *C.QObject = nil
	var outptr_QQmlParserStatus *C.QQmlParserStatus = nil
	C.QQuickItem_virtbase(h, &outptr_QObject, &outptr_QQmlParserStatus)

	return &QQuickItem{h: h,
		QObject:          qt6.UnsafeNewQObject(unsafe.Pointer(outptr_QObject)),
		QQmlParserStatus: qml.UnsafeNewQQmlParserStatus(unsafe.Pointer(outptr_QQmlParserStatus))}
}

// UnsafeNewQQuickItem constructs the type using only unsafe pointers.
func UnsafeNewQQuickItem(h unsafe.Pointer) *QQuickItem {
	return newQQuickItem((*C.QQuickItem)(h))
}

// NewQQuickItem constructs a new QQuickItem object.
func NewQQuickItem() *QQuickItem {

	return newQQuickItem(C.QQuickItem_new())
}

// NewQQuickItem2 constructs a new QQuickItem object.
func NewQQuickItem2(parent *QQuickItem) *QQuickItem {

	return newQQuickItem(C.QQuickItem_new2(parent.cPointer()))
}

func (this *QQuickItem) Width() float64 {
	return (float64)(C.QQuickItem_width(this.h))
}

func (this *QQuickItem) SetWidth(width float64) {
	C.QQuickItem_setWidth(this.h, (C.double)(width))
}

func (this *QQuickItem) Height() float64 {
	return (float64)(C.QQuickItem_height(this.h))
}

func (this *QQuickItem) SetHeight(height float64) {
	C.QQuickItem_setHeight(this.h, (C.double)(height))
}

func (this *QQuickItem) SetFlag(flag QQuickItem__Flag) {
	C.QQuickItem_setFlag(this.h, (C.int)(flag))
}

func (this *QQuickItem) Update() {
	C.QQuickItem_update(this.h)
}

func (this *QQuickItem) SetFlag2(flag QQuickItem__Flag, enabled bool) {
	C.QQuickItem_setFlag2(this.h, (C.int)(flag), (C.bool)(enabled))
}

func (this *QQuickItem) callVirtualBase_UpdatePaintNode(param1 *QSGNode, param2 *QQuickItem__UpdatePaintNodeData) *QSGNode {

	return newQSGNode(C.QQuickItem_virtualbase_updatePaintNode(unsafe.Pointer(this.h), param1.cPointer(), param2.cPointer()))

}
func (this *QQuickItem) OnUpdatePaintNode(slot func(super func(param1 *QSGNode, param2 *QQuickItem__UpdatePaintNodeData) *QSGNode, param1 *QSGNode, param2 *QQuickItem__UpdatePaintNodeData) *QSGNode) {
	handle := cgo.NewHandle(slot)
	ok := C.QQuickItem_override_virtual_updatePaintNode(unsafe.Pointer(this.h), C.intptr_t(handle))
	if !ok {
		handle.Delete()
		panic("miqt: virtual method can only be overridden once on directly constructed types")
	}
}

//export miqt_exec_callback_QQuickItem_updatePaintNode
func miqt_exec_callback_QQuickItem_updatePaintNode(self *C.QQuickItem, cb C.intptr_t, param1 *C.QSGNode, param2 *C.QQuickItem__UpdatePaintNodeData) *C.QSGNode {
	gofunc, ok := cgo.Handle(cb).Value().(func(super func(param1 *QSGNode, param2 *QQuickItem__UpdatePaintNodeData) *QSGNode, param1 *QSGNode, param2 *QQuickItem__UpdatePaintNodeData) *QSGNode)
	if !ok {
		panic("miqt: callback of non-callback type (heap corruption?)")
	}

	// Convert all CABI parameters to Go parameters
	slotval1 := newQSGNode(param1)

	slotval2 := newQQuickItem__UpdatePaintNodeData(param2)

	virtualReturn := gofunc((&QQuickItem{h: self}).callVirtualBase_UpdatePaintNode, slotval1, slotval2)
	if virtualReturn == nil {
		return nil
	}
	return virtualReturn.cPointer()

}

// Delete this object from C++ memory.
func (this *QQuickItem) Delete() {
	C.QQuickItem_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QQuickItem) GoGC() {
	runtime.SetFinalizer(this, func(this *QQuickItem) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QQuickItem__UpdatePaintNodeData struct {
	h *C.QQuickItem__UpdatePaintNodeData
}

func (this *QQuickItem__UpdatePaintNodeData) cPointer() *C.QQuickItem__UpdatePaintNodeData {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QQuickItem__UpdatePaintNodeData) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQQuickItem__UpdatePaintNodeData constructs the type using only CGO pointers.
func newQQuickItem__UpdatePaintNodeData(h *C.QQuickItem__UpdatePaintNodeData) *QQuickItem__UpdatePaintNodeData {
	if h == nil {
		return nil
	}

	return &QQuickItem__UpdatePaintNodeData{h: h}
}

// UnsafeNewQQuickItem__UpdatePaintNodeData constructs the type using only unsafe pointers.
func UnsafeNewQQuickItem__UpdatePaintNodeData(h unsafe.Pointer) *QQuickItem__UpdatePaintNodeData {
	return newQQuickItem__UpdatePaintNodeData((*C.QQuickItem__UpdatePaintNodeData)(h))
}
