// Code generated by miqt; DO NOT EDIT.

package quick

/*

#include "gen_qsgnode.h"
#include <stdlib.h>

*/
import "C"

import (
	"runtime"
	"unsafe"
)

type QSGNode__NodeType int

const (
	QSGNode__BasicNodeType     QSGNode__NodeType = 0
	QSGNode__GeometryNodeType  QSGNode__NodeType = 1
	QSGNode__TransformNodeType QSGNode__NodeType = 2
	QSGNode__ClipNodeType      QSGNode__NodeType = 3
	QSGNode__OpacityNodeType   QSGNode__NodeType = 4
	QSGNode__RootNodeType      QSGNode__NodeType = 5
	QSGNode__RenderNodeType    QSGNode__NodeType = 6
)

type QSGNode__Flag int

const (
	QSGNode__OwnedByParent      QSGNode__Flag = 1
	QSGNode__UsePreprocess      QSGNode__Flag = 2
	QSGNode__OwnsGeometry       QSGNode__Flag = 65536
	QSGNode__OwnsMaterial       QSGNode__Flag = 131072
	QSGNode__OwnsOpaqueMaterial QSGNode__Flag = 262144
	QSGNode__IsVisitableNode    QSGNode__Flag = 16777216
)

type QSGNode__DirtyStateBit int

const (
	QSGNode__DirtySubtreeBlocked  QSGNode__DirtyStateBit = 128
	QSGNode__DirtyMatrix          QSGNode__DirtyStateBit = 256
	QSGNode__DirtyNodeAdded       QSGNode__DirtyStateBit = 1024
	QSGNode__DirtyNodeRemoved     QSGNode__DirtyStateBit = 2048
	QSGNode__DirtyGeometry        QSGNode__DirtyStateBit = 4096
	QSGNode__DirtyMaterial        QSGNode__DirtyStateBit = 8192
	QSGNode__DirtyOpacity         QSGNode__DirtyStateBit = 16384
	QSGNode__DirtyForceUpdate     QSGNode__DirtyStateBit = 32768
	QSGNode__DirtyUsePreprocess   QSGNode__DirtyStateBit = 2
	QSGNode__DirtyPropagationMask QSGNode__DirtyStateBit = 50432
)

type QSGNode struct {
	h *C.QSGNode
}

func (this *QSGNode) cPointer() *C.QSGNode {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGNode) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGNode constructs the type using only CGO pointers.
func newQSGNode(h *C.QSGNode) *QSGNode {
	if h == nil {
		return nil
	}

	return &QSGNode{h: h}
}

// UnsafeNewQSGNode constructs the type using only unsafe pointers.
func UnsafeNewQSGNode(h unsafe.Pointer) *QSGNode {
	return newQSGNode((*C.QSGNode)(h))
}

func (this *QSGNode) MarkDirty(bits QSGNode__DirtyStateBit) {
	C.QSGNode_markDirty(this.h, (C.int)(bits))
}

func (this *QSGNode) SetFlag(param1 QSGNode__Flag) {
	C.QSGNode_setFlag(this.h, (C.int)(param1))
}

func (this *QSGNode) SetFlag2(param1 QSGNode__Flag, param2 bool) {
	C.QSGNode_setFlag2(this.h, (C.int)(param1), (C.bool)(param2))
}

// Delete this object from C++ memory.
func (this *QSGNode) Delete() {
	C.QSGNode_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QSGNode) GoGC() {
	runtime.SetFinalizer(this, func(this *QSGNode) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QSGBasicGeometryNode struct {
	h *C.QSGBasicGeometryNode
	*QSGNode
}

func (this *QSGBasicGeometryNode) cPointer() *C.QSGBasicGeometryNode {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGBasicGeometryNode) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGBasicGeometryNode constructs the type using only CGO pointers.
func newQSGBasicGeometryNode(h *C.QSGBasicGeometryNode) *QSGBasicGeometryNode {
	if h == nil {
		return nil
	}
	var outptr_QSGNode *C.QSGNode = nil
	C.QSGBasicGeometryNode_virtbase(h, &outptr_QSGNode)

	return &QSGBasicGeometryNode{h: h,
		QSGNode: newQSGNode(outptr_QSGNode)}
}

// UnsafeNewQSGBasicGeometryNode constructs the type using only unsafe pointers.
func UnsafeNewQSGBasicGeometryNode(h unsafe.Pointer) *QSGBasicGeometryNode {
	return newQSGBasicGeometryNode((*C.QSGBasicGeometryNode)(h))
}

func (this *QSGBasicGeometryNode) SetGeometry(geometry *QSGGeometry) {
	C.QSGBasicGeometryNode_setGeometry(this.h, geometry.cPointer())
}

func (this *QSGBasicGeometryNode) Geometry() *QSGGeometry {
	return newQSGGeometry(C.QSGBasicGeometryNode_geometry(this.h))
}

func (this *QSGBasicGeometryNode) Geometry2() *QSGGeometry {
	return newQSGGeometry(C.QSGBasicGeometryNode_geometry2(this.h))
}

// Delete this object from C++ memory.
func (this *QSGBasicGeometryNode) Delete() {
	C.QSGBasicGeometryNode_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QSGBasicGeometryNode) GoGC() {
	runtime.SetFinalizer(this, func(this *QSGBasicGeometryNode) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}

type QSGGeometryNode struct {
	h *C.QSGGeometryNode
	*QSGBasicGeometryNode
}

func (this *QSGGeometryNode) cPointer() *C.QSGGeometryNode {
	if this == nil {
		return nil
	}
	return this.h
}

func (this *QSGGeometryNode) UnsafePointer() unsafe.Pointer {
	if this == nil {
		return nil
	}
	return unsafe.Pointer(this.h)
}

// newQSGGeometryNode constructs the type using only CGO pointers.
func newQSGGeometryNode(h *C.QSGGeometryNode) *QSGGeometryNode {
	if h == nil {
		return nil
	}
	var outptr_QSGBasicGeometryNode *C.QSGBasicGeometryNode = nil
	C.QSGGeometryNode_virtbase(h, &outptr_QSGBasicGeometryNode)

	return &QSGGeometryNode{h: h,
		QSGBasicGeometryNode: newQSGBasicGeometryNode(outptr_QSGBasicGeometryNode)}
}

// UnsafeNewQSGGeometryNode constructs the type using only unsafe pointers.
func UnsafeNewQSGGeometryNode(h unsafe.Pointer) *QSGGeometryNode {
	return newQSGGeometryNode((*C.QSGGeometryNode)(h))
}

// NewQSGGeometryNode constructs a new QSGGeometryNode object.
func NewQSGGeometryNode() *QSGGeometryNode {

	return newQSGGeometryNode(C.QSGGeometryNode_new())
}

func (this *QSGGeometryNode) SetMaterial(material *QSGMaterial) {
	C.QSGGeometryNode_setMaterial(this.h, material.cPointer())
}

func (this *QSGGeometryNode) Material() *QSGMaterial {
	return newQSGMaterial(C.QSGGeometryNode_material(this.h))
}

// Delete this object from C++ memory.
func (this *QSGGeometryNode) Delete() {
	C.QSGGeometryNode_delete(this.h)
}

// GoGC adds a Go Finalizer to this pointer, so that it will be deleted
// from C++ memory once it is unreachable from Go memory.
func (this *QSGGeometryNode) GoGC() {
	runtime.SetFinalizer(this, func(this *QSGGeometryNode) {
		this.Delete()
		runtime.KeepAlive(this.h)
	})
}
